publicsuffix/list

public_suffix_list.dat
---
====
Organization Website: https://www.enalean.com
I am a sysadmin at Enalean, a software development company that makes Tuleap (https://www.tuleap.org)
====
We will host our partners applications on the tuleap-partners.com domain and want them to be secure and fully contained.
We already did that for our customers some years ago for the mytuleap.com domain PR #453
=======
```bash
"https://github.com/publicsuffix/list/pull/1360"
```
make test
=========
Test passed
=> Add tuleap-partners.com

public_suffix_list.dat
Subdomain rs.ba, is domain for Republic of Srpska entity (part of Bosnia and Herzegovina). Applications for domain registrations are submitted through [form](http://urc.rs/index.php/domen) on  web site of Computer Center of University of Banja Luka, or by writing email to domeni@unibl.org (which belongs to University's official site).
====
Organization Website: https://unibl.org and also http://urc.rs/index.php/page/301.
Please see **Extra info** and **Reason for PSL Inclusion** for more information.
====
Different sites, ranging from government to private companies, use .rs.ba domain, which refers to Republic of Srpska, authonomous region of Bosnia and Hercegovina. This affects cookie policy, and how browsers treat these domains in …
=> Add rs.ba suffix

public_suffix_list.dat
=> Adding bitbucket.io pages which render user generated content

public_suffix_list.dat
====
Organization Website: https://riseup.net
I represent Riseup Networks, a not-for-profit organization that has been providing free-software based online communication tools on a donation basis for people and groups for twenty years. 
====
One of the services we provide is a hosted gitlab solution (https://0xacab.org). We are adding the Gitlab `pages` functionality, which requires its own domain where the static sites are hosted on subdomains. Because this service allows members of the public to create sites, it also allows those users to create subdomains on the pages domain. Adding the domain to the Public Suffix List prevents browsers from accepting supercookies. 
The domain requested for PSL …
=> Add itcouldbewor.se to public suffix list

public_suffix_list.dat
=> Adding sellfy.store pages which render user generated content

public_suffix_list.dat
Add nog.community, where we host websites for 3rd party NOGs
====
Organization Website: https://nogalliance.org/
The full name of our organisation is Stichting Global NOG Alliance. Stichting is just the Dutch word for Foundation, and NOG stands for Network Operator Group. Network Operator Groups are often run by volunteers and often not registered as a legal entity. they are places where network operators and engineers meet to share experiences and learn from each other. We provide free services to NOGs like web and email hosting, online conferencing tools, file sharing tools etc. so that they can concentrate on helping their community without having to worry about maintaining their own servers and tools.
Reason for PSL …
=> Add nog.community

public_suffix_list.dat
=> add new domains for thingdust AG

public_suffix_list.dat
=> Add demo.datadetect.com and instance.datadetect.com

public_suffix_list.dat
https://yunohost.org
YunoHost is a server operating system aiming to make self-hosting accessible to everyone.
We have added a new subdomain `ynh.fr` in more of the 2 `noho.st`, `nohost.me`. Those domain allows our user to self-host some services without the need of buying a personal domain and with the advantage to bypass some ISPs dynamic IP and to configure DNS entries automatically.
It could be very usefull, if browser could correctly manage this new subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and dyndns services too.
```
dig +short TXT _psl.ynh.fr
"https://github.com/publicsuffix/list/pull/1380"
```
Here are the validated `make test` …
=> Add YunoHost DynDns domains: ynh.fr

public_suffix_list.dat
=> Add Supabase domains

public_suffix_list.dat
=> Add Spreadshop hosting domains: myspreadshop.com plus country-specific

public_suffix_list.dat
Adds additional alternative domain names for Adobe Experience Manager
---
``` 
it will stay that …
```
=> add Adobe Project Helix domains to the list

public_suffix_list.dat
---
eero is a provider of a home WiFi system. It is owned by Amazon.com, Inc.
Organization Website: https://eero.com/
eero will soon release a feature that allows user-controlled content to exist on .eero.online. We are submitting these domains to the list to ensure they are correctly treated by browsers.
=======
~ $ dig +short TXT _psl.eero-stage.online
"https://github.com/publicsuffix/list/pull/1359"
~ $ dig +short TXT _psl.eero.online
"https://github.com/publicsuffix/list/pull/1359"
=> add eero ddns domains

public_suffix_list.dat
Proactively extends DELETIONS on inactive nymnom names that ocurred in #1383 to whole section - Please read issue #1354
====
NymNom, the organization that submitted and managed this section, has allowed registration to lapse on the majority of the domains that they had submitted as eTLD+1 - which they should be maintaining / removing or updating the PSL section for.  Names being removed manually due to security concerns raised in #1354 has already ocurred in #1388, which was a very time-consuming process for the volunteers here on PSL maintainence. 
While it is typical that entities have a 'set and forget' approach to their entries in the PSL, the fact is that there is a requirement to remove entries when domains expire or are no longer needed.  We may revise the …
=> DEL whole nymnom section due to mass atrophy

public_suffix_list.dat
I was emailed these changes and will open a PR that will await them adding the PR text record matching the pull request number with a _psl text record in the .ve zone directly to validate before merging the change into the PSL
---
``` 
It is not within the PSL volunteers' control …
```
=> Updating .ve (Venezuela) entries and contact info

public_suffix_list.dat
Years ago we needed these addresses for our customers. We have moved away from these domains and are able to what we need with a new setup and new domain.
We are trying to clean all up so we don't leave anything in a broken state.
Do I need to remove the TXT entry on our end first? 
```
dig +short TXT _psl.customer.enonic.io. 
"https://github.com/publicsuffix/list/pull/330"
```
=> these domains are being deprecated, we wish to clean up after ourselves

public_suffix_list.dat
=> Adds pages.it.hs-heilbronn.de

public_suffix_list.dat
====
Organization Website: https://tabit.cloud/
Tabit is a restaurant ordering system as well as a point-of-sale that streamlines restaurant operations and extends sales opportunities.
Our 360 degree integrated ecosystem connects every aspect of the customer experience: from guest management, customer ordering and kitchen productivity to tableside payment, bringing efficiencies to every interaction point.
====
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so.  Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event …
=> Tabitorder.co.il

public_suffix_list.dat
Description of Organisation
====
Organisation Website: https://www.woodsvalldata.co.uk/
WoodsValldata is a charity fundraising service provider.
I am a software developer at WoodsValldata catering for the hosted raffle and lottery websites that we provide.
====
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so.  Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.
We have reviewed the wiki here outlining the PSL and understand what it is and is not.
We have reviewed this matter with the team at Facebook, we are now fully …
=> Add affinitylottery.org.uk raffleentry.org.uk and weeklylottery.org.uk to public suffix list

public_suffix_list.dat
---
====
Organization Website: https://lokalized.nl
Providing hosting for websites and servers. We are working on a platform that can host websites and provide a secure environment for testing and deployment. We also strive to make an option to proxy to your own server (like ngrok.io). Use cases are: proxying, hosting your static content and deploy scalable apps with for example multiple nodes.
====
Needed for Cookie Security due to the different websites (with "subdomains") on the hosting. Due to having multiple websites hosted by different people, we want to make it as secure as possible, therefore needing the PSL which will make the sites less vulnerable for same-site attacks.
DNS Verification …
=> Added Lokalized domain

public_suffix_list.dat
foo.bar and *.foo.bar can't both be added, and I let #1393 through, where the linter typically catches and fails them.
It subsequently causes failed imports on some browser inclusions, so this must be backed out.
@pereceh you must re-sumbit and choose only one of each, please reference #1393 in the new PR - leaving the prior _psl txt record is fine when you re-submit 
// Diher Solutions : https://diher.solutions
// Submitted by Didi Hermawan <mail@diher.solutions>
rss.my.id
*.rss.my.id
diher.solutions
*.diher.solutions
=> Roll back diher.solutions PR #1393

public_suffix_list.dat
=> Add instances.spawn.cc

public_suffix_list.dat
As per reference [#1406](https://github.com/publicsuffix/list/pull/1406) , i want to remove wildcard characters for rss.my.id and diher.solutions to make them look better. I also used the previous _psl txt record [#1393](https://github.com/publicsuffix/list/pull/1393) .
=> Update rss.my.id and diher.solutions

public_suffix_list.dat
=> Update (remove) .tn entries

public_suffix_list.dat
Add all regions of DigitalOcean Spaces to the PSL, to deliniate the
names which can be registered by users. This mirrors the inclusion of
Amazon S3.
Please note the contact email address goes to a superset of the domain
registration group, suitable for reaching all critical points of contact
regarding DigitalOcean's PSL entries.
Signed-off-by: Robin H. Johnson <rjohnson@digitalocean.com>
---
``` 
core domain name in ways that could be problematic for …
```
=> Add digitaloceanspaces.com & regional subdomains

public_suffix_list.dat
=> Add sandbox.usercontent.goog

public_suffix_list.dat
Hi,
We are letting go an unused domain name on October 22th and would like to clean up before.
This PR simply removes the entry I made in the first time to the list. I already removed the `_psl` TXT entry from the zone file.
Thanks in advance.
Best,
=> Remove clic2000.net from Private Section

public_suffix_list.dat
=> Adding upli.io

public_suffix_list.dat
---
====
Organization Website: https://www.linode.com
I am an Engineer at Linode.
We are a cloud hosting provider, offering Linux virtual machines (Linodes), a hosted load balancing solution (NodeBalancers), S3 compatible object storage, and other hosted services.
====
We are requesting the addition of `ip.linodeusercontent.com`. We are in the process of transitioning our users from `*.members.linode.com` and `*.nodebalancer.linode.com` to this new domain, away from a subdomain of our business domain at `linode.com`. These domain records are provided as a convenience to our customers for each virtual machine and load balancer.
Both `members.linode.com` and `nodebalancer.linode.com` domains are …
=> add ip.linodeusercontent.com

public_suffix_list.dat
---
**For Private section requests that are submitting entries for domains that match their organization website's primary domain:**
```
Your request could very likely alter the cookie and certificate (as well as other) behaviours on your
It is not within the PSL volunteers' control to do anything about that.
The volunteers are busy with new requests, and rollbacks are lowest priority, so if something gets broken
```
(Link: [about …
=> Add siiites.com

public_suffix_list.dat
====
gb.com is not owned or operated by CentralNic anymore, should be removed.
We're the current owner of this domain, would like it removed from the list.
=======
```
dig +short TXT _psl.gb.com
"https://github.com/publicsuffix/list/pull/1467"
```
make test
=========
```
Making check in tests
CC       test-is-public.o
CC       test-is-cookie-domain-acceptable.o
CC       test-is-public-all.o …
```
=> Remove: gb.com

public_suffix_list.dat
This reverts commit 1e3d816c08debd4474b1c192b3660b4c331f8a85.
The domain amsw.nl is no longer in use and now belongs to a party that
is not affiliated with Amsterdam Wireless.
The original PR that was used for PSL inclusion can be found here: https://github.com/publicsuffix/list/pull/929
=> Revert "Add amsw.nl private domain to PSL (#929)"

public_suffix_list.dat
=> Add 9 BASE, Inc. domains to private section

public_suffix_list.dat
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we seek to resolve the impacts to the best of our ability to do so. Both Apple and Facebook support Public Suffix List for Private Click Measurement and Aggregated Event Measurement respectively.
* We have reviewed the wiki here outlining the PSL and understand what it is and is not.
* We have reviewed this matter with the team at Facebook, we are now fully aware about the consequences to the change we are requesting as it relates to cookies or other services, and choose to proceed in submitting this PR. We understand that despite reviewing the matter with Facebook, Facebook cannot control which use cases get accepted to the PSL
* We …
=> Please add koobin.events to the PSL

public_suffix_list.dat
Undoing: 
https://github.com/publicsuffix/list/pull/431
Removing `nodum.co` / `nodum.io`.
_psl DNS entry already removed.
Reference to this PR in DNS:
`_psl_remove.nodum.io	text = "https://github.com/publicsuffix/list/pull/1444"`
=> Remove nodum domains

public_suffix_list.dat
Teckids e.V. is an organisation that works on everything around young people, educaiton, and free software. It provides a large set of services to bring free software and open education to everyone.
* `edugit.io` should be added to replace to `edugit.org` (see #736, #972)
* `s3.teckids.org` is the base domain for Teckids' new objcet storage platform, which will host buckets under sub-domains, with buckets potentially including web assets that might be able to set cross-origin cookies
```plain
❯ dig +short _psl.edugit.org. TXT
"https://github.com/publicsuffix/list/pull/736"
"https://github.com/publicsuffix/list/pull/1463"
❯ dig +short _psl.edugit.io. TXT
"https://github.com/publicsuffix/list/pull/1463"
❯ dig +short _psl.s3.teckids.org. TXT
"https://github.com/publicsuffix/list/pull/1463" …
```
=> Replace edugit.org with edugit.io and add s3.teckids.org for Teckids

public_suffix_list.dat
=> Add NoSpamProxy Cloud domain: cloud.nospamproxy.com

public_suffix_list.dat
====
Organization Website: https://www.encoway.de/en/
encoway GmbH provides companies from the manufacturing industry with CPQ software.
====
For each installation our clients get a subdomain of eu.encoway.cloud so they can access their system via web without having to incure additional fees for domains, static IP address or dyndns as this is handled by our system. Since each installation belongs to a separated legal entity and deals with that entity valuable information, security is top concern for us and our clients. It has proven that having the subdomains recognized by the browsers as separate domains and not share cookies or other vital information is a good working practice.
=======
```
dig +short TXT …
```
=> Add encoway domain: eu.encoway.cloud

public_suffix_list.dat
I'm not sure if the above 👆 is intended for the reviewers or me to fill. Left it empty, but all the items here are checked.
---
---
====
Organization Website - company - https://hibernatingrhinos.com/ - product - https://ravendb.net
Hibernating Rhinos produces the RavenDB database, a NoSQL Document Database that can run on premise or in the cloud.
We provide our users with clusters that are running on `ravendb.cloud` subdomains. Each customer has each own independent subdomain and they are completely isolated from one another.
Those database clusters are offered from https://cloud.ravendb.net and …
=> Adding ravendb.cloud domain to allow separation between users

public_suffix_list.dat
=> Add `site.tb-hosting.com` for team.blue

public_suffix_list.dat
Signed-off-by: Jamie Tanna <jamie.tanna@digital.cabinet-office.gov.uk>
=> Add CDDO's `api.gov.uk` domain

public_suffix_list.dat
---
====
Organization Website: [GDS](https://www.gov.uk/government/organisations/government-digital-service)
The Government Digital Service is department of the Cabinet Office, we are responsible for the management and delegation for many of the core domains used within the UK Government.
Further details: https://www.gov.uk/service-manual/technology/managing-domain-names
The following domains, submitted for inclusion on the public suffix list, are within GDS' control:
- independent-commission.uk
- independent-inquest.uk
- independent-inquiry.uk
- independent-panel.uk
- independent-review.uk
- public-inquiry.uk
- royal-commission.uk
I am Stephen Ford, Tech Lead/Senior Site Reliability Engineer, representative of the team …
=> Add: GDS Managed Domains

public_suffix_list.dat
---
```
Seriously, carefully read the downline flow of the PSL and the
guidelines. Your request could very likely alter the cookie and
certificate (as well as other) behaviors on your core domain name in
Rollback is really not predictable, as those who use or incorporate
the PSL do what they do, and when. It is not within the PSL volunteers'
control to do anything about that.
The volunteers are busy with new requests, and rollbacks are lowest
priority, so if something gets broken by your PR, it will potentially
```
(Link: [about …
=> Add `vultrobjects.com` and future regional subdomains

public_suffix_list.dat
This adds link to URL of reg policies that articulates the TLD structure within .cy
https://www.nic.cy/portal//sites/default/files/symfonia_gia_eggrafi.pdf
Further detail is present in #1516 sunmitted by @panayiotou
---
====
Organization Website: [https://nic.cy](https://nic.cy)
====
This is being submitted to address the request in Issue #1516 to reflect the updated .cy namespace.
@weppos or @sleevi I won't be able to approve, would you please peek at this and approve?  
See Issue #1516 as it has documented some of the approval tests and validation steps typically included with approving requests.  I articulate them below, but it may contain any additional dialog with the submitting party.
DNS …
=> Update `.cy` per request from nic.cy in Issue 1516

public_suffix_list.dat
=> Add `discordsays.com` and `discordsez.com`

public_suffix_list.dat
=> Add `translated.page`

public_suffix_list.dat
=> Add `kapsi.fi` to PSL

public_suffix_list.dat
This corrects the registration rules links (commented) for .ac, .io and .sh as the BERO has changed (Back End Registry Operator) to address the issue reported in #1527
=> Revises policy links for `.ac` `.io` `.sh` to address issue #1527

public_suffix_list.dat
=> Add `rocky.page`

public_suffix_list.dat
Citing an announcement from the official WapBlog.ID blog, WapBlog will stop providing services on February 23, 2022.
Closing full link:
https://official.wapblog.id/pengumuman-wapblog-id.xhtml
Previous PR:
#1111
=> Remove WapBlog Suffix

public_suffix_list.dat
---
---
====
Organization Website: https://www.kakaocorp.com/page/?lang=ENG&tab=all
We are Kakao who provides all online services such as mobile messenger, search, and blog in Korea.
(https://www.kakaocorp.com/page/service/service)
* Mobile messenger : kakaotalk
https://www.kakaocorp.com/page/service/service/KakaoTalk?lang=ENG&tab=all
* Search engine / News service
https://www.kakaocorp.com/page/service/service/Daum?lang=ENG&tab=all
Among them, this request is for the following blog service:
* Blog : tistory
https://www.kakaocorp.com/page/service/service/Tistory
(https://www.tistory.com/)
Users can use  a subdomain of tistory.com. For example, blog-a.tistory.com, blog-b.tistory.com, etc. can be used. 
Users can also alias their own domains for their blogs. …
=> Add `ktistory.com`

public_suffix_list.dat
=> add `*.build.run`, `*.database.run` and `*.migration.run` to PSL

public_suffix_list.dat
We have decided to not renew the domains couk.me and ukco.me, and instead we are focusing on our .uk domains. I wanted to clean these two .me domains up so they aren't left on the list.
These two domains are currently in the expiration grace period, and we would appreciate their removal from the list.
Many thanks.
=> Remove `couk.me` and `ukco.me` from private section

public_suffix_list.dat
---
---
====
Organization Website: https://staclar.com/
Staclar provides a variety of services to digital music companies, record labels and independent artists.
====
For the same reasons as #1331. This will be hosting sites for third party artists under it, and will be an additional option to users in addition to the already included novecore.site. The main reason for inclusion is cookie security. We confirm we'll maintain the required registration term for this domain.
=======
<TODO>
```
dig TXT _psl.musician.io
_psl.musician.io.       600     IN …
```
=> Add `musician.io` - updates Staclar entry from #1331

public_suffix_list.dat
This pr fixes 6 spelling mistakes in the PSL, allowing for better automatic parsing.
Fixes #1529 
Guidelines
=========
make test
=========
=> Fix spelling errors in PSL

public_suffix_list.dat
---
====
Organization Website: [GDS](https://www.gov.uk/government/organisations/government-digital-service)
The Government Digital Service is department of the Cabinet Office, we are responsible for the management and delegation for many of the core domains used within the UK Government.
Further details: https://www.gov.uk/service-manual/technology/managing-domain-names
The following domain(s), submitted for inclusion on the public suffix list, are within GDS' control:
- campaign.gov.uk
I am Stephen Ford, Tech Lead/Senior Site Reliability Engineer, technical representative of the team which manages these domains within GDS and the Cabinet Office.  Organisational approval for this request has been granted by the GDS Policy …
=> Add: `campaign.gov.uk` (updates #1512)

public_suffix_list.dat
=> Add domains for `encore.dev`

public_suffix_list.dat
=> Add `airkitapps.com`, `airkitapps.eu`, and `airkitapps-au.com` domains

public_suffix_list.dat
=> Add `user.localcert.dev`

public_suffix_list.dat
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))
---
====
Organization Website: <https://www.scaleway.com>
I'm Rémy Léone, I work as an Engineering Manager and cloud developer advocate at Scaleway.
Scaleway is a cloud provider that offers different kinds of managed services for our customers.
Some of those services include DNS functionality: for instance, a DNS record will be added to a load balancer or an instance server.
====
Product | Sub-domains available for customers | Examples
-- | -- | -- 
baremetal | - `fr-par-1.baremetal.scw.cloud` <br/> - `fr-par-2.baremetal.scw.cloud` <br/> - `nl-ams1.baremetal.scw.cloud` <br/> - …
=> add support for scaleway subdomains

public_suffix_list.dat
====
---
For Private section requests that are submitting entries for domains 
that match their organization website's primary domain, please 
understand that this can have impacts that may not match the 
desired outcome and take a long time to rollback, if at all.
To ensure that requested changes are entirely intentional, make sure 
that you read the affectation and propagation expectations, 
that …
=> Add `builder.code.com`, `stg-builder.code.com`, and `dev-builder.code.com`

public_suffix_list.dat
=> Add `lolipopmc.jp`

public_suffix_list.dat
====
IServ GmbH is a German company providing IT solutions for the educational sector. Our main product is also called IServ. IServ, sometimes referred to as IServ school platform, is an all-in-one solution for the pedagogical side of a school's network. It provides basic functionality like e-mail, file sharing, instant messaging, calendars, a collaborative text editor etc., but also software deployment and an Active Directory domain controller as well as more education oriented features such as special examination modes for local computers and an exercise module.
IServ is currently used by over 5,200 schools primarily in German-speaking regions and manages about 350,000 computers and almost 2,900.000 user accounts. …
=> Add `iservschule.de`, `schulplattform.de`, update IServ GmbH contact information

public_suffix_list.dat
**Description of Organization**
===
NIXI is a not for profit Organization under section 8 of the Companies Act 2013, and was registered on 19th June, 2003. NIXI was set up for peering of ISP's among themselves for the purpose of routing the domestic traffic within the country, instead of taking it all the way to US/Abroad, thereby resulting in better quality of service (reduced latency) and reduced bandwidth charges for ISP's by saving on International Bandwidth. NIXI is managed and operated on a Neutral basis, in line with the best practices for such initiatives globally.
Organization Website: https://registry.in/
**Reason for PSL Inclusion**
===
As per info available here - https://registry.in/policies 
Unlimited registrations are available in the following zones.
.in
co.in
net.in …
=> Updates to NIXI `.in` subspace in ICANN section of PSL

public_suffix_list.dat
=> Update to #1217 Add more Framer domains

public_suffix_list.dat
[BeagleBoard.org Foundation](https://beagleboard.org) is a United States 501(c)3 non-profit corporation supporting education in open source embedded systems. We primarily design open hardware single board computers for use in systems needing real-time capabilities, but are also just generally useful when you want to dedicate a computer to a function. By releasing our designs as open hardware, people are free to make variations and ultimately make real-world products out of their ideas. Our community is mostly made of Linux experts seeking to collaborate and educate in improving access and automation all around us.
We've setup a public `gitlab` instance for use by our community at `git.beagleboard.org` and are enabling community members to publish pages on `beagleboard.io` in an attempt to …
=> Add `beagleboard.io`

public_suffix_list.dat
=> Add `streamlitapp.com`

public_suffix_list.dat
====
Amazon Web Services is an infrastructure-as-a-service cloud computing provider.
More information about AWS is availble on our website:
[What is AWS?](https://aws.amazon.com/what-is-aws/)
**Organization Website:**  
[AWS Homepage](https://aws.amazon.com)
====
These features/services have been identified by AWS Security and AWS service
teams as supporting different distinct customers/resources across shared
DNS suffixes. Adding these suffixes to the PSL is expected to improve the
security posture of customers using our services.
**Number of users this request is being made to serve:**  
These changes are expected to impact all customers using these AWS services.
This includes both AWS-internal and external customers. Specific user …
=> AWS Submissions to the Public Suffix List - Month of 2022-07

public_suffix_list.dat
=> Add `2.azurestaticapps.net` DNS suffix

public_suffix_list.dat
---
====
Replit is an online programming environment that allows users to create and host their own websites and applications. I am an engineer at Replit.
In order to make our product safer for children, we are launching a new product called Firewalled Replit. It will behave similarly to Replit, but user's applications will not be able to access arbitrary internet services.
Organization Website: https://replit.com
The new website for Firewalled Replit (which has not launched to external users yet) will be https://firewalledreplit.com
====
Users can use Replit to host their own websites on various subdomains:
- repl.co (already in the PSL)
- id.repl.co (already in the PSL)
- repl.run (already in the …
=> Update existing Replit entries, add `firewalledreplit.co`

public_suffix_list.dat
=> Add Domains from `simplesite.com` et al to one.com subsection

public_suffix_list.dat
====
* [ X ] Description of Organization
* [ X ] Robust Reason for PSL Inclusion
* [ X ] DNS verification via dig
* [ X ] Run Syntax Checker (make test)
* [ N/A ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section
* [ X ] We are listing *any* …
=> Names.of.London is no longer operating the service

public_suffix_list.dat
Overview
====
Previously, #1460 describes a need to organize Amazon domains on the PSL.
In this PR, we've added no new suffixes. However, we've made the following changes to our records on the PSL:
- **CentralNic model**  
We've moved to the so-called "CentralNic model" for large organizations, [with an added trailer](https://github.com/publicsuffix/list/pull/1460#issuecomment-1017955653).
- **References**  
We've added references to sections for our existing services, a practice that we started in #1590. This is an opaque GUID, but is something we use within Amazon to track internal requests for PSL entries.
- **Service Naming**
Services have been corrected to use the name described on their product page. This name either begins with `AWS`, `Amazon`, or just the service name. For …
=> Use CentralNic model for Amazon suffixes

public_suffix_list.dat
The `myravendb.com` domain is no longer used by us and should probably be removed from this list.
I'm the person who original asked to add this domain.
Previous PR that added that is: https://github.com/publicsuffix/list/pull/535
```
$ dig myravendb.com
; <<>> DiG 9.16.1-Ubuntu <<>> myravendb.com
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 9421
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
```
=> Removing myravendb.com domain that expired and is not used

public_suffix_list.dat
I am not the original submitter, however it appears that the domain gwiddle.co.uk is now held by a malicious actor. Accordingly, I think it's better to remove this entry than for it to remain. [The Gwiddle Foundation has been removed from the UK's charity register](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5099459/charity-overview) and no longer exists.
The tests are passing:
```
[...] …
```
=> Remove `gwiddle.co.uk`

public_suffix_list.dat
=> Add `myamaze.net`

public_suffix_list.dat
**Note**
This request is similar to our previous PR, with 2 new additional domains - mytabit.co.il and mytabit.com (that intend to replace original tabitorder.co.il sub-domains system of ours in the future): https://github.com/publicsuffix/list/pull/1385
====
Organization Website: https://tabit.cloud/
Tabit is a restaurant ordering system as well as a point-of-sale that streamlines restaurant operations and extends sales opportunities.
Our 360 degree integrated ecosystem connects every aspect of the customer experience: from guest management, customer ordering and kitchen productivity to tableside payment, bringing efficiencies to every interaction point.
====
This is a pull request in response to the Apple iOS 14.5 change that affected …
=> Update #1385: add `mytabit.co.il` & `mytabit.com` for IOS PCM / FB solution

public_suffix_list.dat
=> Add `cf-ipfs.com`, `cloudflare-ipfs.com`, and `r2.dev`

.github/workflows/deploy-site.yml
This PR adds a GitHub Action that uses the workflow from `publicsuffix/publicsuffix.org` and deploys the list and website if commits are pushed to `master` or if triggered manually.
Signed-off-by: Robert Müller <rmuller@mozilla.com>
=> Add GitHub Action to deploy site on list update

public_suffix_list.dat
---
---
====
Autocode is an API development, management, and hosting platform. We host projects for hundreds of thousands of developers, and have an online IDE that enables anyone to deploy live code in seconds without setup. We specialize in connecting ecosystems such as Discord, Stripe, and Airtable. Common use-cases include Discord bots, Slack alerts, webhooks, and, importantly for this request, static websites.
My name is Jacob Lee, and I'm the co-founder and CTO of Autocode.
Organization Website: https://autocode.com
====
We currently host user code under the domain `api.stdlib.com` (which we previously added to the PSL under the name "Standard Library"). We rebranded the company to Autocode, …
=> Add `autocode.dev`

public_suffix_list.dat
Adds domain names for Adobe Developer Platform
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-o …
=> Add Adobe Developer Platform domains `adobeio-static.net` and `adobeioruntime.net`

public_suffix_list.dat
=> add `canva-apps.com` and `canva-apps.cn`

public_suffix_list.dat
=> Add Snowflake Inc domains to PRIVATE section

public_suffix_list.dat
=> Add `it.com`

public_suffix_list.dat
Note that this is a subset of https://github.com/publicsuffix/list/pull/1640# which includes just second-level domains
such as "akamaized.net" but excludes the third-level domains such as ".com.akamaized.net".  We'd prefer that 
the full list be included but are opening this up to expedite getting a subset included.
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this …
=> Add subset of Akamai domains to the PSL

public_suffix_list.dat
=> Additional ngrok domains - more `ngrok.io` from #48 + `ngrok.app` `ngrok-free.app` `ngrok.dev` `ngrok-free.dev` `ngrok.pizza`

public_suffix_list.dat
added new public domain: kropyvnytskyi.ua
see https://www.hostmaster.ua/2ld/ for current list
Submitted on behalf of Hostmastter.UA - .UA ccTLD manager
New public domain would be operating 2023.05.01
see https://www.hostmaster.ua/2ld/ for current UA public domain list 
kropyvnytskyi.ua is delegated already:
% dig +short soa kropyvnytskyi.ua.
ns.host.kr.ua. hostmaster.host.kr.ua. 2022122004 86400 14400 2592000 345600
* [X ] This request was _not_ submitted with the objective of working around other third-party limits
=> Add `kropyvnytskyi.ua` for .ua ccTLD in ICANN Section

.github/workflows/test.yml, .github/workflows/tld-update.yml, tools/newgtlds.go, tools/newgtlds_test.go
This is an alternative to https://github.com/publicsuffix/list/pull/1809
More cleanup is probably in order (in particular, making a proper Go module for this tool) but for now let's do the simple stuff.
ICANN is updating the contract date field in the `gtlds.json` file for many contracts in the near future. Since including the contract date in the `.dat` file as comments isn't very helpful to anyone, and leaving it in during this renewal period would result in a large quantity of auto-pull requests for no-op changes, we choose to omit the date as a quick fix.
This commit updates the `newtlds.go` tool to no longer process/render the `DateOfContractSignature`. Unit tests are updated to reflect this change.
Previously the Go unit tests for the `newgtlds` tool were run as part of the Travis …
=> tools: skip contract date rendering, small CI fixups.

.github/workflows/test.yml
This branch updates the `test.yml` GitHub workflow's triggers to include `pull_request` in addition to `push`. This will ensure that when a pull request is opened the CI tasks are run and check statuses added to the PR. 
I overlooked this in my earlier CI cleanup PR and noticed this wasn't happening when I opened https://github.com/publicsuffix/list/pull/1817.
Without an update to the repository settings to enable branch protection rules (_recommended_) these will not be _blocking_ checks.
=> ci: update test workflow triggers to include PRs.

tools/newgtlds.go, tools/newgtlds_test.go
This branch updates the `tools/newgtlds.go` tooling to include a comment line with the gTLD's IANA registry URL for each gTLD.
E.g. for the tld `aaa`, includes a comment line: `// https://www.iana.org/domains/root/db/aaa.html`.
Follow-up to #1812
=> tools: include IANA TLD URL in new gtld updates.

.github/workflows/tld-update.yml
Stripping out the project/card definition stuff - appears to use a different context of "project" than intended
This rolls back the cause of the https://github.com/publicsuffix/list/pull/1815#issuecomment-1667496019 and fixes the daily ICANN automation
=> Automation - Roll back broken 'project' assignment in autopull 

.github/workflows/deploy-site.yml, .github/workflows/tld-update.yml
=> Set up permissions to github workflow to least privileges

public_suffix_list.dat
=> Add `wix.run`

public_suffix_list.dat
=> Remove k12.de.us

public_suffix_list.dat
====
- The AFNIC no longer manages the SLD list, now mostly handled by Smallregistry
- The French National Board of Surveyors (Ordre des Géometres-Experts) asks for their domain geometres-experts.fr to be removed (contact: <ordre@geometre-expert.fr> )
* [] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section
* [] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
---
For Private section requests …
=> Update .fr list, move some subspaces to PRIVATE section listing of smallregistry.net

public_suffix_list.dat
=> Add <4-8>.azurestaticapps.net DNS suffix

public_suffix_list.dat
=> Add `torun.pl`

public_suffix_list.dat
The company legal structure has changed from a general partnership (OG) to a limited liability company (GmbH). Please refer to: https://www.futureweb.at/de/impressum/ for more details.
=> Update Company Name (new Legal Structure)

public_suffix_list.dat, tools/newgtlds.go, tools/newgtlds_test.go
Solution for #1174. Replaces #1754
====
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and …
=>  Handle EBEROs: Use DelegationDate alongside ContractTerminated

.github/workflows/test.yml, .github/workflows/tld-update.yml
Mistake introduced in #1901
Fixes https://github.com/publicsuffix/list/actions/runs/7006982080/job/19060050437
=> Change the order of flags in github actions workflows.

public_suffix_list.dat
=> Remove homeoffice.gov.uk

public_suffix_list.dat
=> Add atmeta.com to PSL and consolidate Meta entries

public_suffix_list.dat
=> Update Adobe entries with aem.live and aem.page for former Project Helix

public_suffix_list.dat
=> Add pages.gay

public_suffix_list.dat
I would like to remove my domain `blog.kg` from PSL (related: #1753).
====
---
To ensure that requested changes are entirely intentional, make sure …
=> Removal of `blog.kg` from private section

public_suffix_list.dat
=> Azure updates for Microsoft Corporate Domains

public_suffix_list.dat
=> Add panel.dev

public_suffix_list.dat
=> Brave Submissions to the Public Suffix List - Q4 2023

public_suffix_list.dat
Added a2hosted.com and cpserver.com to public_suffer_list.dat on behalf of A2Hosting
====
---
To ensure that requested changes are entirely …
=> Add a2hosted.com and cpserver.com suffix to private section

public_suffix_list.dat
====
---
====
Organization Website: [https://www.scaleway.com/](https://www.scaleway.com/)
I'm Benjamin Lazarecki, I work as an Engineer at Scaleway.
Scaleway is a cloud provider that offers different kinds of managed services for our customers.
Some of those services include DNS functionality: for instance, a DNS record will be added to a load balancer, an instance server, a grafana instance.
====
We are releasing a new product, that allow client to have observability on their metrics and logs. 
Sub-domains available for customers
- cockpit.fr-par.scw.cloud
- cockpit.nl-ams.scw.cloud
- cockpit.pl-waw.scw.cloud
Example:
- …
=> Update public_suffix_list.dat for scw.cloud cockpit product subdomains

public_suffix_list.dat
=> Add cprapid.com suffix to private section

public_suffix_list.dat
> Also, the template had 10 tasks. Please put them all back and complete them.
* [x ] Description of Organization
Organization Website: https://radwebhosting.com
My name is Scott Claeys, I am a network engineer, and I represent Rad Web Hosting.
Rad Web Hosting provides web hosting and servers to users around the globe.
* [ x] Robust Reason for PSL Inclusion
Rad Web Hosting offers clients the ability to reserve unclaimed subdomains of *.myradweb.net for the purpose of staging incoming site migrations, viewing site updates in the wild, or for creation of webspaces to host websites and applications without registering a paid domain name.
We need to isolate them from one another (eg: we don't want client1.myradweb.net to be able to set a cookie readable from client2.myradweb.net).
Same …
=> Update Rad Web Hosting Domains section - add myradweb.net, servername.us

public_suffix_list.dat
=> Add `webflow.io` and `webflowtest.io`

public_suffix_list.dat
====
Organization Website: https://www.tailscale.com
Tailscale is software that creates a private overlay mesh network between users' devices, secured by the WireGuard VPN protocol.
Among other features, Tailscale gives users a subdomain within a shared DNS namespace. This is primarily to enable obtaining TLS certificates from Let's Encrypt, to appease browser insistence on TLS connections even over our VPN (understandably since the browser doesn't know or care about the security properties of the IP transport).
I'm an engineer at Tailscale, and am making this submission on behalf of my employer. "We" throughout this PR refers to Tailscale as a whole, with me affirming things on the company's behalf.
Reason for PSL …
=> Add `*.c.ts.net.`

public_suffix_list.dat
=> Add `f5.si`

public_suffix_list.dat
=> Add `ewp.live` (EasyWP)

public_suffix_list.dat
=> Add STACKIT subdomains (`runs.onstackit.cloud`, `stackit.gg`, `stackit.rocks`, `stackit.run`, `stackit.zone`)

public_suffix_list.dat
=> additional ngrok domain - add `ngrok.pro`

public_suffix_list.dat
=> Add on.crisp.email (Crisp IM SAS)

public_suffix_list.dat
=> add `*.my.canvasite.cn` and `*.my.canva.site`

public_suffix_list.dat
Added cdn77-storage.com for our object storage service and rsc.contentproxy9.cz used by some of our CDN customers.
====
---
To ensure that requested …
=> Add cdn77-storage.com and rsc.contentproxy9.cz

public_suffix_list.dat
=> ADD: `can.re`

public_suffix_list.dat
=> add getlocalcert.net domains

public_suffix_list.dat
=> Add `nimsite.uk`

public_suffix_list.dat
=> Add `preview.csb.app` and `csb.app`

public_suffix_list.dat
---
---
====
Organization Website: https://darklang.com/
Darklang is a holistic programming language and infrastructure, for building backend web services. We are the company building Darklang. 
I'm a co-founder and CTO of Darklang.
====
We have an [existing domain on the PSL](https://github.com/publicsuffix/list/pull/857), and intend to migrate usage of that domain to a new domain for marketing/product reasons (aka it looks nicer).
Number of users this request is being made to serve: ~1000
- We provide each customer with a unique …
=> Add darklang.io

public_suffix_list.dat
=> add `scrypted.io`

public_suffix_list.dat
=> Remove unused suffix (123sait.ru)

public_suffix_list.dat
=> Add `heliohost.us`, `helioho.st`

public_suffix_list.dat
---
For Private section requests:
---
====
My name is Tomas Maggio and I am the managing director at [Libre](https://libre.nz/). We are a private and commercial company that hosts customer application servers close to users.
Organization Website: https://libre.nz/ 
The domain in question will be used
with the https://runcontainers.nz/ product.
====
User generated content will be allowed on the the subdomains of `runcontainers.dev`. This domain will be used by our users to host pretty much anything that can execute on x86, so we want to ensure isolation and do all we can to protect them.
Number of users this request is being made to serve: 
Based on our installed capacity right now, estimated ~3000 …
=> Add `runcontainers.dev` domain

public_suffix_list.dat
=> Add grayjayleagues.com

public_suffix_list.dat
=> Add `unison-services.cloud`

public_suffix_list.dat
=> Add StackBlitz

public_suffix_list.dat
=> chore: add `is-a.dev`

public_suffix_list.dat
=> Add `framer.ai`

public_suffix_list.dat
Hi,
after [PR#77](https://github.com/publicsuffix/list/pull/77) we are planning to extend feature set of the DynDNS Service provided for our customers, and thus need an additional domain registered on PSL.
Best regards
Andreas
====
---
PR Rollbacks have lower …
=> PSL: Adding myfritz.link (follow up PR#77)

public_suffix_list.dat
The domain `ravendb.me` was added in (https://github.com/publicsuffix/list/pull/535), it is now expired and should be removed from the list.
```
$ dig TXT _psl.ravendb.com
; <<>> DiG 9.16.1-Ubuntu <<>> TXT _psl.ravendb.com
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50542
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;_psl.ravendb.com.              IN      TXT
;; AUTHORITY SECTION:
ravendb.com.            900     IN      SOA     ns49.domaincontrol.com. dns.jomax.net. 2023060703 28800 7200 604800 3600
;; Query time: 110 msec
;; SERVER: 172.28.144.1#53(172.28.144.1)
;; WHEN: Sun Sep 03 15:09:53 IDT 2023
;; MSG SIZE  rcvd: 113
```
=> Removing ravendb.me - unused & expired domain

public_suffix_list.dat
====
cloudscale.ch AG is a Swiss based cloud hosting (IaaS) provider. We offer cloud VMs, an S3-compatible Object Storage and other related services to customers.
Organization Website: https://www.cloudscale.ch/
I'm a System Engineering team lead at cloudscale.ch. 
====
cust.cloudscale.ch
----
DNS records in this domain are provided as a convenience to our customers for each virtual machine.
I have read the guidelines, and did want to note that we plan to have the format of 1-2-3-4.cust.cloudscale.ch for a virtual machine with an IP address of 1.2.3.4. I understand the guideline prohibiting this as a type of wildcard domain, but I would like to assure the reviewer that we will only be serving these …
=> Add `cloudscale.ch` domains

public_suffix_list.dat
=> Add `rt.ht`

public_suffix_list.dat
Given this is a removal, I don't think the PR template applies. Please let me know if I can clarify anything. I've commented on the removal in the PRs where the records were initially added.
=> Drop old pcarrier.ca Software Inc. domains

public_suffix_list.dat
add a new domain for our public dynamic dns service
====
--- …
=> add qnap entries to existing section (`myqnapcloud.cn` , `mycloudnas.com`, `mynascloud.com`)

public_suffix_list.dat
_AWS does not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling._
_Please see the Reason section below for objectives in this pull request._
To …
=> AWS Submissions to the Public Suffix List - Q1 2024

public_suffix_list.dat
=> Remove `ghost.io`

public_suffix_list.dat
=> add `xmit.dev`

public_suffix_list.dat
The `app.lmpm.com` domain was added in 2018, but our inclusion in the list is now causing cookie issues with AWS.
In hindsight, this domain should never have been included. Our `app.lmpm.com` domain hosts a multi-tenant app, where each tenant accesses their instance via a subdomain (e.g. `tenant1.app.lmpm.com`).
====
---
For Private section requests that are submitting entries for domains that match …
=> Remove Lightmaker Property Manager, Inc. section and domain  `app.lmpm.com`

public_suffix_list.dat
=> Add "zeabur.app"

public_suffix_list.dat
=> Add `box.ca` (Whatbox)

public_suffix_list.dat
=> Add notion.site as private eTLD

public_suffix_list.dat
- https://www.microsoft.com/en-us/edge/features/microsoft-defender-smartscreen?form=MA13FJ
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/lis …
=> Add Clever Cloud's domains for customers

.github/workflows/check_pr.yml, tools/pr_checker/check_dns.py, tools/pr_checker/requirements.txt, tools/pr_checker/test_psl_01.dat, tools/pr_checker/test_psl_02.dat
Let's have more automatic checks!
=> Add Github workflow to check _psl DNS entries on PRs

public_suffix_list.dat
=> Add `wixstudio.com`

public_suffix_list.dat
Main motivation is web browser cookie hijack preventation.
Documentation: https://developers.cloudflare.com/dns/zone-setups/partial-setup/setup/
Cloudflare reference: DNS-10787
Signed-off-by: Sami Kerola <kerolasa@cloudflare.com>
=> Add Cloudflare CNAME setup domains

public_suffix_list.dat
=> Add heiyu.space

public_suffix_list.dat
Public Suffix List (PSL) Pull Request (PR) 
====
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand …
=> Add relay.evervault.app and relay.evervault.dev

public_suffix_list.dat
=> Add Strapi domains

public_suffix_list.dat
=> Add `madethis.site`

public_suffix_list.dat
It's in the same situation as `com.by`: not officially reserved according to available documentation, but third-level domain registrations are available as if it were. Logically it belongs in the same block as `com.by`.
Found while developing #1987, because it resulted in surprising output. simon-friedberger recommended making this .dat change, rather than add a custom lint exemption that's only necessary for this one entry.
This is a minor lint cleanup, so most of the PR template does not apply. Applicable items:
- **Description of change**: above.
- **make test**: runs successfully, no errors.
- **Authority**: I'm not authoritative for `by` or `of.by`. However I am not adding/removing any suffixes, only adjusting whitespace.
- **Justification**: I studied the `by` [registry …
=> Reattach of.by to the Belarus ccTLD block

public_suffix_list.dat
=> Add `as.sh.cn`

public_suffix_list.dat
All other comments in the file begin with '// ', this just makes the data more regular for parsing.
In particular I wanted to add a lint for this the Go parser/linter, and this is the only current violation of that convention in the PSL file. It seems easier to adjust the canonical file than to burn this one exception to the rule into code.
This is a whitespace-only change that does not alter any suffixes, so a lot of the PSL checklist is N/A. Relevant items:
- I'm not the owner of the block being edited, but I'm also not changing suffixes or contact info.
- I ran `make test`, it reports no failures.
- I ran `cd tools && go run ./govalidate ../public_suffix_list.dat` and verified that there are no parse/lint errors there either.
=> Add missing spaces after '//' on prequalifyme.today block

public_suffix_list.dat
The PSL file format encourages ascii characters where possible to make parsing easier. This is one comment block with metadata (contact info etc.) that does not use an ascii colon, making parsing more difficult.
Like #2000, this only changes characters in a comment, and doesn't add/edit/delete suffixes. Relevant checklist items:
- I'm not authoritative for this domain, and not changing suffixes or contact info.
- I ran `make test`, no errors.
- I ran `cd tools && go run ./govalidate ../public_suffix_list.dat`, also reports no issues.
=> Replace unicode fullwidth colon with a regular ascii colon.

tools/internal/parser/errors.go, tools/internal/parser/exceptions.go, tools/internal/parser/file.go, tools/internal/parser/parser.go, tools/internal/parser/parser_test.go, tools/internal/parser/text.go, tools/internal/parser/text_test.go
This splits up the parser logic: a lower level helper breaks up the input bytes in useful ways and tracks source information for error reports. The main parser uses the helper, so that it can focus on the "business logic" of checking the format and linting, without being polluted with tracking offsets and partial state and stuff.
The PR is in 2 commits, each one is ~50% of the change: the first adds the new helper without using it, in `text.go` and `text_test.go`. The second commit updates `parser.go` to use the helper.
The helper has a bunch more unit tests, but the parser functionality is unchanged, and all pre-existing tests pass without modification. Later PRs (see [todo](https://gist.github.com/danderson/f2d5a7a7e0400ea2a7c9dff18058615c#file-psl-todo-md)) will add missing features, …
=> tools/internal/parser: refactor to separate text processing from parser main logic

public_suffix_list.dat
====
- <UPDATE THIS LIST WITH YOUR LIMITATIONS!>
--- …
=> Add netfy.app

public_suffix_list.dat
=> Add `wpsquared.site` and `wp2.host` to private section

public_suffix_list.dat
====
We're not seeking to work around browser limits. Instead, we're seeking to have our entries treated as domain suffixes to maximize the fidelity of Salesforce's internal development environment with its production systems while making use of crm.dev instead of the actual production domains.
---
For Private section requests that are submitting entries for domains that match their organization …
=> Salesforce crm dev

public_suffix_list.dat
=> Add `obl.ong`

tools/go.mod, tools/go.sum, tools/govalidate/govalidate.go, tools/internal/parser/errors.go, tools/internal/parser/parser.go, tools/internal/parser/parser_test.go, tools/internal/parser/text.go, tools/internal/parser/text_test.go
The PSL's canonical is valid UTF-8 with no BOM. However, to try and report useful lint errors, the parser tries to detect and normalize all forms of UTF-16, as well as UTF-8 with BOM. Anything other than the specified canonical encoding is reported in validation errors.
---
The upcoming PR that implements validation of block ordering needs to compare block names, which requires comparing with a Unicode collation. Collation is already confusing enough by itself, without also feeding it invalid UTF-8 :). So, this is a best-effort attempt to normalize non-compliant inputs into clean UTF-8, so that we report those errors early and the rest of the parser can assume strings don't contain garbage, at least at the encoding level.
=> tool/internal/parser: sanitize input to clean, valid UTF-8

public_suffix_list.dat
Conventionally, contact info in the PSL is in RFC 5322 email address format, aka "Name of Person <email@example.com>". Many entries omit the chevrons around the email, so parsers need to be robust to that. But Tor is the only one that is halfway between the two, so it makes sense to fix it.
=> Add closing chevron to contact email address.

public_suffix_list.dat
URL schemes are mandatory for HTTP/S in the RFC, although some parsers interpret a scheme-less URL as a relative path with no scheme or host. There are 2 such URLs in the PSL, which require workarounds when parsing owner metadata for suffixes.
=> Add missing URL schemes to URLs

public_suffix_list.dat
=> Add Raidboxes GmbH to the list

tools/internal/parser/exceptions.go, tools/internal/parser/parser.go
PSL changes e18a520, fb91de8 and 45d3d06 fixed the blocks that required these workarounds.
=> tools/internal/parser: remove workarounds for fixed PSL blocks

tools/internal/parser/errors.go, tools/internal/parser/parser.go, tools/internal/parser/parser_test.go
Small extra validation that I remembered while I was implementing the big text/utf-8 bits that have now been merged.
Note this PR does not pass the tests in tools/internal/parser as-is, because it trips over the expired exemptions that get fixed in #2010. This doesn't break PSL CI right now since tools/internal/parser isn't run there, but I recommend merging #2010 first and then this. The two changes are touching different parts of the codebase, so they should rebase cleanly in either direction.
=> tools/internal/parser: detect and report section markers within suffix blocks

public_suffix_list.dat
The domain got repurposed and should not be listed in the PSL anymore. The `_psl` DNS record was deleted.
Initially, it has been added in https://github.com/publicsuffix/list/pull/696.
=> Remove instantcloud.cn

public_suffix_list.dat
cPanel, Plesk are part of the same WebPros family
merge all domains together as a single organization entry.
Also note that this change is dropping on purpose the wildcard for cprapid as this is not needed and we want to be able to store cookies on x.cprapid.com sub domain.
view comment from https://github.com/publicsuffix/list/pull/1957#issuecomment-2182709465 
make test output 
```
Testsuite summary for libpsl 0.21.5
Making check in tests
CC       test-is-public.o
CC …
```
=> Merge WebPros domains in the same section

public_suffix_list.dat
Rakuten Games, Inc. was dissolved in early 2024. And related services are already closed. Due to the organization's domains can be now obtained by any other party (which can be potentially malicious). I want to request the deletion from PSL.
FYI The record was added in https://github.com/publicsuffix/list/pull/994
=> Delete Rakuten Games, Inc related entries

public_suffix_list.dat
This is the only TLD that isn't in the form "<tld> : <url>". It's preferable to make it match the others rather than force metadata parsers to work around it.
=> aero: remove extra word between TLD name and URL

public_suffix_list.dat
====
_AWS does not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling._
_Please see the Reason section below for objectives in this pull request._
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the …
=> AWS Submissions to the Public Suffix List - Q2 2024

tools/govalidate/govalidate.go, tools/internal/parser/file.go, tools/internal/parser/metadata.go, tools/internal/parser/metadata_test.go, tools/internal/parser/parser.go, tools/internal/parser/parser_test.go, tools/internal/parser/validate.go, tools/internal/parser/validate_test.go
Several commits, each one is self-contained.
I promise the formatting is coming soon, this rework is making the metadata extraction more precise, so that we can look at options for reformatting the suffix block headers into some canonical form.
I added some tests specifically for metadata parsing, to cover the layouts that exist in the PSL. I also removed a couple of parser tests that were just exercising metadata parsing, and were testing behavior for formats that aren't actually present in the real PSL :facepalm: 
Next PR after this one is `pslfmt` with sorting of suffixes and suffix blocks, and possibly metadata reformatting if we find a format that we like.
=> tools/internal/parser: rework metadata extraction for more accurate reformatting

public_suffix_list.dat
====
- <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please …
=> Remove domain no longer under Supabase control.

public_suffix_list.dat
====
- Rate-limiting on top-level domain for our user-specific subdomains
---
To ensure that requested changes are entirely intentional, make sure …
=> Add `p.tawk.email` and `p.tawkto.email` domains

tools/private_domains_checker/.gitignore, tools/private_domains_checker/PSLPrivateDomainsProcessor.py, tools/private_domains_checker/README.md, tools/private_domains_checker/TestPSLPrivateDomainsProcessor.py, tools/private_domains_checker/requirements.txt
This PR is related to #1996. It introduces the `tools/private_domains_checker`, a Python script created to fetch data from the PSL and check the domain status and expiry dates of the private section domains. It performs WHOIS checks on these domains and saves the results into CSV files for manual review. 
Please feel free to make any edits! 
The [README file](https://github.com/groundcat/PSL-private-domains-checker/blob/main/README.md) has been updated to reflect the usage instructions.
Example CSV outputs from real PSL data:
- [Example datasets](https://github.com/groundcat/PSL-private-domains-checker/tree/main/data)
=> PSL Private Section Domains WHOIS Checker

public_suffix_list.dat
This domain has been put up for sale and is not PSL worthy, see #2042 for more information.
=> remove `c.la`

public_suffix_list.dat
See [comments](https://github.com/publicsuffix/list/pull/713#issuecomment-2244269098) from the original requester @renqiz in #713 
The regional domains listed below had expired and were registered by different parties.
| Domain           | Creation Date          | Registrar Name   | Nameservers                             |
|------------------|------------------------|--------------------------|----------------------------------------|
| filegear-au.me   | 2021-01-27T18:08:42Z   | Key-Systems GmbH         | ns-cloud-e1.googledomains.com, ns-cloud-e2.googledomains.com, ns-cloud-e3.googledomains.com, ns-cloud-e4.googledomains.com |
| filegear-de.me   | 2022-06-08T22:13:07Z   | Danesco Trading Ltd.     | ns1.gm238.parklogic.com, ns2.gm238.parklogic.com |
| filegear-gb.me   | …
=> Remove filegear regional domains

public_suffix_list.dat
Please refer to recent comments from #1060.
The domains `impertrix.com` and `impertrixcdn.com` likely expired after the project was terminated. The organization website, https://cloud.impertrix.com/, no longer works.
| Domain           | Creation Date       |
|------------------|---------------------|
| impertrix.com    | 2022-07-28T19:26:07Z|
| impertrixcdn.com | 2024-03-28T17:16:20Z|
The current WHOIS data shows both domains were registered after the original PR was submitted and merged.
The domain `impertrixcdn.com` appears to be currently involved in malicious activities, according to VirusTotal [results](https://www.virustotal.com/gui/domain/impertrixcdn.com/community) and also included in [a community report](https://www.virustotal.com/graph/gbf8d6f71f64541d29cc407179aad1fc6670ebf5f5 …
=> Remove `impertrix.com` and `impertrixcdn.com`

public_suffix_list.dat
Please refer to recent comments in #1401 
- The domain `onflashdrive.app` expired and was recently registered by a different party on 2024-03-08.
- The original requester @qoddiapps has [confirmed](https://github.com/publicsuffix/list/pull/1401#issuecomment-2198277238) the domain is no longer in use but made changes incorrectly in their own repository [in this commit](https://github.com/qoddiapps/list/commit/47f12084949314b633ab904c188de4650d4be3ea) instead of creating a PR here.
- The domain was [taken over](https://github.com/publicsuffix/list/pull/1401#issuecomment-2193894223) by a different party and is [flagged as malicious by multiple antivirus engines](https://www.virustotal.com/gui/domain/onflashdrive.app). 
- It is currently on `clientHold` by the registrar.
```md
Domain Name: …
```
=> Remove `onflashdrive.app`

public_suffix_list.dat
Domain is up for sale, which is against the PSL terms of service:
Nameservers of `nid.io` point to Afternic:
---
I am just trying to clean up some entries on the PSL that are invalid with some spare time I have as I really appreciate this project. Would you guys prefer me make one big PR with changes like these (with evidence for removal of each domain, of course) instead of individual PRs for each domain/section? Thanks :)
=> remove `nid.io`

public_suffix_list.dat
This domain is setup to point to a parking page, which I believe is against the ToS:
It was originally added to the PSL in #404 however it seems the domain name registration lapsed and someone else took the domain name as the registration date via a WHOIS lookup shows `Registered on 15th November 2023 at 14:29:51.068`:
The `_psl.cya.gg` TXT record no longer exists either, so that is also reason to believe the domain name has changed registrants.
=> remove `cya.gg`

public_suffix_list.dat
See [latest comments](https://github.com/publicsuffix/list/pull/993#issuecomment-2195028494) from the original requester @benaubin in #993
=> Remove `mintere.site` to rollback #993 (expired domain)

public_suffix_list.dat
This domain returns a for sale page, which is against the PSL's terms of service.
=> remove `pcloud.host`

public_suffix_list.dat
Remove backplaneapp.io to rollback #267 (expired domain)
Creating this PR to remove `backplaneapp.io` for a combination of the following reasons:
- WHOIS shows the domain had expired and was likely registered by a different party, assuming if it's not @voutasaurus the original requester's organization re-registering the same domain after it expired.
```
Domain Name: backplaneapp.io
Registry Domain ID: c7543042354d4534827c58dc5a6cb454-DONUTS
Registrar WHOIS Server: whois.dynadot.com
Registrar URL: http://dynadot.com/
Updated Date: 2024-07-04T00:47:24Z
Creation Date: 2019-08-09T12:55:37Z
Registry Expiry Date: 2024-08-09T12:55:37Z
```
- The _psl TXT record no longer exists, likely meaning the current registrant has no intention of PSL inclusion anymore.
- The organization website …
=> Remove `backplaneapp.io` to rollback #267 (expired domain)

public_suffix_list.dat
Remove both shiftcrypto.dev and shiftcrypto.io domains from PSL. Respective `_psl` records have been removed. 
The domains were initially added to the list via #1236 and at the time the assumption was that some subdomains might be used by third parties. This was never the case and all subdomain were exclusively operated by Shift Crypto and never granted to 3rd parties. Main workloads were also moved to bitbox.swiss which is the rebranding of shiftcrypto. 
Requesting the PR from the original repository pertaining to #1236 . If additional validation is needed, please let me know.
=> Remove `shiftcrypto.dev` and `shiftcrypto.io` 

public_suffix_list.dat
Creating this PR to remove `mozilla-iot.org` because Mozilla has retired its IoT products. 
- [An Important Update on Mozilla WebThings](https://discourse.mozilla.org/t/an-important-update-on-mozilla-webthings/67764)
The project has been renamed from “Mozilla WebThings” to “WebThings” and has moved to a new home at `webthings.io` that is operated by a different entity, no longer under Mozilla.
Mozilla let the domain expire :( , and in November 2023, I noticed this and registered `mozilla-iot.org` on 2023-11-20 to prevent potential exploitations. This was to avoid someone else taking it over and potentially intercepting traffic from customers using the old Mozilla IoT devices. I then reported this to Mozilla and transferred the domain to them. 
This process was documented in [Bugzilla …
=> Remove `mozilla-iot.org`

public_suffix_list.dat
Creating this PR to remove `pagefrontapp.com` for a combination of the following reasons:
- WHOIS shows the domain had expired, was likely registered by a different party, and then expired again for an extended period.
- The _psl TXT record no longer exists (NXDOMAIN).
- The organization website https://www.pagefronthq.com/ is defunct.
- No subdomains have been discovered at `pagefrontapp.com`.
- A [Google search](https://www.google.com/search?q=site%3Apagefrontapp.com&ie=UTF-8) indicates no active site in use.
```
Domain Name: PAGEFRONTAPP.COM
Registry Domain ID: 2779174757_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.web.com
Registrar URL: http://www.networksolutions.com/
Updated Date: 2024-07-22T11:03:17Z
Creation Date: 2023-05-08T18:11:17Z
Registry Expiry Date: 2024-05-08T18:11:17Z …
```
=> Remove `pagefrontapp.com` (expired domain)

public_suffix_list.dat
- graphox.us returns a default web server page:
- Main website https://lab.aaronleem.co.za times out
- `_psl.graphox.us` TXT record is missing
- After looking at the WHOIS records, the graphox.us domain name was registered on 2022-04-15 however the original PR was made 2020-02-10, so I believe the domain most likely lapsed and was picked up by someone else.
Original PR was #960 opened by @gear4s.
=> remove `graphox.us`

public_suffix_list.dat
Introduced in 56cd84e -- the domain is no longer a public suffix.
`_psl` records do not exist.
=> remove cloudcontrol.com

public_suffix_list.dat
Simply updating the contact email for is-a.dev as we have moved to m.is-a.dev for email addresses. I am the original submitter of PR #1949.
=> update contact email for `is-a.dev`

public_suffix_list.dat
Creating this PR to remove `awsmppl.com` (rollback #900) for the following reasons:
- **Expired domain**: WHOIS shows it was likely registered by someone else after it expired, assuming it wasn't re-registered by the original requester's organization (pending for @AgentTNT in #900 to confirm).
Per whois `Creation Date: 2022-12-28T19:04:02Z` is later than the date of inclusion: `sleevi merged commit 4e84d8b into publicsuffix:master on Dec 5, 2019`
- **`ClientHold` for an extended period**: The registrar has placed the domain on ClientHold for a long time, definitely over three months based on my checker's history.
Please read the original WHOIS records below:
```
Domain Name: AWSMPPL.COM
Registry Domain ID: 2747658378_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.web.com
Registrar URL: …
```
=> Remove `awsmppl.com` to rollback #900 (expired domain, malicious)

public_suffix_list.dat
This removes static.land as requested in https://github.com/publicsuffix/list/pull/255#issuecomment-2246388641
@groundcat
=> remove static.land from public_suffix_list.dat

public_suffix_list.dat
- Domain is sitting at a parking page
- `_psl.bitbridge.net` TXT record does not exist
Original PR was #1000 opened by @bitsii.
=> remove `bitbridge.net`

public_suffix_list.dat
- t3l3p0rt.net root does not resolve
- `_psl.t3l3p0rt.net` TXT record does not exist
- tele.amune.org root does not resolve
- `_psl.tele.amune.org` TXT record does not exist
- I also checked `_psl.amune.org` in case they had put a TXT record there, however they have not.
Original PR was #357 opened by @mindprotectionkit-admin. That was back in 2016, so chances are they have just shutdown their service and done a "set and forget" type entry on the PSL.
=> remove Amune section

tools/internal/domain/domain.go, tools/internal/parser/clean.go, tools/internal/parser/clean_test.go, tools/internal/parser/errors.go, tools/internal/parser/parser_test.go, tools/internal/parser/validate.go, tools/internal/parser/validate_test.go, tools/internal/parser/write.go
Enforce that the expected sections are present (and only those sections), and report duplicate suffixes. Duplicates that can be safely fixed are just fixed automatically in `fmt`, others (like when the duples are in different blocks - who owns it?) are reported as validation errors.
The existing metadata validator also respects diffs now, instead of reporting errors for the entire PSL.
=> tools/internal/parser: add more offline, diff-aware validations

tools/go.mod, tools/go.sum, tools/internal/github/pr.go, tools/psltool/psltool.go
Sorry for the radio silence, I returned to work and as predicted available time went down :(
With this change `psltool check-pr 1234` does a differential validation of the PR, diffing against the target branch to report new issues.
Example output, running against currently open PR 2084:
```
> GITHUB_TOKEN=$(gh auth token) go run ./psltool check-pr 2084
Checked the following changed suffix blocks:
"libp2p project" (lines 14117-14119)
file needs reformatting, run 'psltool fmt' to fix
Error: file has 1 error
exit status 1
```
The error is due to the preexisting sorting issues, I decided to not suppress that error since it should be rare once the initial re-sorting is complete (PR incoming for that shortly).
=> tools/psltool: support for analyzing a github PR

public_suffix_list.dat
These are all pure block movements, no suffix or metadata changes. Just out of paranoia, I verified the change with some extra manual steps:
- `ripgrep -v '^//' | ripgrep -v '^$' | sort >suffixes.txt` before and after the reformat shows no diffs, IOW exactly the same suffixes are present.
- `sort <public_suffix_list.dat >lines.txt` shows only 1 diff, post reformat the file has 1 blank line less than the original, no changes to any comment or suffix text.
- `psltool validate public_suffix_list.dat` reports that the PSL file is valid, i.e. no formatting issues and no issues with the validations implemented so far.
- `make test` of course. All tests pass.
- After opening the PR, `psltool check-pr 2088` (with code from #2087) reports that the file is valid and has no changed suffix blocks. …
=> Run 'psltool fmt' to reformat PSL to canonical form

public_suffix_list.dat
=> add `wdh.app`

public_suffix_list.dat
=> add ggff.net and filegear-sg.me

public_suffix_list.dat
====
- We do not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling.
---
To ensure that …
=> Add IONOS product domains

public_suffix_list.dat
I completely forgot about wildcard support in the PSL 😆, so I've consolidated the 2 entries together. This is because I'm likely going to start deploying some more 3rd/4th level subdomains for my hosting service, not just `preview.wdh.app`.
I've also updated my website URL.
I've updated the `_psl.wdh.app` TXT record to this PR as well.
=> merge `wdh.app` entries together using wildcard

public_suffix_list.dat
`localzone.xyz` was added in https://github.com/publicsuffix/list/pull/915 with the intention to introduce a domain that can be used for internal services across different organizations without the risk of collisions.
With the latest [board decision of the ICANN](https://www.icann.org/en/board-activities-and-meetings/materials/approved-resolutions-special-meeting-of-the-icann-board-29-07-2024-en#section2.a) to finally reserve the `.internal` TLD for this specific use-case, `localzone.xyz` is no longer needed and the use of `.internal` is recommended instead.
I therefore intend to have `localzone.xyz` lapse in the future. I already removed the corresponding `_psl` record to indicate that this PSL entry should be removed.
Sorry for the rollback and thank you very much for your hard work. 🙏
=> remove `localzone.xyz`

public_suffix_list.dat
This domain was originally added in #447, which was made in 2017. Upon checking the registration date of `blogsite.xyz` via a WHOIS lookup, it says it was registered on `2021-10-25`, which likely means the registration lapsed and another registrant registered it.
When searching for a TXT record under `_psl.blogsite.xyz`, it simply returns an SPF record, which is just a wildcard record across all subdomains:
```
v=spf1 -all
```
Also, the name servers of the domain name point to the following, which is just a parking page service:
```
ns1.fp261.parklogic.com
ns2.fp261.parklogic.com
```
It is evident the registration has lapsed, where another registrant has registered it and this domain name is no longer eligible for PSL status.
Upon attempting to reach both the HTTPS and HTTP versions of …
=> remove `blogsite.xyz`

public_suffix_list.dat
Both domains were added in #300, however since their service has shutdown and one of the domain names expired nearly a month ago and I believe they are going to let the other one expire as well.
This domain expired 2024-07-13, 28 days ago as of writing this.
It seems like they are not going to renew it as it has been that long since and the WHOIS server returns `Renewal required.`
When looking up the domain on Google using `site:wellbeingzone.co.uk`, all that is returned is:
The registry does not seem to return the domain expiry date for this domain via a WHOIS lookup, however I would estimate it will expire fairly soon.
When going to the site it shows a service shutdown page:
Running a subdomain scan returns no results: https://subdomainfinder.c99.nl/scans/2024-08-11/wellbeingzone.eu …
=> remove Revitalised Limited section

public_suffix_list.dat
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-ex …
=> Add routingthecloud.com/.net/.org

public_suffix_list.dat
=> Move Domains Under OpenHost

public_suffix_list.dat
- See the comments under https://github.com/publicsuffix/list/pull/1181#issuecomment-2246797225 for the confirmation process.
- The domain fireweb.app was registered on 2023-07-30T21:51:15Z, which is after the date of its initial inclusion. It seems the domain lapsed and was then picked up by another party. Interestingly the TXT record exists at `_psl.fireweb.app`.
- The organization website https://firewebkit.com provided in the initial request is not working.
- An attempt was made to contact the submitter via GitHub on July 23, 2024, but no response was received.
- An inquiry email was sent to the submitter's email addresses on September 3, 2024. However, the email address of the initial submitter is invalid. `<mqureshi@amrayn.com>: host route1.mx.cloudflare.net[162.159.205.13] said: …
=> Remove `fireweb.app`

public_suffix_list.dat
[Confirmed](https://github.com/publicsuffix/list/pull/294#issuecomment-2249938664) by the initial PR submitter in #294
=> Remove `publishproxy.com` (#294)

public_suffix_list.dat
Confirmed by initial requestor in https://github.com/publicsuffix/list/pull/1089#issuecomment-2331078184
> as you will see from the conversation above, CentralNic sold those domains many years ago, and I left CentralNic last year in any case.
> As discussed with @dnsguru back in 2020, I attempted to contact the owners of the domains but I don't recall ever getting an answer. If the PSL's policy now is to remove entries that lack a DNS proof, then by all means go ahead.
---
**1. ar.com**
- `_psl.ar.com` TXT record does not exist.
- No live website under `ar.com` based on [Google Search](https://www.google.com/search?q=site%3Aar.com) and [Bing Search](https://www.bing.com/search?&q=site%3Aar.com).
- No entries found in [Certificate Transparency (CT) logs](https://crt.sh/?q=ar.com).
- No …
=> Remove discontinued CentralNic entries

public_suffix_list.dat
---
---
====
'HostBip' is a 'PDNR' (Private Domain Name Registry), allowing 3rd parties to register domain names in a variety of domain name …
=> UPDATE HOSTBIP DOMAIN NAMES (2024) +biz.ng +plc.ng -edu.scot -sch.so

public_suffix_list.dat
confirmed by initial requestor: https://github.com/publicsuffix/list/pull/1617#discussion_r1746319262
=> Remove `autocode.dev` (Rollback #1617)

public_suffix_list.dat
Original PR was #708 
- Domain was added to the PSL on 2018-12-28, however the domain's registration date according to a WHOIS lookup is 2023-08-06, which likely means the domain lapsed and a different person registered it.
- Domain has expired as of 2024-08-06.
- No TXT record at `_psl.dapps.earth`
- No results when looking up `site:dapps.earth` on Google, other than a for sale page on the root which no longer loads.
- No active SSL certificates: https://crt.sh/?q=dapps.earth
=> remove `dapps.earth` section

public_suffix_list.dat
To address #1695 
Source: https://www.nic.cu/docum_det.php?doc_id=2&opt=1
> com.cu: para personas jurídicas con actividades comerciales de bienes y servicios con fines de lucro;
> edu.cu: para definir centros del sistema de Educación;
> gob.cu: para órganos y organismos de la Administración Central del Estado y otras estructuras de Gobierno;
> inf.cu: para entidades relacionadas con la actividad de información científica y proveedores de información o contenidos; 
> nat.cu: para personas naturales residentes en el país.
> net.cu: para Proveedores Públicos de Telecomunicaciones;
> org.cu: para Organizaciones no gubernamentales y sin fines de lucro;
Although gov.cu is not listed by the registry and may have been mistakenly included as a legacy entry, this PR preserves it for now out of …
=> Add gob.cu nat.cu (#1695)

public_suffix_list.dat
This domain name I believe was originally added along with all of the other eu.org suffixes (pre moving to GitHub?)
There are no nameservers under this subdomain nor does there seem to be any registered subdomains for it.
If you search Google using `site:mc.eu.org`, there is no results. The domain is not listed on the eu.org registration website either: https://nic.eu.org/opendomains.html
After running a SSL certificate lookup, no certificates were found: https://crt.sh/?q=mc.eu.org
I believe there is enough evidence to support the idea that this subdomain is not used nor is active.
=> remove `mc.eu.org`

public_suffix_list.dat
https://github.com/publicsuffix/list/pull/1095#issuecomment-2334331448  by @tuchinsun :
> Hi, Thank you for the notification. I've reviewed our existing list, and the following domains(subdomains) can be deleted from the PSL list
> 
> ```
> mycloud.by
> amscompute.com
> kilatiron.com
> lon.wafaicloud.com
> cloud-fr1.unispace.io
> cloud.jelastic.open.tim.it
> faststacks.net
> jelastic.tsukaeru.net
> jelastic.regruhosting.ru
> upaas.kazteleport.kz
> ```
The connection between Jelastic and the user who provided this confirmation can be identified through #1151.
=> Remove discontinued Jelastic domains (from #1095)

public_suffix_list.dat
=> Add v0.build and vusercontent.net

public_suffix_list.dat
=> add `t.hrsn.dev`

public_suffix_list.dat
=> add `hrsn.dev`

public_suffix_list.dat
This PR is to remove `mycd.eu` to rollback #233
Evidence:
- Attempts to contact via email (Marcus Popp at admin@callidomus.com) were unsuccessful - no MX record at `callidomus.com`.
- Attempted to contact the original requester through a GitHub mention in #233, but there has been no response for over 2 weeks.
- The organization website (https://www.callidomus.com/) is not functioning.
- The [Google search](https://www.google.com/search?q=site%3Amycd.eu) and [Bing search](https://www.bing.com/search?&q=site%3Amycd.eu) show no results for the domain.
- [Certificate Transparency](https://crt.sh/?q=mycd.eu) reveals no active SSL certificates in use. None alive after 2021-04-22.
- Running `dig +short TXT _psl.mycd.eu` no longer returns the required record value.
- No subdomains were found by …
=> Remove `mycd.eu` to rollback #233

public_suffix_list.dat
These domains are not active anymore.
Related to https://github.com/publicsuffix/list/pull/572#issuecomment-2357609725
=> Remove *.sensiosite.cloud and *.s5y.io

public_suffix_list.dat
https://github.com/publicsuffix/list/pull/1493
Request to remove ktistory.com from the PSL
=> Remove domain:ktistory.com from PSL

public_suffix_list.dat
To isolate user-created spaces between each other.
Spaces have `*.static.hf.space` domains for space composed of static files only, and `*.hf.space` domains when they run a backend.
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will …
=> Add `hf.space` and `static.hf.space` to `public_suffix_list.dat`

tools/internal/github/pr.go
One more step towards TXT record validation: we need to be able to check the state of past PRs, including merged PRs.
For review, I suggest ignoring the "old" part of the diff completely, and just look at the new part. The logic is sufficiently different that a diff doesn't really help.
=> tools/internal/github: support loading PR diffs for merged PRs

tools/psltool/psltool.go
Initial step for #2158: no multi-version comparison yet, but this makes `psltool validate` accept a local file or a commit hash. In the next PR I'll add optional comparison against a diff base.
=> tools/psltool: allow checking the PSL for an arbitrary commit on github

tools/internal/domain/domain.go
This is needed for doing DNS resolution, e.g. for TXT record checking.
---
Once this PR and #2175 and #2176 are merged, the next PR will be TXT validation again, slimmer and hopefully easier to review! :)
=> tools/internal/domain: add functions to render a domain as punycode

tools/internal/parser/diff.go
Opened in relation to #2168 as it seems we are meant to keep CI changes separate, which was mentioned by @danderson in https://github.com/publicsuffix/list/pull/2168#issuecomment-2359018880.
*Only merge this PR once #2168 is merged, otherwise checks will likely fail.*
=> tools/internal/parser: remove exception for duplicate sections

public_suffix_list.dat
This PR is to remove `daplie.me` to rollback commit a4d8335
Evidence:
- The WHOIS creation date 2022-05-14 is later than the PSL inclusion date, suggesting the domain was likely allowed to expire.
- Attempts to contact via email (aj@daplie.com) were unsuccessful - no MX record at `daplie.com`
- Attempted to contact the original requester through a GitHub mention in #74, but there has been no response for over 2 weeks.
- The organization website (https://daplie.com) is not functioning.
- The [Google search](https://www.google.com/search?q=site%3Adaplie.me) and [Bing search](https://www.bing.com/search?&q=site%3Adaplie.me) show no results for the domain.
- [Certificate Transparency](https://crt.sh/?q=daplie.me) reveals no active SSL certificates in use.
- Running `dig +short TXT …
=> Remove `daplie.me` to rollback commit a4d8335

public_suffix_list.dat
This PR is to remove `forte.id` to rollback PR #1081
Evidence:
- The domain has been SERVFAIL for a long time. Also noted in #2160. None of the authoritative DNS servers are available. 
- ⚠️ Attempted to contact the original requestor through a GitHub mention in #1081, but the requestor has been no longer associated with the organization.
- ⚠️ ~~Email confirmation yet to be sent.~~ Sent on 09/18/2024 to both the email listed in PSL and `contact@mobileeducation.us` which is found on the company website.
- The organization website (https://joinforte.com) is now a music service. No longer matching the described purpose in #1081 : `MobileEducation, LLC provides online education services, primarily Forte. We allow schools and teachers to register vanity urls as subdomains of forte.id to make …
=> Remove `forte.id` to rollback #1081

public_suffix_list.dat
This PR is to remove dyn53.io as a rollback for #820
- I [attempted](https://github.com/publicsuffix/list/pull/820#issuecomment-2330553290) to contact the original requester through a GitHub mention, but received no response for over 2 weeks.
- ⚠️ ~~Email confirmation yet to be sent.~~ Pending reply. Sent on 09/18/2024 to both the email listed in PSL and the requestor's GitHub profile email.
- The organization's website (https://port53.io) is not functioning and is using domain parking nameservers.
- The [Google search](https://www.google.com/search?q=site%3Adyn53.io) and [Bing search](https://www.bing.com/search?&q=site%3Adyn53.io) shows no results for the domain.
- [Certificate Transparency](https://crt.sh/?q=dyn53.io) reveals no active SSL certificates in use.
- Running `dig +short TXT …
=> Remove `dyn53.io` to rollback #820

public_suffix_list.dat
This PR is to remove `certmgr.org` to rollback #225
Evidence:
- The WHOIS creation date 2020-11-06 is later than the PSL inclusion date of #225, suggesting the domain was likely allowed to expire.
- Attempts to contact via email (admin@certmgr.org) were unsuccessful - no MX record at `certmgr.org`
- Attempted to contact the original requester through a GitHub mention in #225, but there has been no response for over 2 weeks.
- The organization website (https://certmgr.org) is not functioning.
- The [Google search](https://www.google.com/search?q=site%3Acertmgr.org) and [Bing search](https://www.bing.com/search?&q=site%3Acertmgr.org) show no results for the domain.
- [Certificate Transparency](https://crt.sh/?q=certmgr.org) reveals no active SSL certificates in use. None active after …
=> Remove `certmgr.org` to rollback #225

public_suffix_list.dat
- this pr will not aim to workaround any rate limitations
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding.
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expec …
=> add mittwald product domains

public_suffix_list.dat
This PR has been created to re-add `cnpy.gdn` to the PSL, restoring #633 by reverting the removal PR #2174, as requested by @angelogladding, who is the original requestor of #633:
https://github.com/publicsuffix/list/pull/2174#issuecomment-2387255985
The DNS failure mentioned in the related issue https://github.com/publicsuffix/list/issues/2172 may be due to a temporary misconfiguration error, as indicated by the requestor.
=> Add back `cnpy.gdn` to restore #633

public_suffix_list.dat
This PR is to remove bounty-full.com, alpha.bounty-full.com, and beta.bounty-full.com as a rollback for commit e54599a
Evidence:
- Attempted to contact the original requester through a GitHub mention in #104, but received no response for over 2 weeks.
- The organization's website (http://www.skyhat.io) is not functioning.
- The [Google search](https://www.google.com/search?q=site%3Abounty-full.com) and [Bing search](https://www.bing.com/search?&q=site%3Abounty-full.com) show no results for the domain.
- [Certificate Transparency](https://crt.sh/?q=bounty-full.com) reveals no active SSL certificates in use.
- ⚠️ Running `dig +short TXT _psl.bounty-full.com` still returns the required record value.
- No resolvable subdomains were found by third-party tools …
=> Remove `bounty-full.com` to rollback commit e54599a

public_suffix_list.dat
====
_AWS does not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling._
_Please see the Reason section below for objectives in this pull request._
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the …
=> AWS Submissions to the Public Suffix List - Q3 2024

public_suffix_list.dat
I'm not sure where this was originally added in, possibly added pre-GitHub. 
Pretty simple reason for removal; the domain name is expired.
When attempting to lookup the domain via WHOIS, the server returns:
```
$ whois blogspot.mr
Server can't process your request at the moment.
```
And to clarify, I don't believe this is a server issue as looking up, for example, `nic.mr` works perfectly fine and returns the WHOIS data.
When attempting to lookup NS records the server returns `NXDOMAIN`.
=> remove `blogspot.mr`

public_suffix_list.dat
- Not listed on nic.eu.org's open domains page: https://nic.eu.org/opendomains.html
- No sites found when searching `site:paris.eu.org`
- No subdomains were found when searching on https://subdomainfinder.c99.nl/
There was one subdomain found with active SSL certificates (https://crt.sh/?q=paris.eu.org), `cdn.paris.eu.org`, it does have active NS records pointing to Cloudflare, however I cannot find any live sites or any records on that zone when using [NSLookup.io](https://www.nslookup.io/domains/cdn.paris.eu.org/dns-records). The SSL certificates are likely auto generated by Cloudflare, as there are no active sites that can be found on that subdomain.
It should be safe to remove this domain as there does not seem to be evidence of usage. Even if `cdn.paris.eu.org` …
=> remove `paris.eu.org`

.github/pull_request_template.md
To address the issue:
- #1813
This PR introduces updates to the PR submission template to address the issue raised in #1813 concerning the accountability of subdomain registries and the need for abuse contact information.
The new requirements aims to require that requestors who operate subdomain registries provide easily accessible abuse contact information, such as an email address or a web form, which allows responsible parties to be contacted in the event of abuse or malicious activities.
---
cc @dnsguru @simon-friedberger
=> Update PR Template Requiring Abuse Contact for Subdomain Registry Requestors

tools/internal/github/pr.go
Sometimes, the API returns PR info with a null "mergeable" bool, which means "I need a few seconds to update the PR and check for mergeability, please try again in a few seconds". Previously this was interpreted by psltool as "this PR has a merge conflict and cannot be checked".
Instead, do as the Github API docs say, and just keep polling until the PR information is up to date.
---
I tested this change by carefully predicting an open PR that probably had outdated mergeability information (opening the PR in a browser updates mergeability, so you have to guess :sweat_smile: ), and verifying with a temporary log statement that psltool gets incomplete PR data, and correctly waits+retries:
```
> go run ./psltool check-pr --online-checks 2202
DEBUG: PR merge information not ready yet, …
```
=> tools/internal/github: correctly handle github's mergeability updates

public_suffix_list.dat
Related issue: #2172 
- Company was [acquired by Cisco in 2020](https://www.cisco.com/c/en/us/about/corporate-strategy-office/acquisitions/banzaicloud.html)
- All activity on github and related CNCF spaces stopped >1 year ago, aside from automated depaware updates.
- All three domains (`banzai.cloud`, `app.banzaicloud.io`, `backyards.banzaicloud.io`) are hard down at the DNS level. All domains are delegated to AWS Route53, which is responding REFUSED - indicating Route53 is no longer configured to serve those domains. My guess is the AWS account was shut down.
- Another open source project [removed references to banzai cloud](https://github.com/thanos-io/thanos/pull/6901) around a year ago, due to the link becoming dead at that time.
- A final piece of hosting for Banzai's products went …
=> Remove Banzai Cloud

public_suffix_list.dat
[Contact Form](https://medusajs.com/contact)
---
(Link: [about …
=> Add medusajs.app domain to public list

public_suffix_list.dat
This PR is to remove `ybo.faith`, `homelink.one`, `ybo.party`, `ybo.review`, `ybo.science`, and `ybo.trade` due to evidence suggesting domain inactivity.
- Attempts to contact via email (mitch@yombo.net) were unsuccessful – no MX record at `yombo.net`. No mail servers found.
- The organization website (https://yombo.net) is no longer functioning and now points to a stationary print business.
- Unable to identify any email address. `@yombo.net` has no MX.
As identified in #2172:
```
ybo.faith TIMEOUT
ybo.party TIMEOUT
ybo.review SERVFAIL
ybo.science TIMEOUT
ybo.trade TIMEOUT
```
---
**1. `ybo.faith`**
- The [Google search](https://www.google.com/search?q=site%3Aybo.faith) and [Bing search](https://www.bing.com/search?q=site%3Aybo.faith) show no results for the domain.
- [Certificate …
=> Remove inactive or expired yombo domains

public_suffix_list.dat
This PR addresses concerns around the `ne.pw` domain, part of a broader issue (#2199), where a China-based entity appears to be exploiting outdated ICANN section domains. The suspicious activity includes possible SEO manipulation and potential spamming through randomized subdomains. Given `ne.pw`'s treatment by PSL users as a ccTLD, this raises concerns about its legitimate use and potential abuse.
- The [Google search](https://www.google.com/search?q=site%3Ane.pw) found nothing for the **ne.pw** domain, while [Bing search](https://www.bing.com/search?&q=site%3Ane.pw) returned several sites under **ne.pw**. However, nearly all the results have the same site name and title, suggesting possible SEO manipulation, likely taking advantage of the fact that **ne.pw** is treated as a ccTLD …
=> Remove `ne.pw`

public_suffix_list.dat
This PR is created to update the `.NA` entries.
@dnsguru has obtained confirmation directly from the .NA registry, as documented in https://github.com/publicsuffix/list/issues/2199#issuecomment-2396379694 and https://github.com/publicsuffix/list/pull/2198#discussion_r1789874645 :
> I am friends with .NA and reached out by private email (sorry, won't share) but got the following response from them about the structure of "official" subdomains underneath .NA
> 
> Here is the list he provided me:
> 
> na
> alt.na
> co.na
> com.na
> gov.na
> net.na
> org.na
> 
> They actually asked if we would purge the balance of them - I will note this in https://github.com/publicsuffix/list/pull/2198
=> Update `.NA` entries

public_suffix_list.dat
This PR addresses concerns around the `museum.mw` domain, part of a broader issue (#2199), where a China-based entity appears to be exploiting outdated ICANN section domains. The suspicious activity includes possible SEO manipulation and potential spamming through randomized subdomains. Given `museum.mw`'s treatment by PSL users as a ccTLD, this raises concerns about its legitimate use and potential abuse.
- The [Google search](https://www.google.com/search?q=site%3Amuseum.mw) found 1 dysfunctional site for the **museum.mw** domain, while [Bing search](https://www.bing.com/search?&q=site%3Amuseum.mw) returned several sites under **museum.mw**. However, nearly all the results have the same site name and title and randomized subdomains, suggesting possible SEO manipulation, likely taking …
=> Remove `museum.mw`

.github/workflows/psltool_pr_check.yml, tools/internal/github/pr.go, tools/internal/parser/validate.go, tools/psltool/psltool.go
Enable DNS checks for PR action.
Rename Client to GHRepo because the internal github.Client and the github.Client from the library confuses my IDE.
Pass the GHRepo to validateTXTRecords so it uses the correct repository.
=> Improve psltool PR check

tools/internal/githistory/history.go, tools/internal/parser/validate.go, tools/psltool/psltool.go
This cuts the amount of Github API traffic required to validate the entire PSL by >99%.
---
I ran out of time today to apply the final details (notably, plumbing the git repo path, right now it assumes current working directory where you run psltool is a PSL git repo), so opening as a draft so that it's available for testing. I plan to apply the final touches tomorrow.
=> Make TXT validation use local git history

public_suffix_list.dat
Related issue: #1353 
- Entry added in 2021, with submitter acknowledging requirements of availability, responsiveness and maintaining ownership via a TXT record.
- Domain is hard down at the DNS layer. Glue records delegate to Cloudflare nameservers, which respond REFUSED - presumably account has been shut down.
- Domain has been down since at least 2024-09-05, when @groundcat found its organization URL didn't load in #2135. While hacking on TXT record checking I've probed it multiple times since then, and it's been consistently down.
- All web activity google can find for ddns5.com ended in 2021, a few months after the PSL entry was merged. I couldn't find evidence of any users of the service. The only hits on Google are copies of the PSL, malware reports that reference the domain (in …
=> Remove ddns5.com

public_suffix_list.dat, tools/internal/parser/exceptions.go
admin@tn-cloud.net
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this …
=> Remove bloxcms.com from public suffix list - no longer needed

public_suffix_list.dat
Just updating contact information for is-a.dev.
Last PR updating this section #2074 was created by me.
I've updated the `_psl` TXT record as well:
```
$ dig +short TXT _psl.is-a.dev
"https://github.com/publicsuffix/list/pull/2225"
```
=> chore: update is-a.dev contact info

public_suffix_list.dat
Based on information from the IANA page for .AO domains (https://www.iana.org/domains/root/db/ao.html), the registration services are available at http://www.dns.ao/.
According to the official registry site (http://www.dns.ao/), the suffixes currently available for registration under the .AO domain are:
- .ao
- .it.ao
- .co.ao
- .org.ao
- .edu.ao
- .gov.ao
However, the current PSL shows the following suffixes:
- .ao
- .ed.ao
- .gv.ao
- .og.ao
- .co.ao
- .pb.ao
- .it.ao
Notably, the registry has announced on 2024-07-11 that the domains “.ed.ao” and “.og.ao” will be phased out. This announcement can be found here: https://www.dns.ao/ao/noticias/titulares-de-dominios-ed-ao-e-og-ao-tem-30-dias-para-conversao/
Recently, the registry accredited an official registrar, as announced here: …
=> Add `org.ao`, `edu.ao`, `gov.ao` ccTLD (ICANN section)

public_suffix_list.dat
This PR attempts to address issue #2078 
Registrars are [promoting](https://www.101domain.com/co_ss.htm) the launch of .co.ss domains, which are currently in the sunrise period. General availability will begin on November 1, 2024.
Registrar Sources:
- https://www.101domain.com/co_ss.htm
- https://domgate.com/whois-and-domain-registration/.co.ss
- https://www.lexsynergy.com/tld/co.ss
- https://www.juhub.ss/domain/
National Communication Authority (NCA) source: 
- https://x.com/NCA_SSD/status/1811778704059547783
I sent an email to the ssNIC contacts (https://www.iana.org/domains/root/db/ss.html) but have not received any response.
=> Add `co.ss` ccTLD (ICANN section)

tools/internal/domain/domain.go, tools/internal/parser/file.go, tools/internal/parser/file_test.go
These calculate the public suffix or registered/registerable domain of some input domain, according to the strict PSL algorithm. Aside from being useful as a reference implementation of the algorithm, it comes in handy in validations that need to do stuff like figure out what registry to query for domain info.
---
Please check my work carefully on the PSL algorithm, in particular the handling of wildcard domains. I read [the spec](https://github.com/publicsuffix/list/wiki/Format#formal-algorithm) very carefully and also the [platform.sh wiki page](https://wiki.mozilla.org/Public_Suffix_List/platform.sh_Problem), and I _think_ I've correctly implemented the strict PSL algorithm with no deviation (a public suffix `*.foo.com` does not imply a public suffix `foo.com`, and there is an implicit …
=> internal/parser: add PublicSuffix and RegisteredDomain methods to List

public_suffix_list.dat
Related: #796 
- Suffixes added in 2019, with a requirement to maintain TXT records.
- Domains have been hard down since at least 2023-05, when #1753 found the domains were returning SERVFAIL.
- Domains are currently hard down. Glue records delegate to 2 IPs that are not running any DNS server.
- No evidence of use. Web search finds one passing mention of reliability issues in a related github project back in 2019. All other mentions are copies of the PSL scattered around the web.
- Suffix owner was pinged about the status of these domains over a month ago in #796. No response.
This seems to be a long dead service, if it was ever active at all.
=> Remove Handshake suffixes

public_suffix_list.dat
This PR is to remove `gov.cu`, as it is not a public suffix, which has been confirmed by the .CU operator with assistance from the IANA contact in this comment: https://github.com/publicsuffix/list/issues/1695#issuecomment-2429339242.
> We (IANA) spoke with the .CU manager and they confirmed `gob.cu` is in use as a public suffix, and `gov.cu` is not.
`gob.cu` has been added by #2143.
=> Remove `gov.cu`

public_suffix_list.dat
Updating the list of SLDs under the `.io` TLD.
I'm adding `co.io` and `net.io` as they do seem to be a domain offered by the registry, as it is not reserved, and is registered to the registry operator themselves (`Registry Operator acts as Registrar (9998)`), along with having the same nameservers of `com.io`, which we know is a SLD already. However I will confirm this with the registry, to make sure.
Note: You can technically register domains at the 3rd level, however they are restricted to residents in the British Indian Ocean Territory, however I don't believe there are any inhabitants living there. However, they are still TLDs technically offered by the registry.
This PR will remain in a draft state until I receive a response from the .io registry.
=> chore: update `.io` section

public_suffix_list.dat
This PR focuses on the `.ci` TLD.
This PR addresses concerns around the `presse.ci` and `md.ci` domain, part of a broader issue (https://github.com/publicsuffix/list/issues/2199), where a China-based entity appears to be exploiting outdated ICANN section domains. The suspicious activity includes possible SEO manipulation and potential spamming through randomized subdomains. Given `presse.ci` and `md.ci`'s treatment by PSL users as a ccTLD, this raises concerns about its legitimate use and potential abuse.
- `Creation Date: 2020-04-15` is later than the PSL inclusion date.
- The [Google search](https://www.google.com/search?q=site%3Apresse.ci) and [Bing search](https://www.bing.com/search?&q=site%3Apresse.ci) show no results for the **presse.ci** domain.
- [Certificate …
=> Remove `presse.ci` and `md.ci`, other ccTLD stubs not associated w respective registry

public_suffix_list.dat
.sk does not offer TLDs at the 2nd level, they only allow direct .sk registration.
This was confirmed by the registry.
=> chore: remove 2nd level comment for `.sk`

public_suffix_list.dat
Adding grafana-dev.net
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation …
=> Add grafana-dev.net to public suffix list

public_suffix_list.dat
https://taveusercontent.com/
And the root of all user content subdomians, for example:
https://adrians-dev-studio.taveusercontent.com/
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or …
=> Add `taveusercontent.com`

public_suffix_list.dat
This is not actually a *public* suffix but it is a domain suffix.
This closes #1205.
=> Add home.arpa

public_suffix_list.dat
- The PR (#630) the domain was added in, predates the WHOIS registration date of `2024-02-05`. The previous owner likely let the domain lapse and a new registrant registered it.
- The `_psl.bci.dnstrace.pro` TXT record is no longer in place.
- No results on Google for either `site:bci.dnstrace.pro` or `site:dnstrace.pro`.
- The homepage at http://dnstrace.pro is just a blank page.
- There are no active SSL certificates under the domain: https://crt.sh/?q=dnstrace.pro
- No subdomains found when searching under https://subdomainfinder.c99.nl/
This domain should be safe to remove as there is no evidence of usage.
=> remove `bci.dnstrace.pro`

public_suffix_list.dat
Simply moving the domain `wdh.app` to a new section.
Reason for move is the domain is not really associated with Harrison Network.
The email address is a personal one, as the section is a personal section. 
Updated `_psl` TXT record:
```
$ dig +short TXT _psl.wdh.app
"https://github.com/publicsuffix/list/pull/2246"
```
=> move `wdh.app` to new section

public_suffix_list.dat
Taken from https://belizenic.bz, the URL linked in the section.
There does seem to be usage of the 2LD `.co.bz`, when searching `site:co.bz` on Google.
These should be added ASAP as people are currently able to set cookies on the 2LD itself, which would affect potentially hundreds of other domains on this 2LD.
=> add `co.bz`

public_suffix_list.dat
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, …
=> Add pages-research.it.hs-heilbronn.de

public_suffix_list.dat
Adding LODMAN regional domains
Abuse Contact:
abuse@man.lodz.pl
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/G …
=> Add lodz.pl pabianice.pl plock.pl sieradz.pl skierniewice.pl zgierz.pl

public_suffix_list.dat
Confirmed by the .ad registry:
```
Hi William.
We can confirm that the .ad TLD does no currently operate any functional public SLD. .nom.ad existed, in theory, some time ago, but is no longer offered and there is no currently existing domain under tht SLD nor any other. Only domains under the TLD .ad do exist and are available for registration.
Thanks for checking and for the good work tith PSL.
Equip de suport domini .ad
```
- Email was originally sent to info@domini.ad which is listed on the registry's site in the footer: https://www.domini.ad/contacte/ (Page URL can be verified through IANA's website: https://www.iana.org/domains/root/db/ad.html)
- I received a response from `Amadeu Abril i Abril (CORE) <amadeu.abril@corenic.org>`.
- You can also confirm yourself that the `nom.ad` TLD …
=> remove `nom.ad`

public_suffix_list.dat
I am creating this pull request to update the .JO block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/jo.html and identified the registry website for registration services: https://www.dns.jo/
3. Received a direct reply from the domain registry (`Domain .jo/الاردن. <DNS@modee.gov.jo>`), confirming the requested information.
Excerpt from the email confirmation:
> 1. Operational Status: Is [name.jo](http://name.jo/) still active and registrable?
> ‘.[name.jo](http://name.jo/)’ was stopped since many years and not available for registration, it replaced with ‘.[per.jo](http://per.jo/)’.
> 2. Available …
=> Update .JO section

public_suffix_list.dat
I am creating this pull request to update the .sg block in the ICANN section.
1. Removed `per.sg`
2. Fixed broken link in the comment
3. Added registry contact and date to the comment
**Steps taken to verify information from the authoritative source:**
1. Started at the IANA page: https://www.iana.org/domains/root/db/sg.html and identified the email address as well as the registry website for registration services http://www.sgnic.sg
2. Located the online web-based contact form provided on the registry website and sent an inquiry.
3. Received a direct reply from the domain registry `<dnq@sgnic.sg>`, confirming the requested information.
> Please be informed that ".per.sg" is no longer in operation but the others are still in the operation.
> 
> Thank you.
> 
> 
> Best regards
> Elysa …
=> Update `.SG` Section

public_suffix_list.dat
This PR did not add or remove any entries in the `.PL` block; it simply added comments to assist with future reference and corrected the alphabetical ordering.  
Confirmed by `<info@dns.pl>`:
> 1. Current Status: Are the above-listed NXDOMAIN domains (ic.gov.pl, is.gov.pl, kwp.gov.pl, oirm.gov.pl, oum.gov.pl, us.gov.pl, wskr.gov.pl, wzmiuw.gov.pl) still active and registrable?
> The above-mentioned names are zones in the .gov.pl domain, in which we enable domain registration for authorized entities, in accordance with the .gov.pl Domain Name Regulations https://www.dns.pl/regulamin_gov_pl (available only in Polish language version). The status of each zone may be verified in the WHOIS database.
> 
> 2. Available Suffixes: Could you provide an updated list of all second-level domains …
=> Update `.PL` comments and fix alphabetical sorting

public_suffix_list.dat
I am creating this pull request to update the .co block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/co.html and identified the email address as well as the registry website for registration services https://www.cointernet.com.co/
3. Received a direct reply from the domain registry `<Gonzalo@cointernet.com.co>`, confirming the requested information.
Fully reply to the email confirmation:
</body>
</html>
> Greetings from “.CO Internet”, the “.CO” ccTLD’s Registry Operator.
> 
> Based on the current “.CO “ policies, we operate the following for third level registration:
> 
> “.com.co”, “.net.co”, …
=> Update `.CO` Section

public_suffix_list.dat
I am creating this pull request to update the .re block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/re.html and identified the email address as well as the registry website for registration services http://www.nic.re (Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.))
3. Received a direct reply from the domain registry `<support@afnic.fr>`, confirming the requested information.
Email confirmation:
> From memory, .nom.re was created in 2001 but was not used. What is absolutely certain is that it is not possible to create domain names under .nom.re.
So, `nom.re` should be …
=> Update `.RE` Section

public_suffix_list.dat
Confirmed by the registry (admin@nic.TM):
Here is an excerpt of the email thread:
```
It IS possible to register directly under the TOP level .TM .... AND also
com.tm
co.tm
org.tm
net.tm
nom.tm
gov.tm
mil.tm
edu.tm
```
The full email chain can be provided to a maintainer at request.
- I emailed batyr@nic.tm; hostmaster@nic.tm; which are both listed on the IANA root database and received a response from admin@nic.TM.
=> alphabetise `.tm` section + add confirmation comment

public_suffix_list.dat
This PR did not add or remove any entries in the `.AZ` block; it simply added/fixed comments to assist with future reference and corrected the alphabetical ordering.
List of suffixes https://whois.az/?page_id=10 traced from IANA database page.
=> Update `.AZ` comments and fix alphabetical sorting

public_suffix_list.dat
Confirmed by TTNIC <admin@nic.tt>:
```
Hi,
The list should be as follows:
•	co.tt
•	com.tt
•	org.tt
•	net.tt
•	biz.tt
•	info.tt
•	pro.tt
•	name.tt
•	mil.tt
•	gov.tt
•	edu.tt
So add mil.tt and remove int.tt, coop.tt, jobs.tt, mobi.tt, travel.tt, museum.tt, and aero.tt
Thanks.
-Patrick
```
- Email was sent to admin@nic.tt; tech@nic.tt; got a response from admin@nic.tt.
Email thread is available to maintainers at request.
=> update `.tt` section

public_suffix_list.dat
I am creating this pull request to update the .CW block in the ICANN section.
This PR **did not add or remove any entries** in the .CW block.
1. Started at the IANA page: https://www.iana.org/domains/root/db/cw.html and identified the registry website for registration services http://www.uoc.cw/cw-registry
2. Located email address and sent the inquiry
3. Received response from `".CW Registry Curaçao @UoC" <registry@uoc.cw>`
Excerpt:
> The information,
> 
> // cw : http://www.una.cw/cw_registry/
> // Confirmed by registry <registry@una.net> 2013-03-26
> cw
> com.cw
> edu.cw
> net.cw
> org.cw
> Is incorrect, since we are not using una.cw neither una.net for our systems.
> 
> Actualized information can be found at …
=> chore: Update `.CW` Section comments

public_suffix_list.dat
I am creating this pull request to update the .MG block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/mg.html and identified the email address as well as the registry website for registration services https://www.nic.mg/
3. Received a direct reply from the domain registry `Dany RANDRIARINIVO <dany@nic.mg>`, confirming the requested information.
Fully reply to the email confirmation:
> On Tue, Nov 19, 2024 at 3:27 AM Dany RANDRIARINIVO <dany@nic.mg> wrote:
> Greetings,
> 
> The active and registrable second-level domains for the .MG are :
> org.mg
> nom.mg
> gov.mg
> prd.mg
> com.mg
> co.mg
> 
> edu.mg …
=> Update `.MG` Section

public_suffix_list.dat
I am creating this pull request to update the .DM block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/dm.html and identified the email address as well as the registry website for registration services http://www.nic.dm
3. Received a direct reply from the domain registry <admin@dotdm.dm>, confirming the requested information.
- DKIM:	'PASS' with domain dotdm.dm
> Thank you for your email and inquiry about .dm domains.
> 
> We invite you to visit our Network Information Center, Rules and Guidelines Policy where all your questions can be answered:
> 
> …
=> Update `.DM` Section

public_suffix_list.dat
This PR did not add or remove any entries in the .BO block.
Added comments and fixed the broken link to assist with future reference and corrected the alphabetical ordering.
List of suffixes can be found at https://nic.bo traced from IANA database page.
Confirmed by registry <soporte@nic.bo> 2024-11-19 
> I send the correct suffixes:
> - Second Level Domain
> .bo
> 
>  -Third Level Domain
> .com.bo
> .edu.bo
> .gob.bo
> .int.bo
> .org.bo
> .net.bo
> .mil.bo
> .tv.bo
> .web.bo
> 
>  -Third Level Domains Social
> 
> .academia.bo    
> .agro.bo    
> .arte.bo    
> .blog.bo    
> .bolivia.bo    
> .ciencia.bo    
> .cooperativa.bo    
> .democracia.bo    
> .deporte.bo    
> .ecologia.bo    
> .economia.bo    
> .empresa.bo    
> .indigena.bo    
> .industria.bo    
> .info.bo    
> …
=> chore: Update `.BO` comments and fix alphabetical sorting

public_suffix_list.dat
I am creating this pull request to update the `.CV` block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/cv.html and identified the email address as well as the registry website for registration services http://www.dns.cv/
2. http://www.dns.cv/ is redirected to https://comprar.cv/
3. Located the email address provided on the registry website and sent an inquiry.
4. Received a direct reply from the domain registry `	OlaCV Support <support@ola.cv>`, confirming the requested information.
Email confirmation:
> Thank you for reaching out.
> Registry link: ola.cv
> .cv
> com.cv
> int.cv
> nome.cv
> net.cv
> org.cv
> pub.cv
> id.cv - not open for purchase
> edu.cv -  open to educational …
=> Update `.CV` Section

public_suffix_list.dat
I am creating this pull request to update the .TW block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/tw.html and identified the email address as well as the registry website for registration services http://rs.twnic.net.tw/
4. Located the email address provided on the registry website and sent an inquiry.
5. Received a direct reply from the domain registry `<dns@twnic.tw>`, confirming the requested information.
---
Ticket # 20650
From `no_reply@twnic.net.tw`
> 感謝來信，關於詢問有關.tw的後綴問題，補充說明如下:
> 1. 運營狀態：網路.tw、組織.tw 和 商業.tw 是否仍然活躍並可供註冊？
> --> 目前這三類的域名已不再提供新註冊及續用，現存的域名也不提供異動設定，也無法解析。
> 網路.tw、組織.tw 和 商業.tw   這些後綴是否應該繼續包括在公共後綴列表中？是否需要移除？
> --> 是否從公共後綴列表中移除，您可自行評估。
> 當前後綴列表：能否提供 .TW …
=> Update `.TW` Section

public_suffix_list.dat
**Abuse Contact: RUB abuse team <abuse@ruhr-uni-bochum.de>**
https://www.ruhr-uni-bochum.de/de/impressum or https://www.ruhr-uni-bochum.de/en/legal-notice
found via imprint on (almost) every web page
A more detailed (german only) contact page can be found via "Meldewege" at our IT-Security pages:
https://www.itsb.ruhr-uni-bochum.de/themen/meldewege.html
---
To ensure that requested changes are entirely intentional, make sure that you read …
=> Adding Ruhr University Bochum domains

public_suffix_list.dat
I am creating this pull request to update the .EG block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/eg.html and identified the email address as well as the registry website for registration services http://www.egregistry.eg/
2. `http://www.egregistry.eg/` is redirected to `https://domain.eg/`
3. It appears that the website is only accessible with an Egypt IP address. Otherwise geo-blocked.
4. At `https://domain.eg/`, located the list of suffixes at https://domain.eg/en/domain-rules/subdomain-names-types/
|                                                    | Suffix                             |
|----------------------------------------------------|------------------------------------|
|         The educational   Sector                   | …
=> Update `.EG` Section

public_suffix_list.dat
See https://github.com/publicsuffix/list/pull/1080#issuecomment-2357881134 for evidence of removal. No response from author in over 2 months.
Should be safe to remove as the same issues are still occuring (e.g. website has been down for months, there is not enough sufficient evidence to keep PSL status, etc.)
=> remove `mcpe.me`

tools/internal/parser/clean.go
The ordering rule is slightly different from the private section: suffix blocks do not get reordered, only the suffixes within each block. Additionally, the ICANN section contains many load-bearing inline comments. To avoid semantic changes, the sorting does not move suffixes over such comments. Unlike in the private section, such movement failures aren't treated as errors, because the subsection comments in the ICANN block have a reasonably consistent meaning.
---
This will fail CI until #2287 is merged, along with the additional sorting fixups in https://gist.github.com/danderson/cb0fb30acbec38651cf8c0a1f4275125 for IDNA domains. Depending on whether #2287 is merged with or without the accent fixes, I can add the remaining fixups in this PR, up to you @simon-friedberger @groundcat.
=> tools/internal/parser: enforce suffix ordering in the ICANN section

public_suffix_list.dat
**Abuse Contact:** psirt@nospamproxy.com
https://www.nospamproxy.de/en/cybersecurity-product-security-incident-response-team-psirt/
--- …
=> Add NoSpamProxy sub domain: o365.cloud.nospamproxy.com

public_suffix_list.dat
- No public website at https://upli.io (which is listed as the org website)
- No subdomains can be found either by searching `site:upli.io` on Google or using a subdomain finder like https://subdomainfinder.c99.nl
- No SSL certificates have been issued for subdomains since 2021-10-22, which was a wildcard SSL certificate, which expired 2022-01-20. The only SSLs issued since then seem to be auto-renewed for the root domain: https://crt.sh/?q=upli.io
I think it is safe to remove this domain as it does not seem to be used, nor have any SSLs been issued for subdomains in over 3 years. The purpose of the original inclusion in #1446 was for customer subdomains, however none were found.
=> remove `upli.io`

public_suffix_list.dat
- No third-party limits are being worked around. This is purely to isolate all hosts under 0e.vc from each other.
* E-mail address from the entry. 
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the …
=> Allow 0e.vc to be isolated for all subdomains by adding wildcard

.github/pull_request_template.md
Currently, domain submissions often use personal email addresses despite our preference for role-based addresses. However, this requirement isn't explicitly stated in our guidelines.
This PR attempts to add a new checkbox to the PR template to ensure submitters are using appropriate contact methods and understand the communication requirements for PSL inclusion. Also we've observed a "set and forget" pattern not only with the domains but also with the contact emails too, where submitters either use personal emails (which become invalid when they leave the organization) or set up role-based emails like `psl@example.org` that aren't actively monitored after submission.
The changes include:
1. Requirements for a role-based email addresses
2. Specified 14-day maximum response time for PSL …
=> Add checkbox for contact method to the PR template

public_suffix_list.dat
Last update was #2247, authored by me.
We are renaming it as there is no real reason for us to keep using `getlocalcert.net` when we already have `localcert.net`.
Note: User subdomains will still be hosted on both `localcert.net` and `localhostcert.net`, hence why they are still being included in the PSL. I understand the risks of continuing to have `localcert.net` listed.
=> rename `GetLocalCert` to `LocalCert`

public_suffix_list.dat
Originally moved from the ICANN section to the PRIVATE section in #815.
- We do not allow testing domains as per the guidelines:
> Projects that are smaller in scale or are temporary or seasonal in nature will likely be declined. Examples of this might be private-use, sandbox, test, lab, beta, or other exploratory nature changes or requests. It should be expected that despite whatever site or service referred a requestor to seek addition of their domain(s) to the list, projects not serving more then thousands of users are quite likely to be declined.
- No SSL certificates found: https://crt.sh/?q=.test.ru (the first `.` is required, otherwise it returns results from unrelated domains for some reason, you can verify this yourself here: https://crt.sh/?q=test.ru)
- …
=> remove `test.ru`

public_suffix_list.dat
* NONE
URL where abuse contact or abuse reporting form can be found: https://aiven.io/.well-known/security.txt and may also be reported to security@aiven.io
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh …
=> add aiven.app to public suffix

public_suffix_list.dat
- No active SSL certificates on `fwnk.site` or `folionetwork.site`: https://crt.sh/?q=fnwk.site&exclude=expired https://crt.sh/?q=folionetwork.site&exclude=expired
- Very few active SSL certificates found on `platform0.app`: https://crt.sh/?q=platform0.app&exclude=expired
- I believe they may issue SSLs on a per domain basis, and only use wildcards on the occasion where no website exists using a wildcard (e.g. https://exampletest123.platform0.app)
- In the original PR #1074, the domains `fwnk.site` and `folionetwork.site` were intended to be used by https://folio.network, however the domain does not have any A/AAAA records, therefore it doesn't resolve.
- No results on Google or Bing for any of the domains when searching using `site:{domain}`.
- `_psl.fwnk.site` is …
=> remove Danger Science section

public_suffix_list.dat
Originally added in #1795.
- No website loads on https://aaa.vodka, which is specified as the company URL
- The contact email address does not exist as there are no MX records at `aaa.vodka` (pointed out by @groundcat in https://github.com/publicsuffix/list/pull/1795#discussion_r1746293949, however he received no response)
- No sites found on Google when searching `site:aaa.vodka`
- Only one subdomain found using a subdomain finder: https://subdomainfinder.c99.nl/scans/2024-12-11/aaa.vodka
- It is worth noting, the subdomain found `nugget.aaa.vodka`, seems to be a very simple static website, and it is also worth pointing out the domain is added as a zone on Cloudflare as it has Cloudflare NS records, I believe the original request may have just been used to evade …
=> remove `aaa.vodka`

public_suffix_list.dat
- Heroku no longer uses `herokussl.com` for SSL certificates, it now uses `herokudns.com` - you see no mention of the domain in their support article (last updated 2nd February, 2024) on SSL certificates: https://devcenter.heroku.com/articles/ssl
- Another article, on TLS, shows `herokudns.com` being used instead of `herokussl.com`: https://devcenter.heroku.com/articles/understanding-tls-on-heroku
- There have been no SSL certificates issued on the domain itself either since 2019: https://crt.sh/?q=herokussl.com (note: no SSLs have been issued on `herokudns.com` since 2020 either, however it is actively shown and used in documentation regarding SSL)
There does not seem to be any evidence of usage of this domain and it should be safe to say it is no longer in use and …
=> remove `herokussl.com`

public_suffix_list.dat
https://myaddr.tools/ and https://dyn.addr.tools/
---
(Link: [about …
=> Add addr.tools dynamic dns services

public_suffix_list.dat
Domain was originally added in #331, in 2016, however the registration date for the domain is 2023-11-30, suggesting that the domain lapsed (like the other 6 domains removed in #2173) and has changed registrants.
It should be safe to remove this domain.
=> remove `yombo.me`

public_suffix_list.dat
Domain was added in #849, in 2019, however the registration date of the domain is 2023-11-30, it is clear the domain lapsed and has changed registrants.
This domain should be safe to remove.
=> remove `lelux.site`

public_suffix_list.dat
IANA page: https://www.iana.org/domains/root/db/bw.html
https://nic.net.bw is the listed registry site, and under https://nic.net.bw/bw-name-structure it has a list of all the 2LDs. This is an authoritative source and can be trusted.
=> update `.bw` section

public_suffix_list.dat
The [IANA page](https://www.iana.org/domains/root/db/az.html) shows `whois.az` as the authoritative source for the TLD.
List confirmed via https://whois.az/?page_id=10 section 2.2
`pro.az` is no longer available for registration, however according to the [statistics page](https://whois.az/?page_id=783) it still has some registered domains. We will keep it for legacy reasons.
=> update `.az` section

public_suffix_list.dat
- Domain expired 2024-10-27
- No results on Google
- No results on https://subdomainfinder.c99.nl/
Note: The domain is in a redemption period, according to a WHOIS lookup, however it seems they will not be renewing it as it expired over a month ago and still hasn't been renewed.
Pretty basic removal, domain is expired, should be safe to remove.
=> remove `shiftedit.io`

public_suffix_list.dat
Domain was added in #1138, in 2020, however the registration date for the domain is 07-05-2024, it is clear it is no longer controlled by the original registrant and should be removed.
The current registrant is shown to be `YMHC CHARITABLE FOUNDATION`, which is a completely different organisation. This domain should be safe to remove.
=> remove `secaas.hk`

public_suffix_list.dat
Originally added in #807, back in 2019.
- The domain is no longer controlled by `Gentlent, Inc.`.
- The domain's registration date via a WHOIS lookup is `2024-07-25`, which is very recent, when the domain was added to the PSL around 5 years ago. The new registrant's name is `Flame Lab Initiative` according to WHOIS, which is not the original registrants.
Should be safe to remove, as it is no longer owned by the original registrant.
=> remove `lab.ms`

public_suffix_list.dat
I may end up deprecating wdh.gg at some point so I am just putting my direct website link, also it just redirects to my website anyways.
=> chore: update website URL

public_suffix_list.dat
Pointed out in #2345, domain was originally added in #935.
- Domain was added to the PSL over 4 years ago, however according to WHOIS it was registered `2023-06-16`, indicating the owner has changed. (The registrant contacts compared to the other entries in this block are completely different companies)
- Domain is listed for sale on HugeDomains.com, indicating no usage: https://www.hugedomains.com/domain_profile.cfm?d=platter-app&e=com
- In WHOIS, the domain's registrant name is listed as `Domain Admin / This Domain is For Sale`.
It is evident this domain lapsed and has been picked up by a new company. This domain should be safe to remove.
I had a look at the other domains in this section (only via WHOIS) and they all appear to still be registered to the same …
=> remove `platter-app.com`

public_suffix_list.dat
Pointed out in #2345, originally added in #166.
- Domain was added to the PSL in 2016, however it was registered on `2022-05-10` according to WHOIS.
- The nameservers of the domain appear to point to parking nameservers: `a.dns.park.io` `b.dns.park.io`
- The domain is listed for sale on https://park.io according to the webpage on the domain: http://spacekit.io/
This domain should be able to be safely removed.
=> remove `spacekit.io`

public_suffix_list.dat
In the original PR (#1393) adding these domains, the author stated that different customers will be allocated subdomains of these domains.
However it does not seem the domains are being used by other parties, especially as there doesn't seem to be any subdomain usage.
- No subdomains are found on diher.solutions or rss.my.id when searching using a subdomain finder: https://subdomainfinder.c99.nl/
- When searching `site:diher.solutions` on Google the only site that shows up is the root domain which appears to be a personal site, not a web hosting service which was what the submitter was intending for these domains to be used for.
- When searching `site:rss.my.id` on Google only results from the root domain are shown, no subdomains are found, it appears to just be a personal blog.
- …
=> remove Diher Solutions section

public_suffix_list.dat
Originally added in #968.
- `_psl.curv.dev` TXT record no longer resolves, which provokes the that idea that PSL status is no longer required, as this TXT record was present when the domain was added to the PSL.
- No results on Google or Bing for `site:curv.dev`, despite the reason for inclusion being that customer websites will be on this domain.
- Few results show up from a subdomain scan, most of which do not resolve properly, if at all: https://subdomainfinder.c99.nl/scans/2024-12-10/curv.dev (also, it is well below our required threshold for inclusion)
- Very few results show up when searching for SSL certificates under the domain: https://crt.sh/?q=curv.dev&exclude=expired&group=none
It is quite evident this domain is not being actively used and should be able …
=> remove `curv.dev`

public_suffix_list.dat
Originally added in
- #733
Steps:
- I attempted to email `security@hakaran.cz` on 2024-09-05, but it was unreachable.
- The organization's website, `http://hakaran.cz`, is not working.
- I tried [tagging](https://github.com/publicsuffix/list/pull/733#issuecomment-2332990195) the requester on 2024-09-05 in the initial GitHub PR, but received no response.
- No subdomains were observed (CT, Google) for all domains, except for `free.hr`, which seems to have changed ownership (`GRANSY d.o.o.` from WHOIS no longer match `Hakaran group`) and is no longer owned by the initial requesting organization.
- `fin.bj` has already expired and is now available for registration. According to WHOIS: `Domain Status: No Object Found`.
- @wdhdev @fakeboboliu might have more information if you would like to …
=> Remove Hakaran group domains

public_suffix_list.dat
The goal for this section of the PSL is to create a sandbox for testing the affects of different rules on the PSL.
This implements #1349.
The sandbox hasn't been deployed yet, however once these entries are listed I will deploy one so users can test out various differences domains have for when they are on the PSL.
Note: I have added these under subdomains of psl.hrsn.dev in order to prevent any potential problems or overlaps with the existence of the `hrsn.dev` rule. Also, I've added this in a new section as I would like these entries to remain as a separate "project" to Harrison Network specifically.
It also might be worth noting that these will be the first exception rules `!` in the private section. 
All `_psl` TXT records have been put in place for the corresponding names.
=> add PSL Sandbox

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://www.cloudbees.com
---
(Link: [about …
=> Add `cloudbeesusercontent.io`

public_suffix_list.dat
Email sent to gmalone@trc.vg; tld.ops@centralnic.com on 2024-12-10 (the contacts listed on the [IANA page](https://www.iana.org/domains/root/db/vg.html)), received a reply on 2025-01-10 from tld.ops@centralnic.com. 
Email forwarded to @simon-friedberger and @dnsguru.
```
Adam Russell (CentralNic Registry) 
10 Jan 2025, 09:42 UTC 
Hi William,
Firstly, thank you for your voluntary work and secondly:
Apologies for the delayed response, our ticket handler didnt like the formatting and your ticket ended up in a catch-all bucket.
The only one I have is edu.vg
Regards,
Adam
```
=> add `edu.vg`

public_suffix_list.dat
**Abuse Contact:** subpro-support@robotpayment.co.jp
URL where abuse contact or abuse reporting form can be found: https://www.robotpayment.co.jp/contact/
---
To ensure that requested changes are entirely …
=> Add subsc-pay suffix domain

.github/workflows/psltool_pr_check.yml, tools/go.mod, tools/go.sum, tools/internal/github/pr.go, tools/psltool/errors.go, tools/psltool/psltool.go
A simple improvement of psltool, may fix #2352
not all error has its corresponding label for now, but I leave slots for them in this 5-minute work.
=> set label on PR based on check result

public_suffix_list.dat
**Previous submission**: https://github.com/publicsuffix/list/pull/1872
URL where abuse contact or abuse reporting form can be found: https://brave.com/.well-known/security.txt
---
PR Rollbacks …
=> Brave Submissions to the Public Suffix List - Q1 2025

public_suffix_list.dat
---
This request was not submitted to circumvent third-party rate limits or restrictions.
I acknowledge it is my responsibility to maintain these entries (removing unused names, renewing the domain, keeping `_psl` DNS entries live, etc.). Noncompliance may lead to removal.
I have carefully read the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) and confirm this request aligns with them.
The entries are placed in the **PRIVATE DOMAINS** section and sorted alphabetically based on the organization name comment.
A role-based email address is provided below, actively monitored for PSL-related queries.
Abuse contact info is published on our site and is easily discoverable:
- URL for abuse reporting: **[obj.ag](https://obj.ag)** 
---
> …
=> Add obj.ag to Public Suffix List

public_suffix_list.dat
Checklist of required steps
https://localtonet.com/abuse
---
---
Localtonet is a tool that allows users to make web applications or services running on a local machine or local network (localhost) accessible from the internet. Normally, web servers that can only be accessed locally or within a local network can be shared publicly through tools like Localtonet. This is especially useful for developers or users who want to quickly share their projects or applications for testing or collaboration purposes.
Key Features of Localtonet:
Tunneling: Localtonet creates a secure tunnel to expose a locally running application to the internet with a publicly accessible URL, allowing remote access.
Secure Access: …
=> Add localtonet.com and localto.net

public_suffix_list.dat
Fixes #2382. Also changed the word "regional .jp suffixes" to "jp geographic type names" for consistency with the existing translation.
Did not use the template because this is not a PSL Inclusion request.
=> Moved JPRS comment to appropriate position

public_suffix_list.dat
- NONE
Please report directly to [support@bubble.io](mailto:support@bubble.io)
--- …
=> add bubbleapps.io and cdn.bubble.io to public_suffix_list.dat

public_suffix_list.dat
Adding `emprende.ve` to the `.ve` block of the ICANN section, as requested and verified by the .ve registry administrator Willians Rincones (wrincones@nic.ve). 
This addition has been confirmed through direct email correspondence with the registry, with maintainer @dnsguru CC'd for verification. 
The change helps facilitate and close #2389 (CC @dexterasperson)
```
From: "Willians Rincones" <wrincones@nic.ve>
Sent: 2/20/25 4:48 PM
Best regards, 
If we are requesting to add the emprende.ve area to the public list of suffixes, because it will be a commercial domain extension in the future in our organization, I am attentive to any information necessary to include undertake.ve in said list. 
Thanks for your prompt response.
```
=> Add `emprende.ve`

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://squareup.com/help/us/en/contact
Block, Inc. (formerly Square, Inc.) is a global technology company focused on financial services and digital payments. We provide tools and services that enable businesses of all sizes to accept payments, manage their operations, and grow their business. The submitter is a security engineer at Block, responsible for maintaining our domain infrastructure and security posture. Our platform provides hosted e-commerce solutions through our square.site service, which allows merchants to create and manage their online stores.
**Organization Website:** https://block.xyz
We are requesting the inclusion of `*.square.site` in the PSL to …
=> Add *.square.site for Block, Inc.

public_suffix_list.dat
- No third-party work arounds.
URL where abuse contact or abuse reporting form can be found: https://zerops.io/abuse
---
(Link: [about …
=> Add *.zerops.app

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://zone.id/l/contact
---
(Link: [about …
=> Add `zone.id` to the list

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://deno.net
---
(Link: [about …
=> add deno.net for Deno

public_suffix_list.dat
We would like to update the contact email for `pro.typeform.com`, which was added in https://github.com/publicsuffix/list/pull/1457. Thank you!
```
dig +short TXT _psl.pro.typeform.com
"https://github.com/publicsuffix/list/pull/2404"
```
=> Update `pro.typeform.com` contact email

public_suffix_list.dat
This PR is created to fix #2406 by adding four new second-level domains under South Korea's .kr TLD: `ai.kr`, `io.kr`, `it.kr`, and `me.kr`.
To quote @Renyu106 from #2406:
> the registry for South Korea’s .kr ccTLD. On March 5, 2025, KISA launched four new second-level domains—`ai.kr`, `io.kr`, `it.kr`, and `me.kr`—the first new additions in 22 years. These domains have been in preparation since 2024 and are now open for public registration.
I've verified these additions through multiple authoritative sources:
1. The Korean Internet & Security Agency (KISA) is the official registry for South Korea's .kr ccTLD according to IANA's database: https://www.iana.org/domains/root/db/kr.html
2. KISA's official registry website (http://www.nic.or.kr/) confirms these new second-level domains on …
=> Add ai.kr, io.kr, it.kr, me.kr

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found:  
https://abuse.eliv.kr (or abuse@eliv.kr)
---
---
PROJECT ELIV is a domain and CDN startup based in South Korea. We collaborate with multiple KRNIC registrars to distribute domains and CDN services to our clients, enabling them to build secure and efficient online environments. 
I am the CTO of PROJECT ELIV, submitting this request to enhance the security and reliability of the domains and subdomains we provide to our customers.
**Organization Website:**  
https://eliv.kr (for customers)  
https://eliv.co.kr (for company use)
PROJECT ELIV plans to provide subdomains under `c01.kr` or `eliv-dns.kr` to customers using our CDN services. Beyond simple CDN offerings, we aim to …
=> Add c01.kr / eliv-dns.kr

public_suffix_list.dat
This PR is adding `inbrowser.link` and `inbrowser.dev` entries next to already existing `dweb.link`.
Both are drop-in replacement for already present `dweb.link` with the main benefit of [CID (hash) verification](https://docs.ipfs.tech/concepts/content-addressing/) happening on end user's machine.
Interplanetary Shipyard is the current entity responsible for maintenance of public good utilities for [IPFS](https://ipfs.tech/) and [Libp2p](https://libp2p.io/) ecosystems (https://docs.ipfs.tech/concepts/public-utilities/)
- MAKE SURE UPDATE THE FOLLOWING LIST WITH YOUR LIMITATIONS! REMOVE …
=> add inbrowser.link and inbrowser.dev

public_suffix_list.dat
https://storacha.network/ ("Contact us" link in footer), also https://web3.storage/ ("Contact us" link in footer)
---
To ensure that …
=> Add storacha.link and w3s.link

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: [psl@windsurf.com](mailto:psl@windsurf.com)
---
(Link: [about …
=> Add windsurf.app and windsurf.build

public_suffix_list.dat
https://www.convex.dev/security
---
---
Convex is a cloud-hosted backend application platform that companies use to build and run full-stack web applications. The platform includes a database, compute engine, authentication, file storage, and more. Developers use Convex to build dynamic apps with real-time data and scalable APIs.
Convex serves both frontend and backend infrastructure on behalf of its customers. The frontend content (such as static sites or web apps) is served via one subdomain pattern, and backend APIs and object storage are served via another. These are isolated from Convex's own corporate sites.
I am an engineer at Convex submitting this request on …
=> Add convex.app and convex.site

public_suffix_list.dat
**Abuse Contact:** security@val.town
---
---
I am Tom MacWright and I represent Val Town, Inc. Val Town is a social website for writing small programs in TypeScript that can power websites and APIs. These programs automatically get subdomains of val.run where user-submitted and controlled code can run.
Organization Website:  https://val.town/
Users' code runs within separate subdomains of web.val.run and val.run. Because their code can be arbitrary TypeScript/JavaScript handlers, they can issue and receive cookies, and we want to ensure that those cookies are fully isolated between different applications. We also issue LetsEncrypt certificates for each wildcard user subdomain. We have previously requested PSL inclusion at #1964: this PR removes one of …
=> Add val.run

public_suffix_list.dat
Abuse contact: mailto:abuse@cloudscale.ch Link this address is available on https://www.cloudscale.ch/
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will …
=> Add objectstorage.ch

public_suffix_list.dat
We will be moving all subdomains across to `localcert.net` as part of our infra rewrite, so we do not intend to renew or keep this domain name.
I'm also updating the email contact.
Last PR was authored by me: #2309
=> remove `localhostcert.net`

public_suffix_list.dat
Merging to reduce size and to use a sole contact method instead. Nothing on the domain itself (like use-case) has been changed.
I've also updated the contact email address.
Last PR was authored by me: #2208
=> merge `Harrison Network` into `William Harrison`

public_suffix_list.dat
This PR proposes the inclusion of biz.gh and net.gh as entries in the Public Suffix List.
biz.gh and net.gh are official second-level domains under the .gh ccTLD for Ghana. The Ghana Domain Name Registry delegates these domains and are commonly used by businesses and network-related entities, respectively.
Ghana Domain Name Registry: https://www.nic.gh/
Example usage: clickmobile.biz.gh, sancfis.net.gh
=> Add biz.gh and net.gh SLD to Public Suffix List

public_suffix_list.dat
This is a removal request for cloud66.zone as it is now redundant. This was raised by https://github.com/publicsuffix/list/pull/797#issuecomment-2887869190
=> removing cloud66.zone as it is redundant now

public_suffix_list.dat
https://abuse.eliv.kr/ (or [domain@abuse.eliv.kr](mailto:domain@abuse.eliv.kr))
--- …
=> Add eliv-cdn.kr

public_suffix_list.dat
Contact email: `domains@dfinity.org`
URL where abuse contact or abuse reporting form can be found: https://dfinity.org/bug-bounty
---
(Link: [about …
=> Add icp0.io /  icp1.io / caffeine.site / caffeine.website for Internet Computer domains

public_suffix_list.dat
Hey there, we are requesting to delist ths .ind.mom suffix from the PSL due to closing of our Registry business. As we are not able to add more suffixes requested by our current registrars. We are not able to make more profit and have lost our invested moneys on premium domains due to not being added on suffix for our future plans.
=> Remove ind.mom from PSL

public_suffix_list.dat
https://openai.com/form/report-content
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding.
(Link: [about …
=> Add *.oaiusercontent.com to the PSL.

public_suffix_list.dat
As the checklist template is tailored to _additions_ to the list, I am not following it as this PR is about a _removal_.
Our original PR was https://github.com/publicsuffix/list/pull/616 in 2018. At that time we handed out subdomains in the form `USER.HOST.uberspace.de` to our users. We ended this practice years ago and moved all user-generated content to subdomains of the separate domain "uber.space" which is already included on the PSL since 2017, so cookie isolation for `*.uberspace.de` is no longer needed.
=> Remove *.uberspace.de

public_suffix_list.dat
__Submitter affirms the following:__  
URL where abuse contact or abuse reporting form can be found:  
https://www.nic.co.de/impressum
Or directly :
contact - registry@kv-gmbh.de
abuse - registry@kv-gmbh.de or abuse@kv-gmbh.de
---
---
KV GmbH is a German-based company operating the second-level domain `co.de`. We provide a commercial subdomain registration service under `*.co.de`, allowing individuals, businesses, and resellers to register third-level domains like `mybrand.co.de`, `johnsmith.co.de`, and so on. This allows meaningful namespace usage without the need for their own top-level domain.
We operate a DNS and domain management infrastructure and are the authoritative registry for this namespace. We provide public delegation, automation, and long-term subdomain …
=> Add co.de to public suffix list

public_suffix_list.dat
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, …
=> Add realtime.supabase.co and storage.supabase.co

public_suffix_list.dat
https://reportsite.walrus.xyz/
---
(Link: [about …
=> Add wal.app

public_suffix_list.dat
- `mydrobo.com` expired for over 2 months
```
Domain Name: MYDROBO.COM
Registry Domain ID: 1070140860_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.networksolutions.com
Registrar URL: http://networksolutions.com
Updated Date: 2025-08-18T08:41:23Z
Creation Date: 2007-07-06T22:13:11Z
Registry Expiry Date: 2025-07-06T22:13:11Z
```
- GitHub mention received no response at https://github.com/publicsuffix/list/pull/84#issuecomment-3198472193
- Unable to reach the initial requestor by email
```
rpadilha@drobo.com
host d220386a.ess.barracudanetworks.com [209.222.82.255]
SMTP error from remote mail server after end of data:
550 permanent failure for one or more recipients (rpadilha@drobo.com:550 5.4.1 Recipient address rejected:
Access denied. For more information see https://aka.ms/EXOSm...)
```
=> Remove `mydrobo.com`

public_suffix_list.dat
Email-Address: abuse@xenoncloud.net
--- …
=> Add xenonconnect.de as public suffix
