publicsuffix/list

public_suffix_list.dat
Please add our DNS entries to the PSL.
I'm able to prove ownership of the domains affected.
Thank you in advance.
=> Add CDN77.com entries to PSL

public_suffix_list.dat
@gerv @weppos @dnsguru - Any objections for me just merging these explicitly each update? Or do you want to review each one of them?
=> Add new gTLDs up to 2015-07-31

public_suffix_list.dat
=> Add new gTLDs up to 2015-08-07

public_suffix_list.dat
Adding umbraco.io and *.umbraco.io to the list for our upcoming Umbraco as a service release
=> Adds umbraco.io domains

public_suffix_list.dat
Reverts publicsuffix/list#32 -- fails tests. Let's work out whether the test is wrong or the patch is wrong, then act accordingly.
=> Revert "Adds umbraco.io domains"

public_suffix_list.dat
// ni : http://www.nic.ni/
com.ni    
gob.ni    
edu.ni
org.ni
nom.ni
net.ni
mil.ni  
co.ni
biz.ni
web.ni    
int.ni
ac.ni
in.ni  
info.ni
=> Add  Nicaragua's SLD

public_suffix_list.dat
I'm on synology.com, where we have a public dynamic dns service with multiple domains.
I had already change these domain name in list to lowercase.
Please feel free to contact me (ronyweng at synology.com) if any need.
Thank you.
=> Add Synology dynamic dns service.

public_suffix_list.dat
I'm adding the mydrobo.com domain that belongs to Drobo.
Please feel free to contact either me (rpadilha at drobo.com) or the CTO (rod at drobo.com) for confirmation.
=> Add Drobo Dynamic DNS service

public_suffix_list.dat
=> Add .CO.CZ suffix

public_suffix_list.dat
This is a trivial change. It closes GH-109 (I decided to keep Submitted instead of Changed, and I normalized all the existing entries).
/cc @gerv or @sleevi for cross-review, just in case I made some error by mistake.
=> Remove date from `Submitted by` label

public_suffix_list.dat
Closes GH-105
/cc @lawells can you please check if it is correct?
=> amazon: Update AWS domains

public_suffix_list.dat
Validated using http://registry.pro/get-pro
> Select third level .PRO domains are also available including:
> law.pro, avocat.pro, bar.pro, recht.pro, jur.pro, cpa.pro,
> aaa.pro, aca.pro, acct.pro, med.pro, eng.pro.
/cc @sherwinflight
---
Closes GH-124
=> pro: Add new suffixes

LICENSE, public_suffix_list.dat, tests/README, tests/prepare_tlds.py, tests/test_psl.txt
Mostly Mozilla and Wikipedia links.
=> Update some HTTP links to HTTPS

public_suffix_list.dat
Feel free to reach out to me at ruibalp@fb.com with any questions.
=> Add apps.fbsbx.com to a new section for Facebook, Inc.

public_suffix_list.dat
Closes GH-159.
@erikvanderpoel since you handled most of GH-159, can you please cross-review it? 
/cc @gerv @sleevi
=> Add co.dk, biz.dk, firm.dk, store.dk, reg.dk

public_suffix_list.dat
Closes GH-181
/cc @sleevi @gerv for cross review
=> Add TLD .xn--e1a4c

public_suffix_list.dat
Hi Eduardo (@sirdarckcat),
This is Scott Wu from Google. I'm working with Han on the 0emm.com stuff.
Could you help to approve the pull request?
Please let me know if there is any problem.
Thank you very much!
Scott Wu
=> Added *.0emm.com to Google's list

public_suffix_list.dat
This PR is submitted on behalf of domain owner Kai Schroeder. 
http://whois.domaintools.com/myfritz.net
You can confirm the request using his mail address linked in the whois information.
Best regards.
=> Add MyFRITZ! DynDNS-Service 'myfritz.net'

public_suffix_list.dat
This is a request add our customer level domains to the suffix list.
Please let me know if/what verification is needed.
=> Add TownNews.com suffixes

public_suffix_list.dat
Hi,
we are setting up an simple provider for free domains (currently we are testing our service, especially dyndns domains).
The sub domains will be available for everybody, so we would like to be on the list. Our background is the support for lets encrypt.
Thanks,
Jan Mönnich
=> For our own free provider

public_suffix_list.dat
=> Add dnshome.de

public_suffix_list.dat
Removed `kesennuma.miyagi.jp`.
=> Update .JP as requested by info@jprs.jp

public_suffix_list.dat
Closes https://github.com/publicsuffix/list/pull/95
=> Add dy.fi dynamic DNS domain

public_suffix_list.dat
Closes https://github.com/publicsuffix/list/pull/108
=> Add e4.cz to E4YOU, spol. s.r.o

public_suffix_list.dat
Closes https://github.com/publicsuffix/list/pull/129
=> Add Freebox domains

public_suffix_list.dat
See http://www.nic.ba/ and
http://nic.ba/users_data/files/pravilnik_o_registraciji.pdf
/cc @gerv @sleevi for cross-review
---
Closes #241
=> Update .BA suffixes

public_suffix_list.dat
As member of Amazon AWS EC2, revising EC2 portion of list to target correct China domain.
=> Correcting error in AWS EC2 China domain

public_suffix_list.dat
For the security and privacy of Shopblocks users, please add this domain to ensure cookie isolation across myshopblocks.com subdomains.
=> Add myshopblocks.com to list

public_suffix_list.dat
fhapp.xyz will soon be hosting arbitrary users' sites.
=> Add fhapp.xyz

public_suffix_list.dat
Contact  admin (at) hepforge.org  for confirmation.
=> Add hepforge.org

public_suffix_list.dat
=> Add a comment on canonical URL

public_suffix_list.dat
2nd attempt.  Rebased to latest master.
=> Add browsersafetymark.io to publicsuffix/list

public_suffix_list.dat
This is Vincent Tseng from ASUSTOR Inc. Please add our DDNS domain name: myasustor.com to public suffix list, thank you.
=> Add ASUSTOR DDNS domain: myasustor.com

public_suffix_list.dat
Fixes the formatting in https://github.com/publicsuffix/list/pull/284
=> Add wmflabs.org

public_suffix_list.dat
This also moves the KRD entries to the PRIVATE section, to facilitate
the script automation.
=> Add new gTLDs up to 2016-08-17

public_suffix_list.dat
Add namespaces for Joyent's Triton Container Name Service.
=> Add Joyent Triton

public_suffix_list.dat
Customer level domains for Cloud CMS - Frontend arbitrary User Content & Backend Administration - Frontend + Backend Cookies - need seperation for security reasons
=> Add Futureweb OG Private Domains

public_suffix_list.dat
fix for https://github.com/publicsuffix/list/pull/310
please let me know if i need to change _psl.keymachine.de TXT record to reauthenticate
Thank you
Best Regards
Martin Dannehl
=> Please add keymachine.de - fix for #310

public_suffix_list.dat
ClouDNS has thousands of customers using the listed domains for dynamic dns
=> Add ClouDNS domains

public_suffix_list.dat
=> Fixed typo

public_suffix_list.dat
> We register domain name directly to .cy (as second level domains)
> only to specific organization
/cc @sleevi @gerv
=> Add .CY suffix as per registry request

public_suffix_list.dat
The SinaAppEngine enabled 2 more domains for it's PaaS service
=> add 2 more domains for SinaAppEngine

public_suffix_list.dat
> The correction is as follows;
>
> please update the "jp" section of PUBLIC SUFFIX LIST.
> (remove "hitoyoshi.kumamoto.jp","kashima.kumamoto.jp")
>
> The attached file is correct.
> Please confirm it.
=> Update .JP suffix as requested

public_suffix_list.dat
Customer level Domains for Cloud CMS - Frontend arbitrary User Content & Backend Administration - Frontend + Backend Cookies - need seperation for security reasons
=> Update Futureweb OG Private Domains

public_suffix_list.dat
=> Remove volgograd.ru from Public Suffix List

public_suffix_list.dat
Hi, 
We would like to add a new domain for Synology DDNS service (refer to #62).
DNS entries for authentication are in place.
Please feel free to contact me (shirobai [at] synology.com) if needed.
Thanks.
=> Add vpnplus.to in the section of Synology, Inc.

public_suffix_list.dat
=> Add sensiosite.cloud

public_suffix_list.dat
Refer to item 5.10.1 of https://www.thnic.co.th/doc/dotthai_policy_pp20110107[draft][en].pdf
=> Update .ไทย domains

public_suffix_list.dat
Pull request for adding hb.cldmail.ru names
=> Pull request for adding hb.cldmail.ru name

public_suffix_list.dat
We use *.definima.net and *.definima.io for our customers projects.
=> Add definima domain suffix

public_suffix_list.dat
I will let you know once the DNS authentication is ready.
=> Adding WeDeploy domains

public_suffix_list.dat
We are a hostingcompany and have a lot of subdomains for the Domains:
+// LCube - Professional hosting e.K. : https://www.lcube-webhosting.de  
+// Submitted by Lars Laehn <info@lcube.de>  
+lcube-server.de  
+svn-repos.de  
+git-repos.de
=> Add lcube-server.de, svn-repos.de, git-repos.de

public_suffix_list.dat
We create a independent webfrontend for every customer at our company. They all have a different Subdomain (in different stages of developement: dev, prod, testing or disrec)
=> Added Thingdusts per-user subdomains

public_suffix_list.dat
to clean up https://github.com/publicsuffix/list/pull/372
=> add CloudAccess.net free domains to Private

public_suffix_list.dat
Adding the Dynu.com domain names to public_suffix_list.dat.
=> Adding Dynu.com domain names to the PSL

public_suffix_list.dat
I reopened https://github.com/publicsuffix/list/pull/470 to have clear explanation of why my pull request isn't merged.
> In addition, owners of privately-registered domains who themselves issue subdomains to mutually-untrusting parties may wish to be added to the PRIVATE section of the list.
We isssue sub-domains to our clients, which can deploy their apps to their subdomains to get benefit of our CI and monitoring service. Regarding you [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) it's correct for me to add that sub-domain into the list. It's the preferable way to secure my clients data from stealing buy another client, am I correct?
=> add *.stage.nodeart.io

public_suffix_list.dat
Pull request for adding org.ru, net.ru and pp.ru names
=> Pull request for adding org.ru, net.ru and pp.ru names

public_suffix_list.dat
We are a web hosting provider allowing our customers to use a custom free subdomain of v-info.info
=> Add v-info.info

public_suffix_list.dat
- PAMPEREDCHEF
- MONTBLANK
- MCD
- MCDONALDS
- CHLOE
See
- https://github.com/whois/ianawhois/commit/3460e5ba37f88f23340e8a163781e66beec4160f
- https://github.com/whois/ianawhois/commit/a62091c9a5bc602a918f70eae20b54d1cad78337
- https://github.com/whois/ianawhois/commit/74a56d2ba980ed47cb0b030f182fa8cf8bcdd550
- https://github.com/whois/ianawhois/commit/ad44f49b33802aa8b3bb44af86093d6f68a7c77f
- https://github.com/whois/ianawhois/commit/30f28d7e951252a974d539a50642986fa9ee588a
=> Delete "REMOVED" TLDs

public_suffix_list.dat
9guacu.br        foz.br      santamaria.br
anani.br         manaus.br   santoandre.br
campinagrande.br maringa.br  saobernardo.br
curitiba.br      riopreto.br saogonca.br
=> .br updated - 12 new 2nd level city domains

public_suffix_list.dat
This is a new 2nd level .br zone. Will be launched tomorrow 20180312
It is already dns delegated and listed at our registry information page.
https://registro.br/dominio/categoria.html
=> .br updated - one new city domain barueri.br

public_suffix_list.dat
Users may create an arbitrary amount of subdomains for off of this one.
=> add azurecontainer.io

public_suffix_list.dat
Re-submitting, following internal issues making the DNS Authentication changes.
=> lug.org.uk

public_suffix_list.dat
Hi,
I change type of company (GmbH now) and added own.pm, now at the correct place
=> Adding own.pm

public_suffix_list.dat
=> Add additional Lukanet Ltd domains

public_suffix_list.dat
My website https://zone.id is a subdomain provider, which let someone to register a subdomain and park it to their website / blog.
I am worrying about cookie stealing throug XSS (Cross Site scripting) or other method.
Please help me.
=> Add zone.id

public_suffix_list.dat
Will create DNS record _psl.linkitools.space pointing to this PR.
=> Add linkitools.space to psl

public_suffix_list.dat
=> Update gu ccTLD suffixes

public_suffix_list.dat
They have been deleted.
https://github.com/whois/ianawhois/commit/08676fbcc66514dca907939549fe523919378bf1
https://github.com/whois/ianawhois/commit/b237a1ca2676c44ecddc360d89420c503446c9d5
=> Remove MEO and SAPO

public_suffix_list.dat
updating Kuwait's ccTLD (.kw)
Email verification can be done via IANA DB or dig
=> Update Kuwait's ccTLD (.kw)

public_suffix_list.dat
See https://github.com/whois/ianawhois/commit/f1f2df42d7f1f48fa78c31bc4d55cdb54fa7c896
=> Remove XPERIA

public_suffix_list.dat
BNNIC has recently allowed .bn registration. Updating the list to remove wildcard (*.bn)
=> Updated .bn ccTLD. Removed wildcard.

public_suffix_list.dat
This new second level domain will be launched 20180927
=> New ong.br 2nd level domain

public_suffix_list.dat
- https://github.com/whois/ianawhois/commit/72fe756a8c0120fbf1094a7aa7c249fb969c6106
- https://github.com/whois/ianawhois/commit/bbffbf5e46ed4eeb9dc7d48c4cfec539ecf6fd71
- https://github.com/whois/ianawhois/commit/3070dbef9e2ceaafb10a1ea9ce3df11b57add860
- https://github.com/whois/ianawhois/commit/f41dd2563a814671b1b75e51e16610000a577c5c
- https://github.com/whois/ianawhois/commit/f1e4043e233524d9daefbe46685a521dfe2dac93
=> Remove deleted TLDs

public_suffix_list.dat
Description of Organization and Reason for PSL Inclusion
====
Organization Website: https://www.dotarai.com
DotArai operate registry system for shop.th and online.th https://domain.online.th/
The purpose for online.th and shop.th is to increase business opportunities for Thai SMEs.
Through digital tools By providing domain name services under the name online.th and shop.th.
We also want to drive the growth of social organizations.
And it's a part of giving a small chance to the prospect we will donate 50% without deducting expenses to the Foundation or organizations selected in Thailand.
=======
dig +short TXT _psl.online.th
`"https://github.com/publicsuffix/list/pull/716"`
and
dig +short TXT _psl.shop.th
`"https://github.com/publicsuffix/list/pull/716"`
make test …
=> Add shop.th & online.th

public_suffix_list.dat
=> Remove trailing whitespace from L11948

public_suffix_list.dat
both *.run.app and *.a.run.app will run user code
=> Add run.app and a.run.app to the psl

public_suffix_list.dat
====
Filegear Inc. provides personal cloud devices to our customers. They can use this device to organize their files, photos, music, and videos automatically. And they can access these files from anywhere, and share with anyone.
Organization Website: https://www.filegear.com
====
We already use filegear.me for our customer's devices. Each of these device has a sub-domain name that is generated dynamically during device initialization and registration, e.g. vxnaowas.filegear.me.
As we are expanding our business overseas, we have customers from different regions. We would like to have regional domain names for devices at different regions, e.g. vxnaowas.filegear-jp.me for a device in Japan. Therefore, we could provide better performance …
=> Add regional domain for filegear.me

public_suffix_list.dat
Hello,
Jonathan Foote from the Fastly security team here, adding another PSL entry for the organization. 
Update: A verification DNS record has been published, this PR should be ready for review.
Thanks,
Jon
====
Organization Website: [www.fastly.com](https://www.fastly.com)
Fastly’s global edge cloud platform processes, serves, and secures applications for users. See [www.fastly.com](https://www.fastly.com) for more information.
====
User (third-party) content is served from subdomains of fastly-terrarium.com. Adding this domain to the PSL will stymie cookie stuffing attacks across these subdomains.
=======
We've published a verification DNS record
```
$ dig +short TXT _psl.fastly-terrarium.com …
```
=> Add fastly-terrarium.com

public_suffix_list.dat
====
Organization Website: hthttps://www.zitcom.dk
Zitcom A/S is a hosting and cloud provider.
====
site.builder.nu is used for our site builder product. Each customer is assigned a subdomain on *.site.builder.nu -like [randomstring].site.builder.nu.
Customer sites should not be able to share cookies and the URL should be displayed correctly in browsers, and for that reason site.builder.nu should be added to the list.
=======
Done:
```
dig +short TXT _psl.site.builder.nu
"https://github.com/publicsuffix/list/pull/723"
```
make test
=========
``` …
```
=> Add site.builder.nu

public_suffix_list.dat
====
Organization Website: https://www.cloudflare.com/
Cloudflare recently announced workers.dev ([blog post](https://blog.cloudflare.com/announcing-workers-dev/)) as a way to easily deploy serverless applications running on [Cloudflare Workers](https://www.cloudflare.com/products/cloudflare-workers/). More information on the project is also available at the [workers.dev](https://workers.dev/) homepage.
I am an engineer on the Workers team at Cloudflare. For this PR, we setup an email alias (publicsuffixlist@cloudflare.com) that can be used to contact the relevant employees at Cloudflare.
====
Cloudflare customers will given a subdomain of `workers.dev` to which they can deploy their serverless applications. Because subdomains are each …
=> Add workers.dev

public_suffix_list.dat
====
Organization Website:  https://www.discourse.org/ 
I'm an engineer at _Civilized Discourse Construction Kit, Inc._ and we build an open source community platform for civilized discussion on the web at https://github.com/discourse/discourse/. 
We host free discussion forums for open source organizations under the `discourse.group` domain.
Read more here: https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/
====
As we host multiple forums under the `discourse.group` domain we'd like to add it to the PSL to:
1. Ensure that each subdomain of discourse.group is treated as a distinct domain.
2. Adding cookie security.
=======
```
⇒ dig TXT _psl.discourse.group +short …
```
=> Add discourse.group for Civilized Discourse Construction Kit, Inc.

public_suffix_list.dat
====
Organization Website: https://banzaicloud.com
Banzai Cloud provide a free cloud agnostic service to simplify manage kubernetes clusters and workloads.
====
We would like to enable our users to manage their subdomain like {orgname}.beta.banzaicloud.io
We would like all of our domain names to be compliant, including cookie handling, DNS sorting, and Let's Encrypt cert issuance
=======
```
dig +short TXT _psl.app.banzaicloud.io
"https://github.com/publicsuffix/list/pull/730"
```
make test
=========
Test result:
https://gist.github.com/kozmagabor/0d0fbf188602f2c030d33cd6e8eaab5e
=> Add app.banzaicloud.io

public_suffix_list.dat
====
.br Registry
Organization Website: https://registro.br
====
New SLD - tc.br
=======
Already delegated from .br delegated servers
Already listed at sld ref page
https://registro.br/dominio/categorias/
```
dig @a.dns.br tc.br ns +norec +multi
; <<>> DiG 9.11.3-1ubuntu1.7-Ubuntu <<>> @a.dns.br tc.br ns +norec +multi
; (2 servers found)
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27477
;; flags: qr aa; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;tc.br.			IN NS
;; ANSWER SECTION:
tc.br.			172800 IN NS a.dns.br.
tc.br.			172800 IN NS b.dns.br.
tc.br.			172800 IN NS c.dns.br.
tc.br. …
```
=> Br 201904 update

public_suffix_list.dat
====
Organization Website: https://nctu.me
NCTU.ME is a subdomain service aiming to make a simple, free, and fast domain service for Taiwanese.
We provide nctu.me subdomain to our users. They can easily manage DNS and setup dynamic dns. We have 2700 users, 3300 domains, and 4700 records.
====
We allow users create subdomains under nctu.me, i.e. oj.nctu.me, id.nctu.me, etc. We would like to isolate cookies and also be able to use Let's Encrypt for our customer's subdomains.
=======
```
> dig +short TXT _psl.nctu.me
"https://github.com/publicsuffix/list/pull/746"
```
make test
=========
``` …
```
=> Add nctu.me

public_suffix_list.dat
Added domains caa.li, conf.se, fin.ci, free.hr, ua.rs, aero.al, pro.bj, fin.bj
====
Hakaran group is medium-size web/vps/server hosting provider in EMEA region.
====
Hakaran group have many clients who need valid hostname for their application, who need dyn-dns service for their dynamic IP address. We want open registration on this domains for everyone who want short URL of your services what havent got domain or want use free-of-charge dyn-dns service.
Secondary, we want for our users open options for use (sub)domains on services as cloudflare, where is need detect is as separate domain, not only subdomain.
=======
```
"https://github.com/publicsuffix/list/pull/733" …
```
=> Add Hakaran domains [caa.li | conf.se | fin.ci | free.hr | ua.rs | aero.al | pro.bj | fin.bj]

public_suffix_list.dat
====
Organization Website: https://voorloper.com
I'm Nathan van Bakel and work at Voorloper.com. We create and host all sorts of sites and applications.
We'd like to use the voorloper.cloud domain to host websites.
We’d like to give clients a [clientapp].voorloper.cloud domain. Those domains shouldn’t be able to read cookies from other *.voorloper.cloud domains.
====
* Cookie Security
=======
```
dig +short TXT _psl.voorloper.cloud
"https://github.com/publicsuffix/list/pull/750"
```
make test
=========
I've ran the test.
=> Add voorloper.cloud

public_suffix_list.dat
====
Organization Website: https://www.stackhero.io
Stackhero is a PAAS, hosting and managing cloud services.
====
We provide a default domain for our clients' services in the format xxxxxx.stackhero-network.com and would like to declare stackhero-network.com as a public suffix.
The goal is mainly to increase security by isolating cookies.
=======
I'm waiting to get the PR id to add the DNS entry.
make test
=========
Test result is ok
=> Add Stackhero domain: stackhero-network.com

public_suffix_list.dat
====
Organization Website: http://www.icilalune.com
We develop & host web applications for our customers.
====
We host our customer projects on our own clusters using the following name scheme : 
``<project-name>.<cluster-id>.moonscale.io``. Thus we want that each customer-allocated DNS under ``moonscale.io`` is considered separate, security-wise.
=======
````
$ dig +short -t txt _psl.moonscale.io
"https://github.com/publicsuffix/list/pull/757"
````
make test
=========
``make test`` ran successfully with the proposed change.
=> Add *.moonscale.io

public_suffix_list.dat
====
ECG Robotics, Inc. is a 501(c)(3) nonprofit operating several high school FIRST Robotics teams. As a service to other such organizations/schools/teams, we are operating a free hosting service for other FIRST Robotics teams. We currently have ten teams with websites hosted on our service, and we are looking to grow this number to take full advantage of our grant to operate this service.
Organization Website: https://ecgrobotics.org
Contact Email: frc1533@ecgrobotics.org
I am the student responsible for managing this project, and I am the owner of the domain in question.
====
Our primary reason is for security as the project grows. We purchased this domain specifically to shift untrusted user-generated websites into a dedicated zone …
=> Add onred.one

public_suffix_list.dat
====
Organization Website: https://hostbip.com
I am Atanunu Igbunuroghene, a representative of HostBip  - a PaaS, Hosting Provider and Private Domain Name Registry - our service is offered to individuals/businesses to enable them create second-level domain under our domain names (companyname.ltd.ng) and to clients using our cloud hosted applications (msgmakurdi.col.ng).
====
This request is seeking to add these to the PSL so the individuals / institutions operating under these suffixes can gain access to services such as Let's Encrypt, Cloudflare and that other third party systems may better be able to identify the level at which the personal/private name has been registered.
=======
```
dig +short TXT …
```
=> Add Hostbip Registry Domains

public_suffix_list.dat
====
Organization Website:  https://www.loginline.com/
I'm Rémi Mach, CEO & Computer scientist at Log'in Line. We are a service company, software publishers (SaaS), research and development lab, and training agency. We target technical excellence & profound expertises in computer engineering & sciences.
====
- We are providing self-services development environments & PaaS to our customers and employees and need cookie isolation on them, with no LE issuance risks (.dev, .services, .app)
- Also, [Gitlab recommands](https://docs.gitlab.com/ee/administration/pages/) the uses of Public Suffixes for their Pages component as we are opening our Gitlab to external customers. (.io, site)
- Future ability to use tools empowering PSL, and exploit …
=> Add loginline (.app, .dev, .io, .services, .site)

public_suffix_list.dat
====
Organization Website: https://kaashosting.nl
KaasHosting in a hosting provider for mainly games servers. 
====
kaas.gg and khplay.nl can be used by any of our customers to host their own code. 
=======
```
dig +short TXT _psl.kaas.gg
"https://github.com/publicsuffix/list/pull/801"
```
```
dig +short TXT _psl.khplay.nl
"https://github.com/publicsuffix/list/pull/801"
```
make test
=========
=> Add KaasHosting

public_suffix_list.dat
====
Organization Website: https://www.srcf.net/
I am a volunteer system administrator at the Student-Run Computing Facility, a student group providing networked computing services to staff and students of the University of Cambridge, including web hosting on per-user subdomains.
====
Individuals and student groups ('societies', or 'socs' for short) can host websites at domains of the form `<username>.user.srcf.net` or `<shortname>.soc.srcf.net` respectively.  At the time of writing, over 1000 such websites are active in our shared hosting setup.
These are totally separate websites, many of which will be handling user authentication and other sensitive information using session cookies, so browser-level enforced isolation of these sites …
=> Add SRCF user domains: soc.srcf.net, user.srcf.net

public_suffix_list.dat
====
Myself providing a domain name service for Finns sharing the same family name.
====
Subdomains are controlled by different individuals, so they should be treated as separate domains for cookie purposes.
=======
```
dig +short TXT _psl.xn--hkkinen-5wa.fi
"https://github.com/publicsuffix/list/pull/804"
```
make test
=========
I ran the test and it completed successfully.
=> Add häkkinen.fi

public_suffix_list.dat
====
Waffle Computer makes OS for home servers.
Organization Website: https://docs.waffleinfo.com
====
wafflecell.com can be used by customers who has their own severs at home.
The individual user needs cookie security, Javascript security and  Let's Encrypt .
=======
```
dig +short TXT _psl.wafflecell.com
"https://github.com/publicsuffix/list/pull/805"
```
make test
=========
Successfully completed.
=> Add wafflecell.com

public_suffix_list.dat
====
Organization Website: https://www.gentlent.com
I am a director and engineer at Gentlent, which is a brand new software development and consulting company.
====
We want to provide "lab.ms" domains for our upcoming PaaS hosting aswell as for DynDNS soon. Users should be able to only set cookies on their .lab.ms domain and browsers should recognize the domains with the suffix being lab.ms.
=======
The verification of the TXT record was successful:
```
dig +short TXT _psl.lab.ms
"https://github.com/publicsuffix/list/pull/807"
```
make test
=========
We run the "make test" successfully. The output may be viewed at https://gist.github.com/tomkln/8e54f5fcb44fcf3d34ca303790b5255a.
=> Add lab.ms

public_suffix_list.dat
Checklist
====
====
Organization Website: http://co.bn
I am Zulfais, founder of Positive Codes Technology Company (Brunei), providing digital identity and online presence services mostly for local micro and small enterprises.
====
The reason for this PSL inclusion is to be able to add .co.bn subdomains into Cloudflare service and maximizing its potential features.
Domain WHOIS
====
The WHOIS detail for the domain can be retrive from https://bnnic.bn/whois
=======
DNS Verification of the domain is as follow:
```
dig +short TXT _psl.co.bn
"https://github.com/publicsuffix/list/pull/789"
```
https://www.whatsmydns.net/#TXT/_psl.co.bn
Syntax Checker (make test)
=========
The output is available at …
=> Add co.bn as Private Domain

public_suffix_list.dat
Update `.rw`, as documented in https://github.com/publicsuffix/list/issues/819
=> Update .rw domains per ccTLD

public_suffix_list.dat
====
Organization Website: https://king.host
KingHost is one of largest web hosting providers in Brazil. We provide shared and dedicated hosting on PaaS model.
I am [Felipe Braz](https://github.com/fbraz3), infraestructure engineer at KingHost.
====
We provide a free domain under kinghost.net, uni5.net, kinghost.com.br or king.host for customers who dont have (or dont want to) register a common domain. We need to be listed because this will prevent super cookie violation on our domains and isolate each subdomain from the others in the same namespace. We also will provide Let`s Encrypt certificate for each user.
=======
```
dig TXT _psl.kinghost.com.br +short
"https://github.com/publicsuffix/list/pull/827"
``` …
=> Add king.host domains

public_suffix_list.dat
====
Organization Website: https://qualifio.com
Qualifio provides a data collection / audience engagement platform, we provide specific domain to clients, as subdomain of qualifioapp.com
====
The main goal is Cookie and other storage separation.
=======
dig TXT _psl.qualifioapp.com @c.dns.gandi.net +short
"https://github.com/publicsuffix/list/pull/840"
make test
=========
=> Created record for qualifio

public_suffix_list.dat
**Description of Organization**
I'm an individual running a (no profit / no money) dynamic-DNS service geared towards on-premises devices.
**Organization Website**: https://www.pubtls.org/
**Reason for PSL Inclusion**
I am mostly concerned about cookie security; I don't want users to be able to set pubtls.org cookies. 
**DNS Verification via dig**
```
$ dig +short TXT _psl.pubtls.org
"https://github.com/publicsuffix/list/pull/839"
```
I have ran `make test` and it passes.
=> Add pubtls.org

public_suffix_list.dat
====
Organization Website: https://www.shopitcommerce.com/
Shopit provides a GCP based ecommerce platform
====
Subdomains are given to users, so the domain should be added for Cookie Security
=======
```
dig +short TXT _psl.shopitsite.com
"https://github.com/publicsuffix/list/pull/838"
```
make test
=========
```
```
=> Add shopitsite.com

public_suffix_list.dat
====
Organization Website:  https://nymnom.com/
'NymNom' is a 'PDNR' (Private Domain Name Registry), allowing 3rd parties to register domain names in a variety of domain name extensions / suffixes.
====
'NymNom' has an existing section in the 'Public Suffix List', and is updating it's section to include additional domain extensions / suffixes in it's portfolio.
Inclusion is required for cookie security, 'Let's Encrypt' issuance, et al.
=======
This section is complete.
```
dig +short TXT _psl.nym.ec "https://github.com/publicsuffix/list/pull/771"
```
```
dig +short TXT _psl.nym.hk "https://github.com/publicsuffix/list/pull/771"
```
make test
=========
Test has been run, and all is correct.
No conflicts reported …
=> Update nymnom section

public_suffix_list.dat
====
Organization Website: http://www.aseinet.com/
I serve a free subdomain service, DDNS service and Hosting service as an individual.
Using my Free subdomain service, users can open a website without fee-charging domain.
If ISP does not provide static IP address, users can also use my DDNS service to install their server at home or office without additional cost to get static IP.
And, I serve free Linux VPS to high school or less students for learning purpose.
====
It is very important that the browser correctly recognizes the subdomain I provide.
I want to these services to be recognized as a known public domain.
=======
```
dig +short TXT _psl.user.aseinet.ne.jp …
```
=> Add our Hosting service and Free domain service

public_suffix_list.dat
====
Organization Website: https://cloud.yandex
I am Alexander Lodin from Yandex security team.
Yandex.Cloud is a platform for developing and deploying cloud applications.
====
As a part of a service, we provide data storage for our customers, that can be used to deviler content and to host simple static websites (similar to AWS S3).
Here is the list of locations available for our customers to host there own content:
```
https://storage.yandexcloud.net/<bucket_name>/**
https://<bucket_name>.website.yandexcloud.net/**
```
=======
```
$ grep yandexcloud.net ./public_suffix_list.dat | xargs -I '{}' sh -c 'printf "%s~%s\n" {} $(dig +short TXT _psl.{})' | column -t -s'~'
yandexcloud.net …
```
=> Add Yandex.Cloud section and Yandex object storage domains

public_suffix_list.dat
Domain is no longer accessible (expired).
===
You can remove from the list.
Thankyou.
.
====
====
=======
make test
=========
=> Remove zone.id from list

public_suffix_list.dat
====
Organization Website: https://pepabo.com, https://mc.lolipop.jp
`LOLIPOP! Managed Cloud` is a Web Hosting service, provides by GMO Pepabo, inc.
For more information about `LOLIPOP! Managed Cloud` head over to [our website](https://mc.lolipop.jp/)
====
We provide every app/website on `LOLIPOP! Managed Cloud` with its own lolipop.io subdomain.
We'd like to be included in the list to improve our cookie security.
=======
```console
$ dig txt +short _psl.lolipop.io
"https://github.com/publicsuffix/list/pull/881"
```
make test
=========
✅ https://travis-ci.org/publicsuffix/list/builds/585872579
=> Add lolipop.io

public_suffix_list.dat
See https://github.com/whois/ianawhois/commit/7be96d8511497505df65cf9177fc76bb40d5ca82
=> Add xn--mgbah1a3hjkrd (موريتانيا)

public_suffix_list.dat
In addition to .so, .edu.so, .com.so, .gov.so, .net.so, and .org.so, the .SO ccTLD also supports ~~.sch.so for schools,~~ .me.so for individuals ~~and .gm.so, .hs.so, .jl.so, .pl.so, and .sw.so for federal member state administrations~~. I have updated the suffix list to reflect this.
====
.so is the ccTLD of the Republic of Somalia. The PSL already partially supports the .so TLD but there are many missing TLD which I added.
Organization Website: http://sonic.so
====
I am not affiliated with the .so entity, I am sending this pull request because I run an accredited .so registrar and this PR would help many other registrars who sell the .so TLD.
=======
N/A
make test
=========
All the tests are passing.
=> Update .so suffix list

public_suffix_list.dat
====
Oracle Cloud Infrastructure (OCI)
OCI Website: https://docs.cloud.oracle.com/iaas/Content/GSG/Concepts/baremetalintro.htm
OCI Documentation: https://docs.cloud.oracle.com/iaas/Content/GSG/Concepts/baremetalintro.htm
====
Customer-oci.com is for customer use when using the Oracle Cloud Infrastructure platform. This domain is used for customers generating DNS endpoints for hosting customer provided code. This includes the parent domain customer-oci.com. as well as three children where cookies should be prevented below: oci.customer-oci.com., ocp.customer-oci.com. and ocs.customer-oci.com..
=======
```
gdrake@gdrake-mbpr:~$ dig +noall +answer +norecurse TXT _psl.customer-oci.com @ns1.p68.dns.oraclecloud.net …
```
=> Add_customer-oci.com

public_suffix_list.dat
====
Organization Website: https://oursky.com/, https://www.skygear.io/
`Skygear` is a serverless platform for modern app development. We allow users to deploy their application in our cloud service.
====
We allow users to deploy their application and hosted on subdomain of `skygearapp.com`. We would like to add `skygearapp.com` to the public suffix list for better cookie security.
=======
```sh
$ dig txt +short _psl.skygearapp.com
"https://github.com/publicsuffix/list/pull/892"
```
make test
=========
Pass: https://travis-ci.org/publicsuffix/list/builds/596025611
=> Add skygearapp.com

public_suffix_list.dat
====
Perspecta is a corporation in Northern Virginia, USA that has recently acquired KnightPoint Systems, LLC.  As such, Perspecta has taken ownership of the KnightPoint Systems cloud enclave.
Organization Website: https://perspecta.com/
====
Perspecta recently acquired KnightPoint Systems (which utilized knightpoint.systems already on the PSL).  As such, we are migrating from knightpoint.systems to perspecta.cloud.  Our primary reason for PSL inclusion for both the prior and new domain is "cookie security".
=======
`lancelot:~ kvanals$ dig +short TXT _psl.perspecta.cloud`
`"https://github.com/publicsuffix/list/pull/898"`
make test
=========
See:  https://pastebin.com/krfngLeA
=> Add perspecta.cloud

public_suffix_list.dat
Add Group 53, LLC
====
Organization Website:  https://www.group53.com
Group 53, LLC, is the owner and operator of the Nova53 Anycast DNS platform. We are adding domains that are members of DDNS services to the list to avoid any issues with users of these domains. 
====
Users on the nsupdate.info platform that have subdomains on our zones are experiencing issues with web browsers detecting their sites improperly.
=======
```
dig +short TXT _psl.awsmppl.com
"https://github.com/publicsuffix/list/pull/900"
```
make test
=========
https://travis-ci.org/publicsuffix/list/builds/601073843
=> Add Group 53, LLC Domains

public_suffix_list.dat
====
Organization Website: https://kuroku.ltd/, https://oya.to/
[oyato cloud (oya.to)](https://oya.to/) is a website optimizing proxy service and a division of [KUROKU LTD](https://kuroku.ltd/) &mdash; I'm the owner.
====
Members of oyato cloud may create custom sites using .oya.to subdomains and we'd like to improve their cookie security.
=======
```
dig txt +short _psl.oya.to
"https://github.com/publicsuffix/list/pull/908"
```
make test
=========
https://travis-ci.org/publicsuffix/list/builds/605906510
=> Add oya.to

public_suffix_list.dat
====
Organization Website: https://www.amsterdamwireless.nl/
Amsterdam Wireless is a community wireless mesh network in Amsterdam. I am the volunteer DNS administrator.
====
Members of Amsterdam Wireless can register their own domain names under amsw.nl for use in the mesh network. These members do not necessarily trust each other. We would like to offer them all the benefits of the Public Suffix List, including better cookie security, domain highlighting, proper searching in the browser history, correct rate limiting by Let's Encrypt and the possibility to apply relaxed DMARC alignment based on the organization domain (which, in this case, would be the member's subdomain).
It should be noted that it is not our intention to merely …
=> Add amsw.nl private domain to PSL

public_suffix_list.dat
====
Organization Website: https://en-root.org/
I am an individual, initiator of an informal non-profit organization called _En root‽_, whose aim is to provide tools for people working on _digital democracy_ and the French Parliament. Currently our collective works on storing each French laws and bills in Git repositories.
We provide some infrastructure to our members (forum, chat, etc) and we are currently adding a new service, a GitLab-based forge https://git.en-root.org.
====
Our GitLab forge provides a GitLab Pages module using the en-root.fr domain. And he [GitLab Pages documentation](https://docs.gitlab.com/12.4/ee/administration/pages/#add-the-domain-to-the-public-suffix-list) states that we should add en-root.fr to the Public …
=> Add en-root.fr domain

public_suffix_list.dat
====
Organization Website: https://observablehq.com
I am Mike Bostock and I represent Observable, Inc. Observable is a collaborative JavaScript notebook for data visualization. We provide a hosted interactive programming environment and publishing platform. Users author notebooks by writing JavaScript.
====
Users’ notebooks run on observableusercontent.com in a sandboxed iframe. Each user has their own subdomain (e.g., mbostock.static.observableusercontent.com). Each user’s origin should be isolated; we want users’ cookies (if any) to be isolated.
=======
```
dig +short TXT _psl.observableusercontent.com
"https://github.com/publicsuffix/list/pull/914"
```
make test
=========
``` …
```
=> Add Observable domain: observableusercontent.com.

public_suffix_list.dat
====
Organization Website: https://www.quickbackend.com
QuickBackend is a FaaS (Function as a Service) platform. It makes easier for the developers to create simple backends for websites and apps.
QuickBackend is a product developed by PyMET software development company (https://www.pymet.com)
====
The subdomains under the qbuser.com domain are assigned to different customers. They can use the assigned subdomain to access their backends. 
We want to protect the user-created subdomains under qbuser.com from cross-subdomain cookie/state sharing.
It would also make us easier generate Let's Encrypt SSL certificates for the custom subdomains.
=======
```
dig +short TXT _psl.qbuser.com …
```
=> Add qbuser.com domain

public_suffix_list.dat
Registry .fj provided direct list of stub zones after being informed by CA that registry could not apply for SSL due to presence of *.fj for pending upgrade to registry system
The registry also supplied the explicit list of direct zones
fj
ac.fj
biz.fj
com.fj
gov.fj
info.fj
mil.fj
name.fj 
net.fj
org.fj
pro.fj
====
Organization Website: https://domains.fj
====
Already listed, this is the ccTLD for Fiji, replacing the *.fj listing with the list of tld and direct sld stubs within .fj, furnished from the registry operator
=======
_psl TXT records returning pull request ID correctly and verified 
make test
=========
Tested ok
=> Update fj entry

public_suffix_list.dat
@jbg commented this was missing in [issue report 936 ](https://github.com/publicsuffix/list/issues/936)
The ccTLD string is in the root and listed with IANA but missing in this list.
This PR adds the Greek .EU IDN and adds the URL of EURID for it, as well as adding the URL for the Cyrillic IDN in the line above it.
====
EURID are the registry for .eu as well as the Cyrillic and Greek IDN versions 
Organization Website: https://eurid.eu
This is being submitted on their behalf to include the Greek IDN, which was recently introduced to the root
====
TLD is in root but missing from PSL, as reported by @jbg in [Issue Report 936](https://github.com/publicsuffix/list/issues/936)
IDN ccTLDs are not caught within current automation that supports …
=> Update .eu IDNs to add Greek and URL for Cyrillic

public_suffix_list.dat
This is an update of the existing NymNom section.
This updates -
a) contact details (as per format)
b) adds new suffix to NymNom section
Thank you for your time,
====
Organization Website: nymnom.com
====
This is an update of the existing NymNom section.
This updates -
a) contact details (as per format)
b) adds new suffixes to NymNom section
Thank you for your time,
=======
THIS IS CORRECT -
RESOLVES TO -
dig +short TXT _psl.nom.bz
"https://github.com/publicsuffix/list/pull/940"
dig +short TXT _psl.nom.lv
"https://github.com/publicsuffix/list/pull/940"
make test
=========
THIS IS CORRECT - NO ERRORS DETECTED
=> Update public_suffix_list.dat - Existing Section

public_suffix_list.dat
====
Back-end registry services provider for .aero registry
====
It used to be a official registry sub-zone, but has since been deprecated
=======
dig TXT _psl.freight.aero
make test
=========
=>  removal of freight.aero

public_suffix_list.dat
====
Organization Website: https://www.oshean.org 
OSHEAN, Inc. is an ISP with Managed DNS services.
Reason for PSL EXCLUDE
====
OSHEAN is migrating to a New Managed DNS service provider and this domain needs to be excluded from the list in order to migrate it.
=======
```
dig +short TXT _psl.k12.ri.us
"https://github.com/publicsuffix/list/pull/923"
```
make test
====================================
=> Update public_suffix_list.dat (k12.ri.us)

README.md
They're already here... let's get that wiki in their face in addition to the publicsuffix.org website URL
=> Added Wiki Link as info resource

public_suffix_list.dat
ac.at-Registry <https://www.nic.aco.net/> has also a subdomain for Dormitories: sth.ac.at 
see: <https://www.aco.net/domain.html?L=1>
====
Organization Website: <https://www.aco.net/domain.html?L=1>
====
We got a User Request regrading:  Cookie Security
=======
```
dig sth.ac.at txt +short
"subdomain for student hostels in Austria"
"Studentenheime - Dormitories"
```
make test
=========
``` …
```
=> adding sth.ac.at

public_suffix_list.dat
====
Organization Website: https://curv-labs.de/
We are a Small Startup from Germany.
We develop websites mainly in node and also some with Wordpress.
====
All customers get their own subdomain like company.curv.dev, they should not allow to access the main curv.dev cookies.
As we also host Wordpress on curv.dev subdomains, it is not hard for customers to upload their own plugin which then could steal cookies.
=======
```
dig +short TXT _psl.curv.dev
"https://github.com/publicsuffix/list/pull/968"
```
make test
=========
Passed, no errors.
=> Add curv.dev to public_suffix_list.dat

public_suffix_list.dat
====
Organization Website: https://www.fabrica.dev/
Fabrica is a no-code app builder, i.e. an online tool that allows users to create web apps using a point-and-click interface.
====
Fabrica hosts its user's apps on the domain onfabrica.com, so a user who makes an app called "Example" may have "example.onfabrica.com" as their app's domain. Since apps can contain arbitrary code, and since *.onfabrica.com apps are created by various different users, it would be good for cookie security, domain validation with third-party APIs, etc. for "onfabrica.com" to be on the PSL.
=======
```
$ dig +short TXT _psl.onfabrica.com
"https://github.com/publicsuffix/list/pull/999"
```
make test
=========
Yes, test ran without …
=> Add Fabrica apps domain: onfabrica.com

public_suffix_list.dat
====
Mintere is a digital marketing company. We've launched a CMS for our users.
Organization Website: https://mintere.com/
====
Users will be able to go to mintere.com, create a site and receive a *.mintere.site subdomain where they can place arbitrary content.
We'd like to be included in the list to improve our cookie security.
=======
```
dig +short TXT _psl.mintere.site
"https://github.com/publicsuffix/list/pull/993"
```
make test
=========
✅
=> Add mintere.site

public_suffix_list.dat
====
Organization Website: https://fly.io
I'm an engineer at fly.io, a commercial company that hosts customer application servers close to users.
====
We have several shared suffixes customers users for previewing their applications. They all use Lets Encrypt certificates, and none of them should share cookies.
=======
```
dig +short TXT _psl.fly.dev
"https://github.com/publicsuffix/list/pull/1015"
```
```
dig +short TXT _psl.shw.io 
"https://github.com/publicsuffix/list/pull/1015"
```
```
dig +short TXT _psl.edgeapp.net
"https://github.com/publicsuffix/list/pull/1015"
```
make test
=========
``` …
```
=> Add fly.io public app domains

public_suffix_list.dat
====
611 coin is a blockchain cryptocurrency featuring an included domain name system.
Published objects are accessible globally with #YourDomainObjectName#.611.to.
Organization Website: https://611project.org
====
611 coin cryptocurrency allows publishing blockchain information using subdomain objects of 611.to.
For Cookie Security, Let's Encrypt or alternate related certificate issuance and other security-related aspects 611.to should be listed in the PSL.
=======
```
$ dig +short TXT _psl.611.to.
"https://github.com/publicsuffix/list/pull/1037"
```
make test
=========
Test suite passed with no failures.
``` …
```
=> Add 611.to, Blockchain Domain Name System

public_suffix_list.dat
Jelastic is a Multi-Cloud PaaS (Platform as a Service) with decentralized network of independent cloud hosting service providers located across the Globe.
**Organization Website**: https://jelastic.com
Security enhancement between the subdomains.
There is a large network of independent and distributed cloud hosting providers that offer shared domains for their end users, for example _*.hidora.com_. End users can get a custom subdomain on top of the shared public domain, for example _myapp.hidora.com_. Such subdomains are managed by different users or organisations with the ability to set cookies and they may create an arbitrary amount of subdomains. We would like all of the public domain names to be compliant, including cookie handling and DNS sorting.
Similar accepted cases: …
=> Jelastic public domains are added

public_suffix_list.dat
====
Gitplac.si is a privately owner self hosted Gitlab instance open to public. The domain and server hardware are owned and controlled only by me ( Aljaz S. <me@aljaxus.eu>)
https://gitplac.si
====
Cookie Security
=======
make test
=========
I have run the test, which was successful
```
```
https://hastebin.app/5e90cf1fabcdc0001dd459c8
=> Add gitpage.si to private domains section

public_suffix_list.dat
====
Organization Website: http://minion.systems
web dev freelancer, hosting customer specific content and samples 
====
improved security on cookies and saved passwords in customers web-browser
preventing confusion of customers on different versions/projects
=======
```
dig +short TXT _psl.csx.cc
"https://github.com/publicsuffix/list/pull/1036"
```
make test
=========
=> Add csx.cc to Private section

public_suffix_list.dat
====
WIARD Enterprise is a non-profit organisation providing digital training opportunities to young people in disadvantaged communities via various community focused projects
Organization Website: n/a
====
To implement gitlab pages so that developers/contributors can deploy pages in an automated way
=======
dig +short TXT _psl.pages.wiardweb.com
"https://github.com/publicsuffix/list/pull/1035"
make test
=========
Results from CI
```
Making check in …
```
=> add pages.wiardweb.com

public_suffix_list.dat
Jelastic is a Multi-Cloud PaaS (Platform as a Service) with decentralized network of independent cloud hosting service providers located across the Globe.
**Organization Website**: https://jelastic.com
Addition to #1023
Security enhancement between the subdomains.
There is a large network of independent and distributed cloud hosting providers that offer shared domains for their end users, for example _*.cloudjiffy.net_. End users can get a custom subdomain on top of the shared public domain, for example _myapp.cloudjiffy.net_. Such subdomains are managed by different users or organisations with the ability to set cookies and they may create an arbitrary amount of subdomains. We would like all of the public domain names to be compliant, including cookie handling and DNS sorting.
Similar …
=> The list of Jelastic public domains was extended. Addition to #1023

public_suffix_list.dat
====
Organization Website: https://www.getopensocial.com/
Open Social is a SaaS hosting provider that provides individual sites to each of its customers. Customers have the ability to run arbitrary JavaScript code on their platform. 
====
We wish to add `opensocial.site` to the list so that cookies issued by different customers sites are not transferred across customer boundaries.
Additionally our hosting provider (Platform.sh) has implemented top-level domain ownership verification preventing new projects being created with a subdomain of a domain in use on another project. This currently breaks our automation. Including this new domain on the PSL and issuing customer sites using it properly signals to their system that these domains …
=> Add opensocial.site

public_suffix_list.dat
====
we are a platform as a service startup that provide global content delivery and web hosting services
Organization Website: https://cloud.impertrix.com
====
for cookie security of domains that point to our domain and lets encrypt issuance for domains that points to our content delivery and webhosting domains
=======
dig +short TXT _psl.impertrix.com
"https://github.com/publicsuffix/list/pull/1060"
dig +short TXT _psl.impertrixcdn.com
"https://github.com/publicsuffix/list/pull/1060"
make test
=========
the tests were successful, https://pastebin.com/uYcSkxxh
=> add impertrix.com and impertrixcdn.com

public_suffix_list.dat
====
LLP "Internet-Pro" (http://netangels.ru) is company that provided shared and private hosting. 
For our clients we provide sub-domains from `na4u.ru` for testing and hosting purposes without the need of buying a personal domain. 
====
Main reason for inclusion is restriction of cookie sharing between these subdomains in `na4u.ru`. Domain registered for this purpose: allow untrusted clients have tehnical domain and not crossed with our domains.
Secondary reason to split Let's Encrypt issuance for websites (yes, we hit limit but this is not big problem, because SSL certificates is slowly issued).
Example of websites that have subdomain in out domain (they already have own domain):
1. https://alabuga.na4u.ru/
2. …
=> Add na4u.ru to list

public_suffix_list.dat
====
[GOV.UK Pay](https://www.payments.service.gov.uk/) is the UK Government's payments platform - this is a domain used for hosting test applications and other miscellaneous services. i.e. `app.pymnt.uk`
Organization Website: https://www.payments.service.gov.uk/
====
We require this domain to be added to the PSL to help ensure cookie isolation between subdomains.
Additionally, one of our subdomains has been flagged as deceptive/phishing, which has resulted in all subdomains of *.pymnt.uk being flagged as dangerous.
=======
```
dig +short TXT _psl.pymnt.uk
"https://github.com/publicsuffix/list/pull/1084"
```
make test
=========
I have run the tests and they pass correctly
=> Add GOV.UK Pay test environment domain

public_suffix_list.dat
====
Organization Website: https://omniwe.com
I am the founder of OmniWe Limited.
====
The company is providing a SaaS platform to let users create their own eCommerce websites as a sub-domain under `omniwe.site`, we would like to limit cookies from leaking into others' websites.
=======
```
dig +short TXT _psl.omniwe.site
"https://github.com/publicsuffix/list/pull/1072"
```
make test
=========
```bash …
```
=> Add omniwe.site

public_suffix_list.dat
====
mcpe.me offers short hostnames primarily for Minecraft Pocket Edition Servers, but is also used for Minecraft related websites. It is a personal project of mine that started a few years ago. I allowed people to register and modify subdomains in a self-service way at https://mcpe.me. Although I have run out of capacity for new subdomains, there are about a thousand mcpe.me subdomains operated by different indidviduals. 
Organization Website: https://mcpe.me
====
Primarily for cookie security across the domains as I don't do any sort of validation on the users of the namespace.
=======
```
dig +short TXT _psl.mcpe.me
"https://github.com/publicsuffix/list/pull/1080"
```
make test
=========
I ran the tests and …
=> Added mcpe.me

public_suffix_list.dat
====
Organization Website: https://www.cesnet.cz/?lang=en
Activity Website: https://www.metacentrum.cz/en/index.html
CESNET provides numerous services for academic computing. This particular activity delivers a public IaaS cloud service for academic use, provided partly through a national portal (https://www.metacentrum.cz/en/Sluzby/Cloud/) and partly through the European Grid Initiative's Federated Cloud Platform (https://www.egi.eu/federation/egi-federated-cloud/).
====
Our subdomains for public cloud machines are already included in the list. This pull request is a modification to exclude the actual head node of the service at `cloud.metacentrum.cz` from the public suffix list since that particular machine is not a public cloud VM …
=> Modify cloud.metacentrum.cz entry

public_suffix_list.dat
====
Jelastic is a Multi-Cloud PaaS (Platform as a Service) with decentralized network of independent cloud hosting service providers located across the Globe.
**Organization Website:** [https://jelastic.com](https://jelastic.com)
====
Addition to [#1023](https://github.com/publicsuffix/list/pull/1023) and [#1063](https://github.com/publicsuffix/list/pull/1063)
Security enhancement between the subdomains.
There is a large network of independent and distributed cloud hosting providers that offer shared domains for their end users, for example *.cloudjiffy.net. End users can get a custom subdomain on top of the shared public domain, for example myapp.cloudjiffy.net. Such subdomains are managed by different users or organisations with the …
=> The list of Jelastic public domains was extended. Addition to #1023 #1063

public_suffix_list.dat
Add omg.lol
====
OMG.LOL provides email, DNS, and web hosting services.
Organization Website: https://omg.lol
====
* Cookie security
* DMARC policy records for email subdomains
=======
```
dig +short TXT _psl.omg.lol
"https://github.com/publicsuffix/list/pull/1090"
```
make test
=========
Locally executed tests have passed.
=> Add omg.lol

public_suffix_list.dat
Added gitapp.si
====
Gitplac.si is a privately owned self hosted Gitlab instance. The platform is currently closed for new signups, but is planned to open in near future. 
Organization Website:
https://gitplac.si
====
Cookie Security, Let's Encrypt issuance
The domain will be used to automatic application deployments. Any user will be able to deploy an application, manage their cookies, request TLS certificates for new subdomains, ...
=======
```
[aljaxus@desktop ~]$ drill _psl.gitapp.si TXT
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 62854
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; _psl.gitapp.si.      IN      TXT
;; ANSWER SECTION:
_psl.gitapp.si. 60 …
```
=> Added gitapp.si

public_suffix_list.dat
Add gsj.bz
====
Organization Website: https://gsj.bz/
gsj.bz is our root-domain.
We offer services in subdomains.
Below are some of them.
https://dx-sp.gsj.bz/
https://vb-sp.gsj.bz/
http://stamp-is.gsj.bz/
I am these director.
====
The reason for inclusion is Cookie Security.
=======
```
dig +short TXT _psl.gsj.bz
"https://github.com/publicsuffix/list/pull/1065"
```
make test
=========
=> Add gsj.bz

public_suffix_list.dat
====
Organization Website: https://www.norid.no
I am a systems developer at Norid AS
Norid AS runs the registry for Norwegian domain names. All domains directly under .no are registered with us.
====
This is just an update of the URLs in the comments in the list.
=======
N/A
make test
=========
...
Making check in tests
CC       test-is-public.o
CC …
=> Updated comments with new URLs to the different lists of domains.

public_suffix_list.dat
====
Organization Website: https://wpengine.com
WP Engine is a commercial company that provides managed WordPress hosting. I work on WP Engine's engineering leadership team.
====
Our customers can publish their sites as subdomains of js.wpenginepowered.com, and we want to prevent cookies from being shared between sites.
=======
```
$ dig +short TXT _psl.js.wpenginepowered.com
"https://github.com/publicsuffix/list/pull/1103"
```
make test
=========
All tests pass:
``` …
```
=> Add js.wpenginepowered.com

public_suffix_list.dat
Used for trademarks registered in Algeria
====
The .tm.dz zone seem have been around for quite some time, but is not included in the PSL
Source: http://www.nic.dz/images/pdf_nic/charte.pdf - page 3 (in French)
~~(However I'm unable to find any domain in the zone, which is not using DNSSEC so I cannot enumerate domains either)~~
I will also try to update the [Wikipedia page](https://en.wikipedia.org/wiki/.dz) (**edit:** done)
The zone was [removed from Wikipedia in 2017](https://en.wikipedia.org/w/index.php?title=.dz&diff=798042678&oldid=798041828), seemingly because the [English charter](http://www.nic.dz/en/images/pdf_nic/charte.pdf), not changed since 2012, did not include it
```
% dig +short SOA tm.dz
ns1.nic.dz. dnsmaster.nic.dz. 2020091700 3600 600 86400 3600 …
```
=> Add .tm.dz

public_suffix_list.dat
====
Organization Website: https://translate.google.com/intl/en/about/
Engineer at Google on the Translate team
====
.translate.goog will be serving 3rd party code separated by publisher. This is very similar to (but a different use case than) appspot.com. Currently there is no much public usage, but since it takes a while to get into the PSL, we would like to have it available before wider use.
=======
```
dig +short TXT _psl.translate.goog
"https://github.com/publicsuffix/list/pull/1107"
```
```
dig +short TXT _psl.tr-test.goog
"https://github.com/publicsuffix/list/pull/1107"
```
make test
=========
```
Testsuite …
```
=> Adds translate.goog and tr-test.goog

public_suffix_list.dat
====
Organization Website: https://www.wapblog.id
I'm Fajar Sodik from WapBlog Developer Team
WapBlog.ID is a platform for create a blog.
====
WapBlog.ID is a platform blog builder who user can create a blog which our subdomain or their own domain. If they don't have a domain, we provide some excelent domain for them like wbq.me or wblog.id and many other.
It could be very usefull, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and wapblog.id services too.
=======
```
dig +short TXT _psl.bloger.id
"https://github.com/publicsuffix/list/pull/1111"
```
```
dig …
```
=> Add wapblog's domain

public_suffix_list.dat
Sort Alphabet entries by TLD first and then by SLD. The change was requested in a conversation for the PR https://github.com/publicsuffix/list/pull/1117.
This PR doesn't add or delete PSL entries.
National blogspot entries remain in a separate block.
make test
=========
```
============================================================================                                          
Testsuite summary for libpsl 0.21.1                                                                                   
============================================================================                                          
============================================================================ 
======================================================================== …
```
=> Sort Alphabet entries by TLD first and then by SLD.

public_suffix_list.dat
====
Organization Website: https://www.gentlent.com
I am a director and engineer at Gentlent, which is a software development and consulting company.
====
It's about cookie security, as we'll provide subdomains to our customers as part of our in-dev CDN offering.
=======
```
dig +short TXT _psl.cdn-edges.net
"https://github.com/publicsuffix/list/pull/1110"
```
make test
=========
We ran the test.
=> Add cdn-edges.net

public_suffix_list.dat
====
Organization Website: https://www.fh-muenster.de
We are the University of Applied Sciences Muenster. I am the responsible IT Administrator.
====
We want to host Gitlab Pages under this subdomain and according to cookie security best practices it is advisable to be included in the PSL
=======
```
dig +short TXT _psl.fh-muenster.io
"https://github.com/publicsuffix/list/pull/1134"
```
make test
=========
make test run successfully
=> Add fh-muenster.io to PSL

public_suffix_list.dat
====
Organization Website: https://www.wapblog.id
I'm Fajar Sodik from WapBlog Developer Team
WapBlog.ID is a platform for create a blog.
====
WapBlog.ID is a platform blog builder who user can create a blog which our subdomain or their own domain. If they don't have a domain, we provide some excelent domain for them like wbq.me or wblog.id and many other.
It could be very usefull, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and wapblog.id services too.
Update:
i was mistake write the file which i contain **bloghp.id** and in my submission i write bloger.id …
=> Update WapBlog.ID domain

public_suffix_list.dat
====
PE Ulyanov Kirill Sergeevich; Hosting
Organization Website: https://airy.host/
====
Domains under management airy.host (lk3.ru , zsew.ru , ra-ru.ru) should be listed in the PSL to provide cookie security and to allow password managers to apply the correct password on different subdomains.
.RU domains are registered for not more than 1 year, but domains have been in use for over 2 years. 
=======
```
% dig +short TXT _psl.lk3.ru       
"https://github.com/publicsuffix/list/pull/1149"
% dig +short TXT _psl.ra-ru.ru
"https://github.com/publicsuffix/list/pull/1149"
% dig +short TXT _psl.zsew.ru 
"https://github.com/publicsuffix/list/pull/1149"
```
make test
=========
Add merge via web
=> Add private domains for airy.host

public_suffix_list.dat
====
Organization Website: https://digitalocean.com
I am Braxton Huggins. I work for DigitalOcean. DigitalOcean offers many cloud services including virtualized servers, managed databases, managed kubernetes clusters, and an application platform.
====
DigitalOcean's new application platform creates subdomains for each hosted app on the domain `ondigitalocean.app`.
We would like to be included in the list to provide cookie security for our end users.
=======
```
dig TXT _psl.ondigitalocean.app +short
"https://github.com/publicsuffix/list/pull/1150"
```
make test
=========
I ran the test
=> Add ondigitalocean.app to the list of private domains

public_suffix_list.dat
Dears,
Kindly update the .ye in the suffix list as follows:
// ye : Confirmed by registry 21/01/2021
ye
com.ye
edu.ye
gov.ye
net.ye
mil.ye
org.ye
We are ALL able to query 1.1.1.1 or 8.8.8.8 and get these answered as shown below, nowadays.
Eager to hear from you soon.
Thanks a lot
Yours,
Riyadh
####################################################
eg:
nslookup -type=txt _psl.ye
Server:         195.94.0.36
Address:        195.94.0.36#53
_psl.ye text = "https://github.com/publicsuffix/list/pull/897"
###
$ dig @1.1.1.1 txt _psl.ye
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-16.P2.el7_8.6 <<>> @1.1.1.1 txt _psl.ye
; (1 server found)
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15544
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT …
=> Update .ye in ICANN section (was #897)

public_suffix_list.dat
====
Organization Website: https://snowplowanalytics.com/
Snowplow is an open-source data delivery platform, maintained by our UK-based company Snowplow Analytics.  Snowplow is the most widely adopted platform for collecting, processing and delivering behavioral data.  The core components of a snowplow event pipeline are free and open-source, which has led to its wide-scale adoption on countless websites and mobile apps.
====
The [Try-Snowplow](#) experience allows prospective Snowplow users to a deploy their own instance of the platform hosted under a subdomain of `try-snowplow.com`. Users of these platform instances are fully autonomous and they do not share any level of trust with other instances.  Therefore cookies and wildcard tls …
=> Add try-snowplow.com to PSL

public_suffix_list.dat
====
====
* .wed is a valid TLD since 2013: https://www.icann.org/resources/agreement/wed-2013-10-01-en
* .البحرين [.xn--mgbcpq6gpa1a] is a valid TLD for "albahrain": https://www.iana.org/reports/2020/xn--mgbcpq6gpa1a-report-20200110.html
* .ລາວ [.xn--q7ce6a] is a valid TLD for "Lao": https://www.iana.org/reports/2020/xn--q7ce6a-report-20200110.html
* .za is a valid TLD and the only one in this list of ICANN domains that is not included without any subdomain (even other TLDs which are typically only issued with a secondary domain like .uk are included as a standalone TLD)
=======
make test
=========
I'm unable to run the tests locally, I keep getting an error with `libicu` that I haven't …
=> add missing IDN ccTLDs:  for Bahrain and Laos ( .xn--mgbcpq6gpa1a and .xn--q7ce6a )

public_suffix_list.dat
====
Organization Website:  https://www.kuleuven.be
Catholic University of Leuven, Belgium
====
Subdomains of _kuleuven.cloud_ are used by several cloud providers that offer services to KU Leuven. They should not share cookies via the domain _kuleuven.cloud_.
The domain _.ezproxy.kuleuven.be_ is a specific domain that uses https://www.oclc.org/en/ezproxy.html to offer off-campus access to e-resources. But it enables them to set cookies on the kuleuven.be domain, we want to prevent this by adding the domain .ezproxy.kuleuven.be to the PSL.
We will certainly hold the domain registration for >2 years for both _kuleuven.cloud_ and _kuleuven.be_.
=======
make test
=========
=> Public suffixes KU Leuven

public_suffix_list.dat
Issue #1208 provides a suggested update to the .my section and a link to the updated list of namespace available.
The IANA listed registration authority is for .my is [https://www.iana.org/domains/root/db/my.html](https://www.iana.org/domains/root/db/my.html) shows mynic.my as the authoritative registry.
The link to the list of registerable extensions furnished in issue #1208 is from mynic.my and it adds biz.my 
This pr revises the .my section in the following ways:
- adds biz.my
- sorts the existing sld entries to conform with updated sorting standards
- updates the listed entity header from mynic.net.my to the mynic.my
- adds link to the namespace definitions
====
Organization Website: mynic
I am one of the PSL maintainer volunteers, taking issue #1208 and …
=> Update .my in ICANN section

public_suffix_list.dat
====
Organization Website: https://www.framer.com
My name is Koen Rouwhorst, I am a security engineer, and I represent Framer B.V.
Framer is a web-based collaborative prototyping for teams that allows users to create interactive prototypes. These prototypes are powered by modern web technologies.
====
* `framercanvas.com` (expires 2023-02-18) - The user's canvas is the place where they create their Framer prototypes. Under the hood it is served up under a separate user content domain (`<project-id>.framercanvs.com`) as it displays and executes untrusted user content. Reason for inclusion is to provide better isolation between projects.
* `framer.app` (expires 2023-10-02) - Framer prototypes, which are essentially web applications, may …
=> Add framer.app and framercanvas.com

public_suffix_list.dat
* n/a - see below
====
Organization Website: https://www.gov.scot
The Scottish Government is the devolved government for Scotland.
I submitted the PSL entry for its domain, gov.scot, in #904, and am [listed](https://github.com/publicsuffix/list/blob/c565a9abe69982803ace41b221a0341a04d49602/public_suffix_list.dat#L13104) in the PSL as the contact for that domain.
====
The `service.gov.scot` domain is intended for public services aimed at citizens and residents in Scotland offered by the Scottish Government, other public sector entities in Scotland, and private sector vendors offering services on behalf of the Scottish Government.
Hence, the domain is intended to be shared by multiple organisations, and while we assume their good …
=> Add service.gov.scot

public_suffix_list.dat
====
Organization Website: https://medicomhealth.com/
Medicom Health is the market leader in online health risk assessments (HRAs). It’s our passion! 850+ influential hospitals use our best-in-class tools to convert website & Facebook visits to revenue-rich office visits. At first glance, these evidence-based HRAs appear to be simple “health quizzes” but they hide a deeper power. They spark “aha moments” to engage patients. They collect actionable data to turbo-charge CRMs & personalize digital outreach. The back-end portal allows marketers to enhance their patient acquisition workflow via customization and integration options.
====
Each of our clients have a unique set of health risk assessments (HRAs) that we would like to group under …
=> Add hra.health to PSL

public_suffix_list.dat
====
Organization Website: https://shiftcrypto.ch
Shift Crypto is a privately held company based in Zurich, Switzerland. Our international team of specialists across engineering, cryptosecurity and Bitcoin core development build the BitBox products and provide consulting services. We manufacture [BitBox02](https://shiftcrypto.ch/bitbox02/), a cryptocurrency hardware wallet.
====
Our hardware products are accompanied by software, [BitBoxApp](https://shiftcrypto.ch/app/), which relies on a number of services connected over Internet.
Up to now, we've been using the domains in question for internal purposes, but will soon start exposing various network services under sub domains. The services may be run by and assigned to different groups …
=> Add shiftcrypto.dev and shiftcrypto.io

public_suffix_list.dat
====
Organization Website: https://www.mazeplay.com
I am the lead developer at Manwaring Web Solutions, Inc which builds and hosts websites. We build and maintain an online ticketing system for Maze Play which they market to farmers. So I am submitting this on their behalf. The ticketing system takes the form of mazename.mazeplay.com.
Some current examples:
* andelinfarmtickets.mazeplay.com
* farmtownfun.mazeplay.com
* libertycornmaze.mazeplay.com
====
These maze owners are attempting to set up conversion tracking and inclusion in the public suffix list is required for the cookie security with changes in iOS 14.5 as per https://www.facebook.com/business/help/331612538028890?id=428636648170202
The domain mazeplay.com is currently …
=> Adding mazeplay.com

public_suffix_list.dat
====
Organization Website: [Platform.sh](https://platform.sh/)
[Platform.sh](https://platform.sh/) is new generation PaaS hosting solution.
====
In order to safely power our white-label offerings we are grouping them all under `*.tst.site` umbrella. Platform.sh is already featured in PSL via #417 and #1061.
=======
```
dig +short TXT _psl.tst.site
"https://github.com/publicsuffix/list/pull/1256"
```
make test
=========
```
```
=> Update Platform.sh domains

public_suffix_list.dat
=> Update cn.vu in Private section

public_suffix_list.dat
* [ x ] Description of Organization
* [ x ] Reason for PSL Inclusion
* [ x ] DNS verification via dig
* [ x ] Run Syntax Checker (make test)
* [ x ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.
====
Organization Website: https://storebase.io
Storebase is an Ecommerce SaaS. We provide merchants the tools to sell their products online. 
====
We provision store backends on *.storebase.store, and seperate out our admin login to the frontend domain selling the products online. We're looking to provide cookie protection to ensure CSRF attacks don't occur between the backends of storebase stores.
=======
```
dig +short TXT _psl.storebase.store …
```
=> added Storebase.store

public_suffix_list.dat
====
Organization Website: github.com (though this is for github.dev and githubpreview.dev)
I'm a software engineer at GitHub working on the new Codespaces product
====
We want to restrict the ability to create cookies that span subdomains of github.dev and githubpreview.dev 
Both of these domains aren't set to expire until 2023:
```
$ whois github.dev|grep -i expir
Registry Expiry Date: 2023-01-16T16:27:37Z
$ whois githubpreview.dev|grep -i expir
Registry Expiry Date: 2022-12-09T21:03:15Z
```
=======
`dig +short TXT _psl.github.dev` and `dig +short TXT _psl.githubpreview.dev` both point to this URL
make test
=========
I wasn't able to get the tests to run locally but they do pass in CI. Let me know if this …
=> Add github dev domains

public_suffix_list.dat
====
Organization Website: https://noop.app/ 
Noop (a play on words for no-op, or no operations) is a Platform as a Service enabling developers to deploy their applications without the need to manage operations themselves. 
====
Noop makes use of Let's Encrypt to issue TLS certificates for our customers.
The domains have been renewed for the next 2 years.
=======
```
dig +short TXT _psl.developer.app
"https://github.com/publicsuffix/list/pull/1265"
```
```
dig +short TXT _psl.noop.app
"https://github.com/publicsuffix/list/pull/1265"
```
make test
=========
``` …
```
=> Add noop.app and developer.app to PSL

public_suffix_list.dat
====
Organization Website: https://authgear.com, https://oursky.com
Authgear is an authentication server for web and mobile apps. We allow our users to create applications in our cloud service and use it as their application authentication server. 
====
We allow our users to create applications in our cloud service and use it as their application authentication server. The authentication server of applications are under subdomains of authgearapps.com and authgear-staging.com. So we would like to add them to the list to isolate cookies per application.
=======
```
dig +short TXT _psl.authgearapps.com
"https://github.com/publicsuffix/list/pull/1304"
```
```
dig +short TXT _psl.authgear-staging.com …
```
=> Add authgearapps.com authgear-staging.com

public_suffix_list.dat
====
====
=======
make test
=========
=> Remove wildcard id.forgerock.io

public_suffix_list.dat
====
Organization Website: https://jotelulu.com
Jotelulu S.L. is a cloud provider that offers SME-oriented services. We allow our users to work from anywhere without having to deal with a complicated interface. 
====
We assign subdomains under the jotelulu.cloud domain to our clients (for example, customer1.jotelulu.cloud, customer2.jotelulu.cloud) to access their environments. There they can deploy any application.
We want to protect the subdomains under jotelulu.cloud from the exchange of cookies between subdomains.
The registration term for 'jotelulu.cloud' is greater than 2 years, and it will be extended automatically.
```
whois jotelulu.cloud | grep "Registry Expiry"
Registry Expiry Date: 2026-06-08T09:28:18Z
```
DNS Verification …
=> Add jotelulu.cloud

public_suffix_list.dat
====
Postman is a collaboration platform for API development. Postman allows producers to build APIs and allows consumers to discover and use these APIs. Postman's features simplify each step of building an API and streamline collaboration so you can create better APIs—faster.
**Organization Website:** https://www.postman.com/
I'm a Security Engineer and I'm part of the Research and Mitigation team.
====
So we're primarily looking for cookie security.
Postman's Mock Servers provides the ability to simulate the behaviour of real API. Mock Servers can be useful if your production API's are not yet built or if you do not wish to run the API against real data. A Mock server is hosted on a unique subdomain. Every subdomain is in the form of …
=> Add postman dev domains

public_suffix_list.dat
This PR reverts https://github.com/publicsuffix/list/pull/1233
====
Organization Website: https://www.curvegrid.com/
Curvegrid is a blockchain software company. Our core product MultiBaas allows both independent developers and enterprise companies to rapidly prototype and build blockchain applications.
We are offering MultiBaas as a fully managed SaaS solution in which users/organizations get assigned sub-domains under multibaas.com and/or multibaas.app.
Reason for PSL removal
====
We are encountering some unwanted side effects with a popular web infrastructure and website security company that provides content delivery network services, DDoS mitigation, Internet security, and distributed domain name server services. 
This company do not recognize our domains …
=> Remove multibaas.app and multibaas.com

public_suffix_list.dat
=> Add elementor.cloud and elementor.cool

public_suffix_list.dat
__Smoove company affirms the following:__ 
---
====
Organization Website: https://www.smoove.io 
We are an ESP and marketing platform that gives businesses from all over the world a full set of tools for their marketing and administrative needs.
from newsletters to landing pages to full marketing automation.
====
Our users get a vp4.me subdomain for their landing pages, the subdomain is personal and separate for each account.
they use it for their business needs: various registration forms, purchase pages, advertising campaigns, business cards, and more.
for example: danafb1.vp4.me
This is a pull request in response to the Apple iOS 14.5 change that affected Facebook Pixel tracking functionality for the domain(s) in the change, and we …
=> Add Smoove private domain

public_suffix_list.dat
=> Add clerk.app and clerkstage.app

public_suffix_list.dat
=> add homesklep.pl domain

public_suffix_list.dat
=> add ecommerce-shop.pl

public_suffix_list.dat
=> Add Ellucian domains

public_suffix_list.dat
=> Updating Cloudera domains

public_suffix_list.dat
---
====
nctu.me has been closed since 2020/9/30.
=======
```
> dig +short TXT _psl.nctu.me
"https://github.com/publicsuffix/list/pull/1407"
```
make test
=========
```
Making check in tests
CC       test-is-public.o
CC       test-is-public-all.o
CC       test-is-cookie-domain-acceptable.o
CC       test-is-public-builtin.o
CC       test-registrable-domain.o
CCLD     test-is-public
CCLD …
```
=> Remove: nctu.me

public_suffix_list.dat
=> Adding new .ar SLDs and nic.ar URL correction

public_suffix_list.dat
- Update title to reflect product name
- Update email to dedicated mailing list for PSL usage
Signed-off-by: Robin H. Johnson <rjohnson@digitalocean.com>
=> ondigitalocean.app: update comment for DigitalOcean App Platform

public_suffix_list.dat
* [X ] Description of Organization
* [X ] Reason for PSL Inclusion
* [X ] DNS verification via dig
* [X ] Run Syntax Checker (make test)
* [X ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
---
``` 
Rollback is really not predicatable, as those who use or incorporate the …
```
=> Added FlashDrive.io domain names

public_suffix_list.dat
This is a request by SIDN (registry of .nl) on behalf of Omar Iqbal (x2com.nl / clearvox.nl) to remove virtueeldomein.nl after discussing this with them. The original submitter (Leon Rowland) is no longer working there. Knowledge about how to do this seems vanished with him from the organization that originally submitted. Will attempt to have them add the _psl, but not sure if they are able to.
Related to: https://github.com/publicsuffix/list/issues/472
---
``` 
certificate (as well as other) …
```
=> REMOVAL of virtueeldomein.nl

public_suffix_list.dat
=> Adding Hoplix domains

public_suffix_list.dat
=> feat: Add pro.typeform.com to PSL

public_suffix_list.dat
=> Add codeberg.page to PSL

public_suffix_list.dat
=> add `*.beget.app`

public_suffix_list.dat
=> Add `messwithdns.com`

public_suffix_list.dat
Add tech.orange in PSL
---
``` 
stay that way for an …
```
=> Add `tech.orange`

public_suffix_list.dat
=> Add `site.transip.me` for TransIP

public_suffix_list.dat
=> Add `aivencloud.com`

public_suffix_list.dat
=> Add `typedream.app`

public_suffix_list.dat
=> Add `deta.app` and `deta.dev`

public_suffix_list.dat
- add direct.quickconnect.cn
- sort the list according to https://github.com/publicsuffix/list/wiki/Guidelines#prepare-the-change
- test passed
---
``` 
The volunteers are busy with new requests, and …
```
=> Add new `direct.quickconnect.cn` domain to Synology dynamic dns service.

public_suffix_list.dat
=> Add `1.azurestaticapps.net` DNS suffix

public_suffix_list.dat
___________________
====
Organization Website: https://udr.org.yt
Universal Domain Registry (UDR) also operating as 'HostBip' is a 'PDNR' (Private Domain Name Registry), allowing 3rd parties to register domain names in a variety of domain name extensions/suffixes. This pull request adds or updates the entries for a number of domain extensions that we operate.
====
'UDR' is claiming some legacy names from the Hostbip's existing section in the 'Public Suffix List', and is creating a new section to include additional domain extensions/suffixes in its portfolio.
This request is seeking to add these to the PSL so the individuals/institutions operating under these suffixes can gain access to services such …
=> UPDATE HOSTBIP RECORDS (`name.pm` `sch.tf` `biz.wf` `sch.wf` `org.yt`)

public_suffix_list.dat
in the notes (comments) under **.in**
the existing path of the uri <https://registry.in/Policies> returns 404
updated to the correct path <https://registry.in/policies>
~~ * [ ] Reason for PSL Inclusion~~
~~ * [ ] DNS verification via dig~~
---
PR Rollbacks have lower priority, and the volunteers are unable to control …
=> doc (`.in`): update ref uri to registry policies

public_suffix_list.dat
=> Add `messerli.app`

public_suffix_list.dat
Israel Internet Association (ISOC-IL) is Israel’s country code top-level domains (ccTLD) registry, responsible for managing .il domain names and ישראל. TLD and SLDs.
ISOC-IL is the Israeli chapter of the Internet Society (ISOC.ORG).
https://isoc.org.il/
Israel Internet Association (ISOC-IL) is Israel’s country code top-level domains (ccTLD) registry, responsible for managing .il domain names and ישראל. TLD and SLDs.
We would like to update the list with the new IDN - .ישראל / xn--4dbrk0ce TLD and SLDs
https://www.iana.org/domains/root/db/xn--4dbrk0ce.html
```
$ dig TXT _PSL.ישראל. +short
"https://github.com/publicsuffix/list/pull/1595"
```
``` …
```
=> add IDN ccTLD `.ישראל` and SLDs for Israel by ISOC-IL

public_suffix_list.dat
====
Website URL: https://www.fastmail.com/
Fastmail is a mailbox provider with a focus on user privary. We provide paid email service to individuals and small businesses. My role within the company is in the backend developer team. We have approximately 250k individual users.
We offer a web hosting service to our users, when a user is not hosting on their own domain we offer the ability to host on a subdomain of our user.fm domain. …
=> Add Fastmail user content domain `user.fm`

.github/pull_request_template.md
_This is not a submission to the public suffix list_
This PR fixes some minor typos in the PR template. I've got some other suggestions too, but they're less objective so I'll submit them in a future PR.
=> Fix typos in pull request template

public_suffix_list.dat
=> update `.bj` 

public_suffix_list.dat
Hi there,
squee from the Fastly DNS Engineering team here, adding a PSL entry for `fastly-edge.com`.
Update: TXT record is now available. PR is ready for review!
Thanks,
squee
====
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the desired outcome and take …
=> add fastly-edge.com

public_suffix_list.dat
=> Add `3.azurestaticapps.net` DNS suffix

public_suffix_list.dat
=> add 47 domains of SAKURA Internet Inc.

public_suffix_list.dat
**For Private section requests that are submitting entries for domains that match their organization website's primary domain:**
```
```
(Link: [about …
=> Add `ie.ua`

public_suffix_list.dat
=> Add `ladesk.com`

public_suffix_list.dat
=> Add `{id,io,ai}.vn` for .vn ccTLD in ICANN Section

public_suffix_list.dat
====
Amazon Web Services is an infrastructure-as-a-service cloud computing provider.
More information about AWS is availble on our website:
[What is AWS?](https://aws.amazon.com/what-is-aws/)
**Organization Website:**  
[AWS Homepage](https://aws.amazon.com)
====
These features/services have been identified by AWS Security and AWS service
teams as supporting different distinct customers/resources across shared
DNS suffixes. Adding these suffixes to the PSL is expected to improve the
security posture of customers using our services.
**Number of users this request is being made to serve:**  
These changes are expected to impact all customers using these AWS services.
This includes both AWS-internal and external customers. Specific user …
=> AWS Submissions to the Public Suffix List - Q1 2023

public_suffix_list.dat
=> Add `storipress.app`

public_suffix_list.dat
=> Update Platform.sh section - add `upsunapp.com`, `upsun.app` domains, remove `bc.platform.sh`

public_suffix_list.dat
====
-  [x] Description of Organization
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and …
=> Replace run.app and a.run.app with *.run.app

public_suffix_list.dat
=> Homebase requested the addition of id.pub kin.one kin.pub

public_suffix_list.dat
====
_AWS does not submit suffixes to the Public Suffix List to work around rate-limits of any third-party products or tooling._
_Please see the Reasonsection below for objectives in this pull request._
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not match the …
=> AWS Submissions to the Public Suffix List - Q4 2023

public_suffix_list.dat
=> add 12CHARS to private domains

public_suffix_list.dat
=> Add `aliases121.com`

public_suffix_list.dat
=> Add `flutterflow.app`

public_suffix_list.dat
=> Add ZAP-Hosting Domains

public_suffix_list.dat
=> Added Cyclic Software

public_suffix_list.dat
=> Add 3 Streak domains

public_suffix_list.dat
=> Add `modx.dev`

public_suffix_list.dat
=> Add `adaptable.app`

public_suffix_list.dat
=> Removing wildcard for cloudapp.azure.com

public_suffix_list.dat
=> GD - graphic.design

public_suffix_list.dat
====
Organization Website: [nft.storage](https://nft.storage/)
Developed by [Protocol Labs](https://protocol.ai/), NFT.storage is a long-term storage service designed for off-chain NFT data. Data is content addressed using IPFS, meaning the URI pointing to a piece of data is completely unique to that data.
Protocol Labs also develops [IPFS](https://ipfs.io/), which allows end-users to resolve content they have published on the IPFS network using content-based addressing. This content can be resolved by web browsers and other clients using public IPFS gateways like `http://<hash>.ipfs.dweb.link`, which is already part of PSL. 
For NFT specific optimisations, we created `http://<hash>.ipfs.nftstorage.link` which can resolve …
=> add `nftstorage.link`

public_suffix_list.dat
=> Add wadl.top

public_suffix_list.dat
=> Update Snowflake Inc domains in PRIVATE section

public_suffix_list.dat
=> Add `is-cool.dev`, `is-local.org`, `is-not-a.dev` and `localplayer.dev`

public_suffix_list.dat
=> Jouwweb public suffixes

public_suffix_list.dat
=> Removing cloudapp.azure.com from PSL

public_suffix_list.dat
=> Add shop.brendly.hr

public_suffix_list.dat
====
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expe …
=> Add `ngo.us` for the NGO.US Registry

public_suffix_list.dat
=> Add aaa.vodka

public_suffix_list.dat
=> Adding regional domain `bielsko.pl`

public_suffix_list.dat
=> Add `sheezy.games`

public_suffix_list.dat
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding.
PR Rollbacks …
=> Add observablehq.cloud

public_suffix_list.dat
=> Add web.val.run and express.val.run to PSL

public_suffix_list.dat
=> Add `*.hosted.app`

public_suffix_list.dat
=> Add Expo domains

public_suffix_list.dat
=> Add `hypernode.io` domain

public_suffix_list.dat
Suffix List (PSL) Pull Request (PR) Template
====
--- …
=> add .ind.mom 

public_suffix_list.dat
=> mytuleap.com, tuleap-partners.com: update contact information

public_suffix_list.dat
====
- <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please …
=> Remove expired domains: `ro.im`, `cn.vu`

public_suffix_list.dat
=> Update comments on aland.fi

public_suffix_list.dat
====
- <UPDATE THIS LIST WITH YOUR LIMITATIONS!>
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have impacts that may not …
=> Add `durumis.com`

public_suffix_list.dat
=> Add `hatenablog.com`, etc.

public_suffix_list.dat
- none
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusio …
=> Add dhosting.pl Sp. z o.o. shared domains: dfirma.pl, dkonto.pl, you2.pl

public_suffix_list.dat
=> Add Servebolt AS shared domain: servebolt.cloud

public_suffix_list.dat
Closes #2046 
Approved by original submitter: https://github.com/publicsuffix/list/issues/2046#issuecomment-2244574946
=> remove Cyclic Software section

public_suffix_list.dat
Removes two domains that I am responsible for that are no longer used as public suffixes.
=> remove old domains

public_suffix_list.dat
====
* [] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the \_PSL txt record in place in the respective zone(s) in the affected section
* [] We are listing *any* third-party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue …
=> update for .PK ccTLD

public_suffix_list.dat
=> Add `mafelo.net`

public_suffix_list.dat
=> add `is-a-fullstack.dev` under Open Domains

public_suffix_list.dat
=> add `is-a-good.dev`

public_suffix_list.dat
=> add `preview.wdh.app` and `t.hrsn.net`

public_suffix_list.dat
I know this is like an OCD thing and pretty insignificant, but I just wanted to tidy up some inconsistencies in the comments. So, here's a quick PR to fix those.
=> Fix syntax inconsistency

public_suffix_list.dat
=> Update contact information for `nyc.mn`

public_suffix_list.dat
====
- <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please …
=> 2024 Update for domain diher.solutions and rss.my.id

public_suffix_list.dat
=> add `nyat.app`

.github/workflows/psltool-fmt.yml
Add a GH action to run psltool fmt
=> Add new action to manually run formatter

public_suffix_list.dat
====
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expe …
=> Adding oraclecloudapps.com from Oracle Autonomous Database

public_suffix_list.dat
confirmed by the initial requestro https://github.com/publicsuffix/list/pull/1232#issuecomment-2333082166
=> Remove `magnet.page` (Rollback #1232)

public_suffix_list.dat
====
- <UPDATE THIS LIST WITH YOUR LIMITATIONS! REMOVE ENTRIES WHICH DO NOT APPLY! REMOVE THIS LINE!>
---
For Private section requests that are submitting entries for domains that match their organization website's primary domain, please …
=> Add `ctfcloud.net` domain

.github/pull_request_template.md
This PR aims to fix some grammar in the PR template and move some text to comments in order to reduce the visible length of the PR template when finished.
=> docs(pr_template): various fixes and comment updates

.github/pull_request_template.md
=> docs(pr_template): fix grammar error + small changes

public_suffix_list.dat
Public Suffix
---
(Link: [about propagation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-i …
=> Add shopware.shop to public suffix list

public_suffix_list.dat
Hello, we are updating our contact email address for `prvcy.page` which was added from #1859. Thank you!
=> Update `prvcy.page` contact email

tools/internal/domain/domain.go, tools/internal/parser/unicode.go
Despite being a process of reading from read-only state, somehow these APIs turn out to be thread-unsafe, and parsing multiple PSLs concurrently in the same process results in data races and panics.
Thankfully each use of the collator is quite short, so wrapping their use in a global mutex, while unfortunate, is acceptable. And enabling parallel parsing of PSLs speeds up online validations by a factor of 10x on many cored machines.
---
First step of TXT record validation. To make it go fast it parses PSL files concurrently, and that revealed that x/text/collate is not thread safe :facepalm: This is a targeted fix for that issue.
=> tools/internal: wrap use of collators in mutexes

public_suffix_list.dat, tools/internal/parser/diff.go
Not sure why these were ever separate sections in the first place considering they are for the same organisation.
Original PRs: #438, #622 and #1076
=> combine duplicate sections

.github/pull_request_template.md
=> chore(pr_template): remove syntax check

public_suffix_list.dat
Adding Heyflow GmbHs service provider domains to public_suffix_list.dat
There is none!
tech@heyflow.com and via https://get.heyflow.com/report-abuse
This form is linked on our companys website https://heyflow.com and can also be found on the default page returned on https://heyflow.page and https://heyflow.site
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and …
=> Adding Heyflow GmbHs service provider domains heyflow.page & heyflow.site

public_suffix_list.dat
I am creating this pull request to update the .AF block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/af.html and identified the registry website for registration services http://www.nic.af
2. From http://www.nic.af located https://www.nic.af/instruction-fill-registration-form-af
> - .gov.af for government agencies
> - .com.af for commercial entities
> - .org.af for non commercial organisations
> - .net.af for network providers
> - .edu.af for educational institutions
=> chore: Update `.AF` Section link and sorting

public_suffix_list.dat
I am creating this pull request to update the .GE block in the ICANN section.
1. Started at the IANA page: https://www.iana.org/domains/root/db/ge.html and identified the email address as well as the registry website for registration services https://nic.ge/
3. Received a direct reply from the domain registry `info <info@nic.ge>`, confirming the requested information.
> Currently we are operating the following SLDs: .com.ge, .edu.ge, .pvt.ge,.org.ge, .net.ge, .school.ge. , .gov.ge. We aren't operating .mil.ge SLD, but we are planning to add more SLDs to .GE zone.
> 
> Best regards,
> 
> .GE ccTLD Registry
> Tel: (+995 32) 2 00 00 22 
> E-mail: …
=> Update `.GE` Section

public_suffix_list.dat
This PR only updates contact informations.
--- …
=> Update company & contact email address only

public_suffix_list.dat
=> update info + add note regarding 2LDs for `.name`

public_suffix_list.dat
* [Let's Encrypt](https://letsencrypt.org/docs/rate-limits/)
https://fleek.xyz/requests/report-site/
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand them, and confirm this understanding.
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will …
=> add on-fleek.xyz

public_suffix_list.dat
This PR is created to update comments for `.it`, `.jp`, `.se`, `.cn` to fix broken links and note some registry confirmation responses to improve documentation.
=> Update comments for `.it`, `.jp`, `.se`, `.xn--fiqs8s`, `.xn--fiqz9s`

public_suffix_list.dat
This PR partially solves #2338, by fixing some of the broken URLs.
They were fixed by either:
a) changing the URL to just the root domain, not using a specific path
b) finding the updated URL path
c) using the next best match for what the original URL hosted
=> fix some URLs

public_suffix_list.dat
Updating my email address to a less personal one, which includes spam filtering.
=> update email address

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://inventor.gg/legal/terms
---
(Link: [about …
=> add botdash domains

public_suffix_list.dat
This PR replaces all broken ccTLD links with IANA page links to resolve #2338
=> Replace broken links

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: [https://liara.ir/abuse](https://liara.ir/abuse)
---
(Link: [about …
=> Add Liara suffixes

public_suffix_list.dat
https://report.alibabacloud.com
---
(Link: [about …
=> Add alibabacloudcs.com 

public_suffix_list.dat
**Abuse Contact:** security@laravel.com
URL where abuse contact or abuse reporting form can be found: https://ea-docs.laravel.cloud/docs/abuse
---
(Link: [about …
=> Add laravel.cloud

public_suffix_list.dat
* Add cpanel.site to private section
URL where abuse contact or abuse reporting form can be found: abuse@webpros.com
---
(Link: [about …
=> Add cpanel.site to private section

public_suffix_list.dat
*We do not intend to work around the rate-limits of any other services.*
*Please see reason section below.*
https://inferno.net.uk (linked from https://inferno.co.uk/contact-us)
---
PR Rollbacks have lower priority, and the volunteers are …
=> Add oninferno.net

public_suffix_list.dat
- https://toss.im/. The official site of our organization.
- You can find customer support menu from the bottom of the site.
- The site is easily accessibile by visiting "deus-canvas.com" which is the domain registered by this PR.
---
PR …
=> Add deus-canvas.com to PSL

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://cognition.ai/pages/acceptable-use-policy
---
(Link: [about …
=> Add devinapps.com

public_suffix_list.dat
Domain expired and deleted by the registry.
Current WHOIS record:
```
This premium domain is available for purchase. To register the domain, please contact premium@identity.digital.
This domain is currently available for application via the Identity Digital Dropzone service.
>>> Last update of WHOIS database: 2025-03-10T05:02:18Z <<<
```
WHOIS record before it was deleted:
```
Registrar Registration Expiration Date: 2024-12-14T07:41:05Z
Registry Expiry Date: 2025-12-14T07:41:05Z
```
Email inquiry sent on 2025-03-10, no response received yet.
=> Remove `router.management`

public_suffix_list.dat
None
https://www.appwrite.io/docs/advanced/platform/abuse
---
(Link: [about …
=> Add Appwrite domains to the list

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://help.figma.com/hc/requests/new
---
(Link: [about …
=> add `figma.site`

public_suffix_list.dat
This is a followup to #2412. We're adding some new environments and changing how we assign subdomains. This PR updates the PSL to match.
URL where abuse contact or abuse reporting form can be found: https://cognition.ai/pages/acceptable-use-policy (linked at the bottom of https://cognition.ai which https://devinapps.com redirects to)
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and propagation expectations, that you understand …
=> Add *.devinapps.com

public_suffix_list.dat
We have mail dedicated for reporting security / abusing at `security@e2b.dev`.
---
(Link: [about …
=> Add e2b.app

public_suffix_list.dat
This change adds the TLD seg.ar, which is defined in the official domain policy published by NIC Argentina: https://nic.ar/es/nic-argentina/normativa
---
To ensure that requested changes are entirely intentional, make sure that you read the affectation and …
=> Add seg.ar

public_suffix_list.dat
=> Remove ie.ua

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://luyani.app/ directly.
---
(Link: [about …
=> Add `luyani.app`

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://help.figma.com/hc/requests/new
`preview.site` redirects to `www.figma.com`. From that page, you can click "Support" > "Contact Support" to report abuse.
---
PR Rollbacks have lower priority, and the volunteers are unable to …
=> add `preview.site`

public_suffix_list.dat
https://abuse.eliv.kr/ (or [abuse@eliv.kr](mailto:abuse@eliv.kr))
---
To ensure that requested changes are entirely intentional, make …
=> Add mmv.kr / vki.kr

.github/workflows/psltool-fmt.yml, .github/workflows/psltool_pr_check.yml, .github/workflows/test.yml, .github/workflows/tld-update.yml, .github/workflows/validate.yml
fix: autopin dependencies
Context: [threat actors exploiting github-actions supply-chain in the wild](https://x.com/ramimacisabird/status/1903068773411631426)
=> fix: autopin dependencies

public_suffix_list.dat
**ONID Abuse contact information:**
onid.ca redirects to https://get.onid.ca/ so it's easy to find. 
Abuse contact information is available at https://onid.ca/pages/contact
However, abuse is mostly unlikely because most subdomain users we personally work with and not through automated registration. We are NOT a subdomain registration service like just another `eu.org`. Most of our service involves direct interaction with clients when setting up their subdomains or enterprise solutions or on-premise products.
---
For PRIVATE section requests that are submitting entries for domains that match their organization website's primary domain, please understand that this can have …
=> Add ONID domain

README.md
Closes #2451 
Website PR: https://github.com/publicsuffix/publicsuffix.org/pull/48
=> fix(readme): remove preceding dots

public_suffix_list.dat
Updates the email contact.
Last PR was authored by me: #2225
=> update email contact for is-a.dev

public_suffix_list.dat
Move after the Amazon block and place alphabetically.
Pointed out in https://github.com/publicsuffix/list/pull/2410#issuecomment-2860471873.
None
https://www.appwrite.io/docs/advanced/platform/abuse
---
PR Rollbacks have lower priority, …
=> Move Appwrite domains

public_suffix_list.dat
Actualización de lista de extensiones del dominio ec en orden alfabético
=> Actualización de lista de extensiones del dominio ec en orden alfabético

public_suffix_list.dat
We are not using the public suffix list to work around any limitations imposed by vendors.
* https://github.com/contact or security@github.com
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if …
=> Add github.app to Public Suffix List

public_suffix_list.dat
- No third-party work arounds.
URL where abuse contact or abuse reporting form can be found: https://encr.app https://lp.dev
---
(Link: [about …
=> Add encr.app and lp.dev subdomains

public_suffix_list.dat
Note: See "Reason for PSL Inclusion" below! Impossible at this time for existing entries.
**Abuse Contact:** info@iserv.de
URL where abuse contact or abuse reporting form can be found:  https://iserv.de/impressum
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or …
=> Add iserv.host for IServ GmbH

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://vercel.com/abuse
---
(Link: [about …
=> Add `vercel.run`

public_suffix_list.dat
**Abuse Contact:** abuse@ionos.com
https://www.ionos.com/terms-gtc/domain/terms-abuse/
---
(Link: [about …
=> Add webspace-host.com to PSL

public_suffix_list.dat
aem.network is a supplemental service to the existing aem.page and aem.live domains
https://helpx.adobe.com/x-productkb/global/report-abuse-misuse-of-adobe-products.html and `abuse@adobe.com`
---
PR Rollbacks have lower priority, and the …
=> Update Adobe entries with aem.network for Adobe Experience Manager

public_suffix_list.dat
**Abuse Contact:** abuse@v.ua
https://www.v.ua/contact.html
--- …
=> Update v.ua in public_suffix_list.dat

public_suffix_list.dat
https://www.hidoha.net
---
(Link: [about …
=> Add hidns.co and hidns.vip

public_suffix_list.dat
**Abuse Contact:** abuse@railway.com
URL where abuse contact or abuse reporting form can be found: https://railway.com/legal/terms
---
(Link: [about …
=> Add `up.railway.app` to the PSL

public_suffix_list.dat
[https://qualyhq.com/contact-us/](https://qualyhq.com/contact-us/)
---
Qualy is a B2B SaaS company that provides payment and payout solutions for educational institutions (e.g. colleges and universities) and their education agents. We operate a multi-tenant platform where each customer tenant accesses services via a dedicated subdomain under `qualyhqpartner.com` and `qualyhqportal.com`. 
As the submitter, I am the CTO at Qualy responsible for platform security and infrastructure. 
- The subdomain `qualyhqportal.com` is used by students to perform payments.
- The subdomain `qualyhqpartner.com` is used by the tenant's partners to check the status of payments. 
How Qualy …
=> Add qualyhqpartner.com and qualyhqportal.com

public_suffix_list.dat
**Abuse Contact:** support@ZoneABC.net
URL where abuse contact or abuse reporting form can be found:   [https://ZoneABC.net/about#contact](https://ZoneABC.net/about#contact)
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the PSL will refresh or …
=> Add zabc.net

public_suffix_list.dat
**Abuse Contact: abuse@gov.cz**
URL where abuse contact or abuse reporting form can be found: https://gov.cz/.well-known/security.txt
---
To ensure that requested changes are entirely intentional, make sure that you …
=> Add gov.cz to Public Suffix List

public_suffix_list.dat
https://registro.br/contato/
---
(Link: [about …
=>  * .br - 4 new 2nd level - api ia social xyz

public_suffix_list.dat
URL where abuse contact or abuse reporting form can be found: https://jotelulu.com/en-gb/contact/
---
(Link: [about …
=> Add jote.cloud to Jotelulu's Public Suffix List

public_suffix_list.dat
**Abuse Contact:** abuse@hackclub.app
URL where abuse contact or abuse reporting form can be found: https://guides.hackclub.app/index.php/Contact
---
(Link: [about …
=> Add hackclub.app

public_suffix_list.dat
We have a form to report abuse in
**https://jotelulu.com/en-gb/contact/**
URL where abuse contact or abuse reporting form can be found: https://jotelulu.com/en-gb/contact/
---
PR Rollbacks have lower priority, and the volunteers are unable to control when or if browsers or other parties using the …
=> Add Jotelulu domains

public_suffix_list.dat
Contact Form https://e.id/contact
--- …
=> add e.id to public suffix list private domain
