public_suffix_list.dat
ZADNA administers the TLD .za for South Africa. Information for this addition was found here:
http://www.zadna.org.za/content/page/domain-information
=> update public_suffix_list.dat for .za

tests/test_psl.txt
1bb3c8c34b17e9afe34e308069daeffac91380b2 resolved
https://github.com/publicsuffix/list/issues/7 by removing the *.cy
wildcard in favor of an explicit listing.
However, it did not update test_psl.txt to match, so any tests that
use it would fail.  This patch updates the test suite to use *.il
instead of *.cy.
=> update tests/test_psl.txt since .cy is no longer wildcarded

public_suffix_list.dat
We are Service Online LLC company that provide private registries
.biz.ua, .co.ua and pp.ua.
Web-site: https://drs.ua
Our domains .co.ua and pp.ua. were added to PSL since 21 Feb 2012, but
for some reason our first domain .biz.ua was not added.
Official site of this domain zone (in Russian): www.biz.ua
(http://drs.ua/rus/policy/bizua.html)
Translated version:
http://translate.google.com/translate?hl=ru&sl=uk&tl=en&u=http%3A%2F%2Fdrs.ua%2Frus%2Fpolicy%2Fbizua.html&sandbox=1
Authoritative whois server:  whois.biz.ua port 43
Our registry named CUNIC (Central Ukraine Network Information Center)
is also registered at IANA EPP repository list:
https://www.iana.org/assignments/epp-repository-ids/epp-repository-ids.xhtml
=> Add private registry .biz.ua to PSL

public_suffix_list.dat
I'm on the sandstorm.io team, where we maintain a public dynamic DNS service at sandcats.io.
@kentonv is the listed domain owner. Let me know what we should do to fully confirm the domain name to your satisfaction.
=> Add sandcats.io dynamic DNS service as public suffix

public_suffix_list.dat
Please advise as to what verification is necessary to make this change (As FYI, I'm the same Phil Ames as the one that requested a similar change in https://bugzilla.mozilla.org/show_bug.cgi?id=965744)
=> Add withyoutube.com as a new public suffix

.travis.yml
* .travis.yml: Add file
When hooked to Travis-CI, public_suffix_list.dat and tests/test_psl.txt
will be tested using https://github.com/rockdaboot/libpsl.
The tests includes testing with libicu (IDNA2008 UTS#46),
libidn2 (IDNA2008) and libidn (IDNA2003).
=> Use Travis-CI for testing with libpsl

public_suffix_list.dat
Pantheon operates a Platform as a Service (PaaS) supporting Drupal and WordPress Content Management Systems (CMS).  Host names under getpantheon.com and pantheon.io are under administrative control of Pantheon prospective customers, customers, partners, and others.
=> Adding Pantheon Systems PaaS domains

public_suffix_list.dat
ngrok.com/ngrok.io is a public reverse-proxy/tunneling service that allows developers to run expose local servers behind a firewall at a public endpoint. More info here: https://ngrok.com
=> Add ngrok.io

public_suffix_list.dat
Regarding to [wikipedia](https://en.wikipedia.org/wiki/.an) and a [source document](http://www.versgeperst.com/nieuws/268890/internetextensie-an-stopt-per-31-juli.html), `.an` domains has been discontinued.
=> Remove .an domains from the list

public_suffix_list.dat
This is in preparation of our DNS & HTTP(S) rollout, that will enable users to serve content on `${username}.hashbang.sh`.
I am part of #!'s sysadmin team.
=> Add hashbang.sh

public_suffix_list.dat
cloudfunctions.net is to be used to host 3-rd party code.
=> Add cloudfunctions.net to Google, Inc. section

public_suffix_list.dat
http://registry.gy states:
Presently, .gy; .co.gy; .com.gy; .org.gy; .net.gy; .edu.gy and .gov.gy domain names. are available for registration.
=> Add additional entries to .GY ccTLD

public_suffix_list.dat
Citrix is offering subdomains under xenapponazure.com which resolve to customer managed deployments of Citrix XenApp.
=> Add xenapponazure.com to the PSL

public_suffix_list.dat
Added dynv6.net as public suffix for the dynv6.com service.
Will update a TXT record pointing to this PR URI for verification. Feel free to contact me at dom@digineo.de.
=> adding dynv6 dynamic DNS service

public_suffix_list.dat
This also removes .doosan, as per ICANN.
zTestRegistry is not included; it is a bug in the ICANN datafeed.
=> Add new gTLDs up through 03/01/2016

.gitignore, .travis.yml, linter/README.md, linter/pslint.py, linter/pslint_selftest.sh, linter/test_allowedchars.expected, linter/test_allowedchars.input, linter/test_dots.expected, linter/test_dots.input, linter/test_duplicate.expected, linter/test_duplicate.input, linter/test_exception.expected, linter/test_exception.input, linter/test_punycode.expected, linter/test_punycode.input, linter/test_section1.expected, linter/test_section1.input, linter/test_section2.expected, linter/test_section2.input, linter/test_section3.expected, linter/test_section3.input, linter/test_section4.expected, linter/test_section4.input, linter/test_spaces.expected, linter/test_spaces.input, linter/test_wildcard.expected, linter/test_wildcard.input, tests/tests.txt, tools/convert_tests
This adds a python PSL linter for use with Travis CI.
The former 'linting' of the PSL done via libpsl pulls in a full C project on each commit to publicsuffix/list. Configure, compile and link steps are a waste of CPU time in comparison with this simple python script.
Simone (@weppos) opened a [wiki page](https://github.com/weppos/pslint/wiki/Rules) with a bunch of tests to perform.
The python script performs all test except 'Order' (the last one in the list).
=> Add pslint.py linter and use it on Travis CI

public_suffix_list.dat
We offer our webhosting customers a so called preview domain to view their website. This helps to test the website before changing the name server. Each customer gets a *.cyon.link domain.
E.g.: My website http://snowgarden.ch/ can also be reached on http://snowgard.cyon.link/
We offer our webhosting customers a site creation tool (aka sitebuilder). Similar too cyon.link we offer each sitebuilder customer their own publish subdomain => *.cyon.site.
E.g.: An example site that one of my coworkers put together can be found on http://hasi.cyon.site/index.html
Cookie isolation. An other beneficial reason is that we can issue SSL certificates with Let's Encrypt [1] more easily and not hitting the per domain rate limit.
The use case can be compared to herokuapp.com or herokussl.com. …
=> Adds cyon.link and cyon.site to private domains

public_suffix_list.dat
Peplink and Pepwave routers use *.mypep.link for DDNS service.
=> Add mypep.link to public suffix list

public_suffix_list.dat
hzc.io will soon be hosting arbitrary users' sites underneath it, and each of them could have different login mechanisms. For cookie isolation, we'd like to put it on the PSL.
=> Add hzc.io

public_suffix_list.dat
Daplie, Inc provides Domains, Dynamic DNS, and a home Cloud server. Subdomains of daplie.me are available to DIY users, hobbyists, and developers.
=> Add daplie.me

public_suffix_list.dat
we (and users of our nsupdate.info service) ran into issues with letsencrypt.org's rate limiting for tls certificate requests.
it might also help for other purposes, so people can know these hosts do not all belong to me / to the nsupdate.info domain, but shall be considered independent.
=> add nsupdate.info dyndns service

public_suffix_list.dat
P.P.COM (ppcom.fr via denti.site) offers our dentist customers in France a website hosted in a domain *.chirurgiens-dentistes-en-france.fr.
Specifically, each dentist has a domain in the form of dr-<firstname>-<lastname>.chirurgiens-dentistes-en-france.fr
E.g.: dr-dupond-pierre.chirurgiens-dentistes-en-france.fr
One can see other examples of sites in denti.site
Reason for inclusion
Cookie isolation. Each dentist can partially modify himself his site so cookie isolation is needed for security reason.
We could also get rid of our wildchar certificate and obtain easily (using Let's Encrypt for instance) a certificate per active website
=> Adds chirurgiens-dentistes-en-france.fr to private domains

public_suffix_list.dat
After an email exchange with the registry, I got the list of official suffixes (#140).
It's not completely clear how many registered second level domains there are for the .ZM zone, therefore I went with listing all the suffixes _and_ the TLD itself.
/cc @gerv @sleevi for cross-review
---
Closes #140
=> Update .ZM TLD

public_suffix_list.dat
These two domains are used to provide subdomains for different users.
Confirmation may be sought at the admin email address or registrant email address for these domains.
=> Add compute.estate and alces.network for Alces Software Ltd

public_suffix_list.dat
Viprinet is a manufacturer of VPN Routers. SERIALNUMBER.router.management (.management is a new public TLD) are used to access our routers. In future, we also wish to support Let's encrypt, which requires this domain to be on the public suffix list. Subdomains of the vipri.net domain are internally used for update servers and the likes, and therefore also should be on the public suffic list.
=> Viprinet customer router management domains

public_suffix_list.dat
Hey there!
We'd like to add on-aptible.com to the Public Suffix List. The admin email on the whois records for the domain can be used to reach us (through whoisguard).
Is there anything else needed from us? 
Thanks!
--
cc @fancyremarker @aaw
=> Add on-aptible.com public suffix

public_suffix_list.dat
> we (and users of our nsupdate.info service) ran into issues with letsencrypt.org's rate limiting for tls certificate requests.
related (nerdpol.ovh is a dyndns domain for nsupdate.info) to https://github.com/publicsuffix/list/pull/93
=> add nerdpol.ovh part of nsupdate.info dyndns service

public_suffix_list.dat
While merging #212 I missed that the sort order was incorrect; fix it.
=> Correctly sort DNSHome before Dreamhost

public_suffix_list.dat
[Pagefog](http://pagefog.com) is a hosting service that provisions cloud servers and sets up website hosting, DNS with the `pgfg.com` domain, and SSL certificates with LetsEncrypt.
```bash
$ host -t TXT _psl.pgfog.com
_psl.pgfog.com descriptive text "https://github.com/publicsuffix/list/pull/141"
```
=> Added pgfog.com to the public suffix list

public_suffix_list.dat
potager.org is a French non-profit organization hosting websites run by independent groups and individuals.
=> Add domains hosted by potager.org

public_suffix_list.dat
Boxfuse users receive boxfuse.io subdomains which can optionally be secured by Let's Encrypt certificates
=> Added boxfuse.io domains

public_suffix_list.dat
Hasura issues sub-domain based project urls to its customers. These projects should not be able to set cookie anywhere else other than on their own root domain. Like herokuapp.com
=> Add hasura-app.io to the list

public_suffix_list.dat
Please add `*.magentosite.cloud` to the list.
This entry covers all the regional deployments of the Magento Cloud product (`us.magentosite.cloud`, `eu.magentosite.cloud`, `ap.magentosite.cloud`, etc.). The customer subdomains running arbitrary code are subdomains of these regional deployment domains, as in `myapp.us.magentosite.cloud`.
=> Add *.magentosite.cloud

public_suffix_list.dat
Customer level domains given for accessing their company on cloud telephone systems.
=> Add ClearVox Domains

public_suffix_list.dat
SBE network solutions GmbH offers our customers (mostly schools) dynamic DNS services under the domains logoip.de and logoip.com (e.g., hostname.logoip.de).
For security reasons (cookie isolation) and to provide them with the ability to create Let's Encrypt certificates, we would like to add those domains to the public suffix list.
=> Add logoip.de and logoip.com domains

public_suffix_list.dat
evennode.com provides web hosting. The following subdomains are used to host users' sites.
=> Add evennode.com

public_suffix_list.dat
TuxFamily is now automatically provisioning certificates via Let's Encrypt for their users on thousands of subdomains of tuxfamily.org. We don't use cookies on the main site (tuxfamily.org) so being added here is perfectly fine for us.
=> Add tuxfamily.org domains

public_suffix_list.dat
Remove kosa.kumamoto.jp as requested on June 17th.
> While we registered a domain name,
> please update the "jp" section of PUBLIC SUFFIX LIST.
> (remove "kosa.kumamoto.jp")
> 
> The following three files relevant to update the list are attached to
> this e-mail.
> 
>    - public_suffix_list.dat.original.txt   (original list, 2016/6/17)
>    - public_suffix_list.dat.new.txt        (updated list)
>    - public_suffix_list.dat.diff.txt       (diff file)
=> Update .JP as requested by info@jprs.jp

public_suffix_list.dat
certmgr.org is supposed to become an aiding domain for server management. Any server operator is supposed to be able to obtain a subdomain *.certmgr.org for his server pointing back to the server under the operator's control. In order to avoid the misuse of content on foreign subdomains, strict cookie separation is required.
=> Add certmgr.org

public_suffix_list.dat
Agnat sp o.o. is a hosting provider that provides its customers
websites within beep.pl domain, DNS, and SSL Certificates with
LetsEncrypt
=> Add beep.pl into PSL

public_suffix_list.dat
callidomus is providing it's customers access to their homes with dyndns and https (with let's encrypt cert).
They are using XXXX.mycd.eu to access their homes.
=> callidomus: please add mycd.eu

public_suffix_list.dat
Customers can freely add subdomains of those domains to their apps on our hosting platform, Galaxy.
=> Add Meteor Galaxy managed domains (meteorapp.com)

public_suffix_list.dat
* Fix the sorting for potager.org
* Remove trailing whitespace from cn-north-1.compute.amazonaws.com.cn
* Fix the sorting for Amazon AWS
=> Cleanup bad entries

public_suffix_list.dat
At backplane we issue subdomains of backplaneapp.io to customers in order to bootstrap configuration and testing. These customers are mutually-untrusting. We do not intend to ever serve anything on the backplaneapp.io apex domain directly.
=> add backplaneapp.io

public_suffix_list.dat
GitLab.io is used for GitLab Pages and thus allows arbitrary users to have subdomains. You can see the official request to add GitLab.io on [our issue tracker](https://gitlab.com/gitlab-com/infrastructure/issues/230).
=> Add gitlab.io

public_suffix_list.dat
static.land lets users create sites at *.static.land, *.dev.static.land, and *.sites.static.land.
Creating the needed TXT records now.
=> add static.land

public_suffix_list.dat
Stackspace allows customers to launch and use big data tools hosted on subdomains of stackspace.space.
=> Add stackspace.space

public_suffix_list.dat
QNAP is providing dyndns services to their customers on the .myqnapcloud.com domain. I work in QNAP. Please add myqnapcloud domain to public suffix list
=> Please add myqnapcloud domain to publicsuffix list

public_suffix_list.dat
> This email is to authenticate the request to remove lib.de.us
> from the PUBLIC section of the public suffix list and to add
> it to the PRIVATE section only.
> We need this done because Chrome does not respect wildcards
> for names in the ICANN (public) section, but they do in the
> PRIVATE section.
Closes https://github.com/publicsuffix/list/issues/243
/cc @sleevi @gerv can you please cross-review?
/cc @ehmoore
=> Move lib.de.us to the private section

public_suffix_list.dat
Add ro.im and shop.ro private domains. We allow registration of second level domains using ro.im and shop.ro.
=> Add ro.im and shop.ro

public_suffix_list.dat
This is the response I got from the registry:
> We have the following second level domains:
> 
>     co.mz, net.mz, org.mz, ac.mz, gov.mz, adv.mz,
>     mil.mz and edu.mz.
> 
> But we also have some domain names which are directly registered
> under .mz like uem.mz, tvcabo.mz, the domains are mostly operators
> like ISPs, but they are few because we are not registering under
> .MZ anymore.
I added all the suffixes in the patch, and I also listed mz as there are some domains registered at the second level domain.
/cc @gerv @sleevi
=> Update .MZ suffixes according to registry

public_suffix_list.dat
[alwaysdata](https://www.alwaysdata.com) is a web hosting company. Each of our customers has a alwaysdata.net subdomain.
=> Add alwaysdata.net.

public_suffix_list.dat
Add domain taifun-dns.de to public_suffix_list.dat.
This domain provides dynamic dns for our customers.
=> Add taifun-dns.de

public_suffix_list.dat
Domains under `wellbeingzone.co.uk`, `wellbeingzone.eu` and `ptplus.fit` are issued to Revitalised Ltd. customers to serve our SaaS instances.
For example; `customer.wellbeingzone.co.uk`.
DNS verification will be added once I get the pull request ID.
=> Add Revitalised Limited private domains

public_suffix_list.dat
We provide a hosting service, and subdomains of the domain are issued to mutually untrusting parties.  Customers can choose their subdomain during [registration](https://console.opencraft.com/registration/).
=> Add opencraft.hosting

public_suffix_list.dat
TransIP provides different internet services, among them domain name registration and webhosting. When a customer registers a domain name and webhosting packet, we also provide an additional domain name containing the transurl{.nl, .be, .eu} suffix _(so if a customer uses the domain example.nl, we would provide example.nl.transurl.nl)_. This extra domain name will also point to the customer's website.
Many different websites are hosted on subdomains under the transurl{.nl, .be, .eu} suffix and customers have almost full control over what they will be hosting. The main reason that we want our suffixes to be added is to prevent customers to make super cookies.
=> Add transurl.nl

public_suffix_list.dat
Our domain `myfusion.cloud` is used to provide custom sub-domains in the form of `acme.myfusion.cloud` to our SaaS customers for product "Fusion Intranet" (www.fusion-intranet.com).
The customers using the service have no affiliation to each other and should therefore be separated.
=> Add myfusion.cloud

public_suffix_list.dat
We use this domain at [SourceLair](https://www.sourcelair.com) to provide domains for our users, so that they can view their websites. Possible domains:
- https://4fv6pjnu.apps.lair.io/
- https://ufwlp5am.apps.lair.io/
We use this domain at [SourceLair](https://www.sourcelair.com) for our https://stolos.io product, where each customer has it's own subdomain and can create dynamic subdomains below it. Possible domains:
- https://sourcelair.stolos.io/
- https://akalipetis.sourcelair.stolos.io/
=> Add apps.lair.io and stolos.io to the list

public_suffix_list.dat
We issue subdomains of now.sh to our customers for their deployments.
=> Add now.sh

public_suffix_list.dat
Subdomains under shiftedit.io are issued to shiftedit users.
e.g: customer.shiftedit.io
DNS verification added
=> Add shiftedit.io

public_suffix_list.dat
Subdomains of these zones are used by our DynamicDNS and IPv4/6 Portmapping Service feste-ip.net
TXT Records for all zones are set.
=> DynamicDNS and Portmapping Service Feste-IP.net

public_suffix_list.dat
Enonic is using Enonic.io as a base for out Cloud hosting service, and every customer project is delegated its own domain name under enonic.io and customer.enonic.io. To get cookie handling rignt and to circumvent lets encrypts rate limits, we need to add enonic.io and customer.enonic.io to the public suffix list.
=> Added enonic.io domain to the private list

public_suffix_list.dat
These domains are used by users for dynamic DNS.  These domains need to be added since Yombo Gateway software will host websites. Requesting these be added to this so that cookies don't transfer between 3rd level (and lower) domains.
The domains in this pull request all use ns1.yombo.net and ns2.yombo.net as the name servers to validate that Yombo controls these domains.
=> Added dynamic domains for Yombo

public_suffix_list.dat
*Adding ap-south-1.compute.amazonaws.com EC2 domain
*Adding s3-ap-south-1.amazonaws.com and s3.ap-south-1.amazonaws.com S3 domains
=> AWS ap-south-1 EC2 and S3 domains

public_suffix_list.dat
This subdomain is used to automatically assign hostnames to event attendees. They should not be allowed to set cookies on the parent domain or interfere with Let's Encrypt rate limiting on the parent domain or other subdomains. Users can effectively trigger arbitrary domain registration under this subdomain.
I am the systems administrator in charge of DNS under party.eus and am authorized by the domain owner to request this change. As proof of domain control, I've added a TXT record under the registered domain:
```
$ dig TXT party.eus
[...]
party.eus.              600     IN      TXT     "Please add user.party.eus to the PSL (marcan@euskalencounter.org / GitHub marcan-euskal)"
```
Please let me know if this is sufficient documentation.
=> Add user.party.eus to PRIVATE section

public_suffix_list.dat
on-web.fr is the subdomain for our shared hosting customers.
=> Added on-web.fr (Planet-Work shared hosting)

public_suffix_list.dat
These domains have now been made available to Nicaraguan corporations.
Examples of this are:
- loto.ni
- nic.ni
=> Added .ni as a valid user registerable domain.

public_suffix_list.dat
Hi. My name is Alf from the TwoDNS Support Team. TwoDNS is a Dynamic DNS Service located in Germany. All the domains to add are used by our users. Over the last period of time we got more and more requests, to add our domains to the public suffix list. The main purpose is the usage of the Let's Encrypt Service.
The DNS records are set, just need to edit the number for the pull - the domain sort order hopefully fits, too. By the way I had problems to get the wanted result by using dig, maybe my cache - but with host -t on our ns1.register-it.net it shows up. Hope that will be fine for validation.
=> Request to add TwoDNS TLD's used by users

public_suffix_list.dat
We are the owner of ro.com. It's a domain name and we have build a website on it. It's not a public suffix. Please merge this pr, so that we can apply https cert for our domain.
=> Remove ro.com from Public Suffix List

public_suffix_list.dat
We provide thousands of our (and not only our) users with domain names in .inf.ua, .ltd.ua and .cc.ua zones. So we belive these domains should be added to PRIVATE section of public suffix list. Thank you.
=> Add inf.ua, ltd.ua and cc.ua to PRIVATE section

public_suffix_list.dat
Adding in homeoffice.gov.uk for organisational subdomain management,
also relates to GDS principles https://www.gov.uk/service-manual/technology/managing-domain-names
=> Adding homeoffice.gov.uk

public_suffix_list.dat
Follow up to GH-359. See also GH-380.
This commit is also related to
https://bugzilla.mozilla.org/show_bug.cgi?id=1134993 https://github.com/publicsuffix/list/commit/601e0b094957f3289be53e50a5dbdcad6d744e6a
However, I need to follow up with FAITID because it's not clear the
boundary between the current list of .SU suffices, and the provided one.
=> Add .RU and .SU geographic suffixes owned by FAITID

public_suffix_list.dat
evennode.com provides web hosting. The following subdomains are used to host users' sites.
=> Additional evennode.com domains

public_suffix_list.dat
I know the guidelines say that I must cite an official website among other things. Unfortunately, I cannot find such information anywhere. I'm thinking about putting up a site educating people about Zimbabwe's DNS system but I doubt such a site would be deemed official for the purposes of this list.
I have been putting off submitting this pull request for over a week now since I do not have the correct references to cite but this has been nagging me. See, domains are kind of my thing and Zimbabwe is my beloved country :) I would love to have an accurate representation of our domain extensions in this list.
I work for Web Enchanter P/L, a company which runs [Name.co.zw](https://www.name.co.zw), one of the biggest domain registrars in Zimbabwe. I also maintain a [Rust …
=> Update .zw extensions

public_suffix_list.dat
*.daplie.me is used by users who are registering publicly accessible domains. *.localhost.daplie.me is used for corresponding client-side applications running locally that in some cases directly mirror the *.daplie.me domains. We do not want the localhost application cookies, local storage, etc to be shared among apps as they are by different authors and should not necessarily have access to the same data.
We are aware that similar results could be achieved by using localhost.*.daplie.me, however, there are also applications in which localhost.foo-user.daplie.me should be secured from foo-user.daplie.me, so we're covering both use cases.
=> add localhost.daplie.me for client-side applications

public_suffix_list.dat
Hello!
Currently, our access (DSL/Fiber) customers can choose their subdomain under xs4all.nl to use for their own services.  We wish to move them to xs4all.space; the subdomains will be under control of our customers.
By listing them here, they will have all the benefits listed on https://publicsuffix.org/learn/.
As for authentication purposes, as the Guidelines describe, I added a TXT-record with the URL of the Pull-request to the zone:
```
_psl.xs4all.space.      86400   IN      TXT     "https://github.com/publicsuffix/list/pull/397"
```
Kind regards,
Daniël Mostertman,
System Engineer at XS4ALL Internet bv
=> Add xs4all.space to PSL (for XS4ALL Internet bv's access customers)

public_suffix_list.dat
cya.gg is the routing domain that provides users of the FOSS project [Ulterius ](https://ulterius.io) with sub-domains that point to their self-hosted instances. Their sub-domain is generated when an account is registered, the software handles keeping their IP synced to their domain. 
A example domain for instance is: 2aafcc59.cya.gg, which would point to the public address of their server. 
The addition of cya.gg to the public suffix list will help ensure new and current users of Ulterius are able to keep their domains isolated from one another.
=> Add cya.gg to the private section.

public_suffix_list.dat
c66.me is the domain used by Cloud 66 (www.cloud66.com) customers to power their websites.
=> Adding c66.me customer domain for Cloud66

public_suffix_list.dat
We provide application hosting services to customers using subdomains like `[customername].[shared server].awdev.ca` and `[customername].[shared server].advisor.ws`
For example, `james0208.force1.awdev.ca` and `james.us1.advisor.ws`
=> Add Advisor Websites domains

public_suffix_list.dat
These domains are used for contributor web pages (e.g. https://puiterwijk.fedorapeople.org/) and services that contributors run in our OpenStack cluster (e.g. https://copr.fedorainfracloud.org/).
=> Add Fedora People and Cloud domains

public_suffix_list.dat
Matthew Hardeman of IPiFony Systems, Inc. is requesting addition of private domain "ipifony.net" to the private section of the PSL.  This is requested as IPiFony intends to have various customer system subdomains (across different, mutually untrusting customers) in the ipifony.net domain.
I can be reached with any questions via email at mhardeman@ipifony.com.
=> Requesting addition of ipifony.net

public_suffix_list.dat
We're a hosting company and we plan to use the domain `uber.space` for our customers. Every account will get its own `mydomain.uber.space` domain. For cookie isolation it would be great to get included in the public suffix list.
=> Add uber.space

public_suffix_list.dat
Adding vapor.cloud and vaporcloud.io to the list.
Clients are going to create subdomains, and we are providing Let's Encrypt certificates. I can't explain much here because of NDA, for further details, contact me directly.
Example domains:
subdomain1.vapor.cloud
subdomain2.vapor.cloud
sub1.subdomains1.vapor.cloud
sub2.subdomains2.vapor.cloud
The same goes for vaporcloud.io
=> Add vapor.cloud to list

public_suffix_list.dat
This domain is used to host customer applications on individual subdomains. We would like to prevent these applications from storing cookies both within their own subdomain and on the root domain.
=> Adding quipelements.com domain for Quip.

public_suffix_list.dat
we will use letsencrypt to give us free domain users
submitted by whois contact email
we have added TXT records
[root@r310 kencorp]#
[root@r310 kencorp]# dig txt _psl.url.tw +short
"https://github.com/publicsuffix/list/pull/398"
[root@r310 kencorp]# dig txt _psl.mymailer.com.tw +short
"https://github.com/publicsuffix/list/pull/398"
[root@r310 kencorp]# dig txt _psl.twmail.cc +short
"https://github.com/publicsuffix/list/pull/398"
[root@r310 kencorp]# dig txt _psl.twmail.net +short
"https://github.com/publicsuffix/list/pull/398"
[root@r310 kencorp]# dig txt _psl.twmail.org +short
"https://github.com/publicsuffix/list/pull/398"
and this passed Travis-CI check  
we have set the status checks. But for the old pull request no way to show
https://travis-ci.org/publicsuffix/list/builds/201746015 …
=> add private domain in public suffix

public_suffix_list.dat
hello at PSL!
as a shared hosting provider we have interest in a PSL listing for multiple reasons.
1. customers have their own subdomains (possibly for one or all of the given domains) assigned upon registration. Preventing privacy-damaging "supercookies" is a main goal here. We have more than 200k of such subdomains at the moment.
2. also we plan to use let's encrypt here, having these domains in the PSL allows great advantages for the signing process.
3. document.domain property restrictions are considered an advantage as well.
you may contact me via "security @bplaced dot n-e-t" as given by the guidelines, also the DNS records were set up.
Thanks a bunch!
kind regards,
Miroslav Bozic
bplaced CEO
https://www.bplaced.net/
=> Add bplaced network domains

public_suffix_list.dat
Please add `*.platformsh.site` to the list.
This entry covers additional regional deployments of Platform.sh product (notably `nl-1.platform.sh`, `de-1.platform.sh`, etc). These subdomains run arbitrary code.
=> Add *.platformsh.site

public_suffix_list.dat
There is another reserved extension directly attached on nc TLD: nom.nc
See http://www.cctld.nc/ind?man=2
.nc : generic extension
.asso.nc : reserved for associations
.nom.nc : reserved for the private individuals who shall wish to to deposit their surname.
=> Add nom.nc - official second-level domain

public_suffix_list.dat
Customers of Google's Cloud Platform will have the option of creating a Public DNS name, e.g. foo.cloud.goog., for a customer project with name "foo". To avoid cross-project cookie interference, we add cloud.goog to the PSL.
=> add cloud.goog

public_suffix_list.dat
Reason: x-domain, browsers. Customers generate their own subdomains. Contact: hello@nodum.io
=> Add nodum.io aPaas

public_suffix_list.dat
Adding domain for filegear.me
filegear.me is used by Filegear Inc. (www.filegear.com) for our customer's devices. Each of these device has a sub-domain name that is generated dynamically during device initialization and registration, e.g. vxnaowas.filegear.me.
=> Add Filegear domain

public_suffix_list.dat
Those domains are used by our clients for accessing their private installations of our product http://www.barsy.bg 
Since each installation is on a separate server on the client premises they are also used as dynamic dns in case the client IP is changed. 
The information in the program contains sensitive financial information, so for security reasons cookies should not be shared between installations.
=> Added Lukanet Ltd domains in the list

public_suffix_list.dat
Subdomains used in NGI HPC Cloud services. Arranging for appropriate TXT records now.
=> metacentrum.cz cloud subdomains

public_suffix_list.dat
Subdomains of this domain are used by completely independent entities to host arbitrary websites.
=> Add flynnhosting.net for Flynn

public_suffix_list.dat
Hi,
we're a web hosting provider and cloud company and have multiple domains where customers can freely register subdomains. We have over 400k subdomains currently active on the listed domains.
We'd like to be included in the PSL for security concerns (mainly cookies).
DNS-Records will be set up soon.
Best,
Phillipp
=> Add lima-city/TrafficPlex domains

public_suffix_list.dat
Customers of the mytuleap solution will have a subdomain like customer.mytuleap.com to host their forge.
We want to be sure cookies are correctly set.
=> Add mytuleap.com domain

public_suffix_list.dat
Hello!
Currently, our access (DSL/Fiber) customers have their own subdomain under cistron.nl and demon.nl to use for their own services.  
By listing them here, they will have all the benefits listed on https://publicsuffix.org/learn/.
As for authentication purposes, as the Guidelines describe, I added a TXT-record with the URL of the Pull-request to the zone:
```
_psl.cistron.nl.    86400    IN    TXT    "https://github.com/publicsuffix/list/pull/457"
_psl.demon.nl.      86400    IN    TXT    "https://github.com/publicsuffix/list/pull/457"
```
Kind regards,
Daniël Mostertman,
System Engineer at XS4ALL Internet bv
=> Add cistron.nl/demon.nl to PSL (for XS4ALL Internet bv's access customers)

public_suffix_list.dat
info.cx offers free sub domains through afraid.org. I would like to add the domain to the suffix list to ensure cookies are handled properly.
=> Add info.cx

public_suffix_list.dat
Greeting Sir,
First, thank you for your notification in #451 and apologize for my misunderstanding.
We're DrayTek Corp. And this is our website: https://www.draytek.com/ 
Our company is building DDNS service to provide customers register their domain, right now we are planning using *.drayddns.com for DDNS service.
By adding the "drayddns.com" into Public Suffix List, the Let's Encrypt could identify domain correctly and each customer could get their own certificate.
examples of our domain list below:
https://vkao-home.drayddns.com
https://smallkai.drayddns.com
If there anything we need to do or we can do, please inform us. 
Thank you for taking your time and have a nice day. :D
=> Added "drayddns.com" into public suffix list.

public_suffix_list.dat
Boomla ([boomla.com](https://boomla.com/)) allows anyone to create and host websites on `*.boomla.net` subdomains. We want to prevent users from adding cookies to `boomla.net`.
Example customer domain: [psl.boomla.net](http://psl.boomla.net/)
=> Add boomla.net domain

public_suffix_list.dat
Netlify deploys websites for customers under subdomains at *.netlify.com and *.bitballoon.com.
Examples:
* https://opensmc.netlify.com/
* https://special-tester.bitballoon.com
Adding DNS records when we have a PR number.
=> Add Netlify domains

public_suffix_list.dat
evennode.com provides web hosting. The following subdomains are used to host users' sites.
=> evennode.com domains

public_suffix_list.dat
Hello PSL,
We are a hosting company and we are willing to add we.bs to the list. We are doing this for two reasons.
1. We have a lot of clients using .we.bs subdomains, so this will solve cookie problems.
2. We have recently integrated Let`s Encrypt SSLs to our system. Having we.bs in the list will improve the signing process.
The requested TXT record has been added:
> dig TXT _psl.we.bs 
> "htt<span>ps://github.com/publicsuffix/list/pull/452"
Regards,
Victor Velchev
admin@liquidnetlimited.com
=> Add we.bs domain

public_suffix_list.dat
Subdomain variants of this domain name are used across our network to provide legitimate temporary staging environments to our customers.
Sub 6 Limited is the parent company that owns this domain name.
=> Add temp-dns.com

public_suffix_list.dat
P.P.COM (ppcom.fr via byen.site) offers our customers a website hosted in a domain *.byen.site
E.g.:  dupond-pierre-taxi.byen.site
Reason for inclusion
Cookie isolation. Each customer can partially modify himself his site so cookie isolation is needed for security reason.
=> Add byen.site

public_suffix_list.dat
We are setting up a dynamic dns service for users of our server software, which is installed by the user on a computer in their home. For example I might register a domain like tmm1.remote.getchannels.com, for easy remote access to the server I setup at home. 
Since we use the getchannels.com domain for marketing and subscription purposes, the intent of this PR is to ensure that cookies are not shared between user sub-domains and our root domain, nor across different user domains (by using a `.remote.getchannels.com` supercookie).
My understanding is that a cookie set on `.getchannels.com` would _not_ be made available to `tmm1.remote.getchannels.com`, but I would appreciate if someone can confirm my understanding of how the PSL works.
We also plan to use Let's Encrypt to issue SSL …
=> Add channelsdvr.net to the PSL

public_suffix_list.dat
Updating existing entry and adding all region specific ones.
The wildcard entry is incorrect. We give our customers CNAMEs with these TLDs.
=> Update AWS Elastic Beanstalk domain suffixes.

public_suffix_list.dat
The reasoning is exactly the same as for my previous pull request https://github.com/publicsuffix/list/pull/420 (copied below).
> We allow costumers to create projects using the <project>.wedeploy.io (for production) and <project>.wedeploy.me for local development.
> Some examples:
> http://whatsapp.wedeploy.io/
> http://supermarket.wedeploy.io/
> http://boilerplate-auth.wedeploy.io/
> http://boilerplate-liferay.wedeploy.io/
> http://metrics.wedeploy.io/
> These are all different sites, from different costumers (in this case, they are demos), not related with each other (besides the fact they are run on our infrastructure).
> Docs: http://wedeploy.com/docs/
I will comment here when DNS authentication is ready and remove this comment.
=> Adding wedeploy.sh domain

public_suffix_list.dat
The debian.net namespace is open for registration by all members of the
Debian project.  Services underneath debian.net should not necessarily
trust each other.
=> Add debian.net

public_suffix_list.dat
.htc has been removed effective 2017-10-24
sources:
1) https://www.iana.org/domains/root/db/htc.html
2) https://github.com/whois/ianawhois/commit/1691d737b8f30c1f217d8db64793e65234a6552b
=> remove .htc TLD

public_suffix_list.dat
Hi,
These are the new SDLs managed by nic.bo.
I do not work for nic.bo, I just want to contribute to the project.
For more information you can go to https://nic.bo/delegacion2015.php#h-1.10 .
Unfortunately I was not able to find documentation in English.
As you can see, the new SDLs are alredy working.
pro-imagen.tecnologia.bo
Also, since 2011 gov.bo it is not a valid SDL.
In the same document  https://nic.bo/delegacion2015.php#h-1.10, below the social domains you can check the restricted domains:
Dominio.gob.bo
Dominio.edu.bo
Dominio.mil.bo
Dominio.int.bo
As you can see, gov.bo is not longer available.
Added  web.bo, also listed in the same document.
Here are some other contributions that I have made to the list:
https://github.com/publicsuffix/list/pull/406 …
=> Add social domains - NIC.bo

public_suffix_list.dat
This adds a new domain for SensioCloud (https://sensio.cloud/).
This new entry covers all the regional deployments of the SensioCloud product (eu.s5y.io, us.s5y.io, etc.). The customer subdomains running arbitrary code are subdomains of these regional deployment domains, as in myapp.us.s5y.io.
The new domain will gradually replace the existing one.
DNS update coming just after the PR number has been attributed.
=> Add s5y.io

public_suffix_list.dat
1Password service creates separate subdomain for every team and family account. For example, `https://agilebits.1password.com` and `https://anotherteam.1password.com` should be treated as different sites.
1Password has three geographical regions: 1password.ca, 1password.com, and 1password.eu.
=> Add 1Password domains

public_suffix_list.dat
Nimbus Hosting (nimbushosting.co.uk) are a web hosting company and we use `*.nh-serv.co.uk` for server hostnames.
=> Add nh-serv.co.uk to list file

public_suffix_list.dat
We expose our users' device-hosted web services at `<device id>.resindevice.io` and in our staging environment at `<device id>.devices.resinstaging.io`. We'd like to ensure these devices are isolated from one another in browsers.
~~I'm organising authentication for these domains at the moment, I'll update here shortly once we've got the `_ps1` TXT records set up.~~ `_ps1` TXT records for these domains are now live.
=> Add resin.io device domains as public suffixes

public_suffix_list.dat
These domains are used by the production and staging OpenShift instances run by Fedora Infrastructure and run apps by various application owners.
=> Add Fedora Openshift app domains

public_suffix_list.dat
Public users will be able to spool up a personal environment which should not share cookies etc... with other subdomains.
=> Adding scrysec.com to public suffix to properly partition publicly created subdomains

public_suffix_list.dat
Request to add `webhosting.be` and `hosting-cluster.nl` as private domains.
Customers get a subdomain assigned for each purchased hosting package which can be used to access their website.
=> Add Combell domains

public_suffix_list.dat
I made a mistake when I added alwaysdata.net in #292: our customers have their own subdomain foo.alwaysdata.net, so the suffix is actually alwaysdata.net, not *.alwaysdata.net.
=> Fix alwaysdata.net.

public_suffix_list.dat
As announced on 2017 December 18 here https://aws.amazon.com/about-aws/whats-new/2017/12/announcing-the-aws-eu-paris-region/ a new AWS region has been launched, adding new public suffixes
=> Add new Paris AWS region

public_suffix_list.dat
kenic has started accepting registrations for second-level domains: http://www.kenic.or.ke/index.php/en/ke-second-level-domain/second-level-domain
Thus, in addition to the pre-existing second-level suffixes we need to add the TLD
=> Update .ke suffixes to include second-level domains

public_suffix_list.dat
The domain should be removed from the list since it restricts us from using CloudFront system-wide.
=> Remove myfusion.cloud domain

public_suffix_list.dat
YesCourse (https://yescourse.com) allows users to create online Academies which are hosted on our servers but can be available on the users own domain or a sub domain of official.academy chosen by them
eg.
https://yescourse.official.academy/ 
https://courseschool.official.academy/
...
Adding official.academy to the PSL will prevent any sub-domain from setting cookies on official.academy
=> Add official.academy to the PSL

public_suffix_list.dat
This is a domain we use to host customer subdomains.
Each customer has a username and can create [username].schokokeks.net and [something].[username].schokokeks.net. Thus for security reasons it makes sense to separate them cookie-wise.
=> add schokokeks.net

public_suffix_list.dat
Hi. 2038.io is a domain for users of 2038.host, a hosting service. Users can host any web content on their corresponding subdomain, so we need this to avoid cookies leaking.
=> Add 2038.io

public_suffix_list.dat
cloud66.ws is a domain used by Cloud 66 (www.cloud66.com) customers to power their websites.
=> Adding cloud66.ws customer domain for Cloud66

public_suffix_list.dat
We are hosting Atlassian products -as-a-Service under the linkyard.cloud domain.
Since each customer is run on his own instances I'd be great to have cookie isolation. The customer sites are run as xyz.linkyard.cloud.
=> Add linkyard.cloud

public_suffix_list.dat
Mozilla offers free subdomains for Web of Things gateways in people's homes as part of an experimental "Project Things". See https://iot.mozilla.org
Each subdomain points at a different web server under a different user's control so cookies should not be shared across subdomains.
Please use email authentication if possible.
Thanks!
=> Add mozilla-iot.org

public_suffix_list.dat
xxxxxxxxxxxxxxxx.cloudeity.net subdomains are given out to users of Cloudeity.
=> Add Cloudeity customer subdomains

public_suffix_list.dat
The domain se.com is under new ownership and is no longer a public suffix. This will be reflected with the correct TXT DNS records shortly.
This is a correction for pull request 613.
=> Removed se.com

public_suffix_list.dat
The new region was announced in February here: https://aws.amazon.com/jp/blogs/news/osaka-local-region-launch-2018feb/
=> Add AWS ElasticBeanstalk Osaka, JP region

public_suffix_list.dat
The institutes of the Russian Academy of Sciences use a custom subdomains of **ras.ru**
=> Add ras.ru domains

public_suffix_list.dat
jino.ru is a hosting provider. We give our customers free subdomains of myjino.ru domain.
Examples:
some-user.myjino.ru
project1.6e7oz.landing.myjino.ru
vps1.zm9y1.vps.myjino.ru
We need to restrict cookie sharing between these subdomains.
=> Add myjino.ru

public_suffix_list.dat
Gwiddle.co.uk is a privately-owned domain. The Gwiddle Foundation issues subdomains to mutually-untrusting parties for the purposes of free student web hosting, and as such we request that it is added to the private section of the Public Suffix List.
=> Include gwiddle.co.uk

public_suffix_list.dat
`cleverapps.io` is a privately-owned domain.
* When a client deploys an app on Clever Cloud, it is assigned a domain like this: [random-UUID].cleverapps.io
* A client a also set a specific [myname].cleverapps.io.
All subdomains of cleverapps.io are considered mutually-untrusting parties/clients.
As such we request that it is added to the private section of the Public Suffix List.
Examples of apps deployed by clients:
* https://adminer.cleverapps.io/
* http://streamline-emojis.cleverapps.io
* https://json2caseclass.cleverapps.io/
=> Add cleverapps.io (Clever Cloud)

public_suffix_list.dat
Arranging for appropriate TXT records now.
This is a public IaaS cloud service for academic use, provided by cooperation of https://www.metacentrum.cz/en, http://www.ics.muni.cz/ and https://www.cerit-sc.cz/.
The DNS structure is flat. Domain names used for virtual machines provisioned in the cloud are for instance:
snowflake252.flt.cloud.muni.cz
snowflake215.flt.cloud.muni.cz
We will also deploy a Dynamic DNS service, where users will be able to set up DNS names for their virtual machines. These names will go to the usr zone, i.e., the names will be:
foo.usr.cloud.muni.cz
bar.usr.cloud.muni.cz
=> cloud.muni.cz cloud subdomains

public_suffix_list.dat
YunoHost is a server operating system aiming to make self-hosting accessible to everyone.
We provide dyndns subdomain  `noho.st` and `nohost.me` to our users, allowing them to self-host some services without the need of buying a personnal domain and with the advantage to bypass some ISPs dynamic IP and to configure DNS entries automatically.
It could be very usefull, if browser could correctly manage those subdomains (cookies, highlighting the subdomain, sorting by subdomain and not all the domain ). We want these services to be recognized as a known public suffix and dyndns services too.
```
dig +short TXT _psl.noho.st
"https://github.com/publicsuffix/list/pull/615"
```
and
```
dig +short TXT _psl.nohost.me
"https://github.com/publicsuffix/list/pull/615"
```
Here are the validated `make …
=> Add YunoHost DynDns domains: nohost.me & noho.st

public_suffix_list.dat
Subdomains of this are assigned to customers and their servers. Things like cookies set for one of the subdomains must not be set across subdomains.
=> Adding customer.speedpartner.de

public_suffix_list.dat
We provide users with the ability to host clusters of databases.
Typically these are in the form of:
* `https://node-a.user-1234.dbs.ravendb.net`
* `https://node-b.user-1234.dbs.ravendb.net`
* `https://node-c.user-1234.dbs.local.ravendb.net`
Each cluster (the `user-1234` portion) is per user, and then there is a subdomain below that for each node that is operated by them.
We want to get clear separation between different users.
=> Adding ravendb.net subdomains

public_suffix_list.dat
[Nucleos Inc](https://nucleos.com) is a company behind [PortableCloud](https://portablecloud.net), a "local cloud solution" (currently something like a platform with an app store so that non-technical users can easily set up whatever software they want on our custom server devices), which is currently expanding its featureset to remote access, supporting SSL certificates, even in LANs and so on. Currently our software is deployed at various schools in Zimbabwe, India and evaluated in countries like Mauritius, rural Mexico and so on.
I can't _really_ give you proper examples due to the nature of our platform (no proper authentication yet and so on), but every device is given its own domain under the pcloud.host suffix (like piotr.pcloud.host, which is currently routed to a tunnelling …
=> pcloud.host

public_suffix_list.dat
Now-DNS is a free provider of Dynamic DNS domains that users can register sub domains against. This pull request covers all our current domains.
=> Add Now-DNS suffixes

public_suffix_list.dat
The blackbaudcdn.net domain is used to host static assets for applications within the Blackbaud ecosystem.
=> Added blackbaudcdn.net private domain to PSL

public_suffix_list.dat
FASTVPS EESTI OU (https://fastvps.ru/) provides technical domains for it's customers.
fastvps-server.com - for the server itself, so customer can use domain like s056579f2.fastvps-server.com
fastpanel.direct - for our hosting panel, that can be installed on the server
These 3-rd level domains are not related with each other and should not trust each other.
Every domain is used by different server and typically by different customer.
=> Add fastvps-server.com for FASTVPS EESTI OU

public_suffix_list.dat
Update TLDs from nic.it in compliance with version 7.1 of Italian Regulation assignation.
In particular:
regions are listed in Appendix A;
provinces are listed in Appendix B.
Municipalities are omitted due to limits and constraints of PSL. See also #519 for further discussions.
=> nic.it - update regions and provinces

public_suffix_list.dat
[Datto](https://www.datto.com/) is a backup and disaster recovery company. We sell backup appliances and we'd like to add Let's Encrypt based HTTPS support with custom domains to them.  
```
$ dig TXT _psl.dattolocal.net +short
"https://github.com/publicsuffix/list/pull/624"
$ dig TXT _psl.mydatto.net +short   
"https://github.com/publicsuffix/list/pull/624"
$ dig TXT _psl.dattoweb.com +short   
"https://github.com/publicsuffix/list/pull/624"
$ dig TXT _psl.dattolocal.com +short
"https://github.com/publicsuffix/list/pull/624"
$ dig TXT _psl.dattorelay.com +short
"https://github.com/publicsuffix/list/pull/624"
$ dig TXT _psl.mydatto.com +short 
"https://github.com/publicsuffix/list/pull/624"
```
Edit: All domain TXT records have now been propagated.
=> Add dattoweb.com, dattorelay.com, dattolocal.net, dattolocal.com, mydatto.net and mydatto.com

public_suffix_list.dat
[Memset Hosting](https://www.memset.com) is a dedicated and VPS hosting provider. These are domains we use for customer hosted dedicated servers and VPS's (ie. `customer.memset.net`)
We need these domains to be in the public suffix list as each subdomain is specific to one customer server: cookie isolation is required.
Additionally, we have recently had memset.net blacklisted by Google - one of our customers was hosting malware, and the whole *.memset.net domain was blacklisted. We have been advised by StopBadware to request addition to the Public Suffix list:
> Google assumes by default that a domain is used entirely by one entity. If instead you are using this domain as a TLD, you should have the owner of the domain request its addition to the Public Suffix List: …
=> Add memset.net and miniserver.com

public_suffix_list.dat
utwente.io is used for GitLab Pages and thus allows arbitrary users to host websites on arbitrary subdomains.
Update - TXT record is in place:
```
$ dig txt _psl.utwente.io +short
"https://github.com/publicsuffix/list/pull/626"
```
=> Add utwente.io

public_suffix_list.dat
dnstrace is a user-run domain intelligence data aggregator. We will be running untrusted nodes in subdomains under bci.dnstrace.pro, so cookie isolation is important to ensure no rogue node could steal information. Thus, the request.
TXT record is also in place:
`;QUESTION
_psl.bci.dnstrace.pro. IN TXT`
`;ANSWER
_psl.bci.dnstrace.pro. 299 IN TXT "https://github.com/publicsuffix/list/pull/630"`
=> Submit bci.dnstrace.pro

public_suffix_list.dat
Members can create their own subdomains using either
[member].mayfirst.org or [member].mayfirst.info.
=> These domains are used to host member subdomains.

public_suffix_list.dat
Co & Co is a bespoke software developer for a wide variety of clients.
We use otap.co as a domain for test environments, acceptance environments and on the fly hosting of short and long lived experiments. We would like to add stronger (cookie) isolation between these domains, as well as benefit from any additional effects the PSL might bring us in terms of browser UI, etc.
Domain names on otap.co always have four labels total in the form of {project}.{client}.otap.co, hence the wildcard.
Examples:
a.x.otap.co should be isolated from b.x.otap.co. Both should also be isolated from c.y.otap.co.
inner1.a.x.otap.co is not isolated from a.x.otap.co.
=> Add *.otap.co

public_suffix_list.dat
This removes the duplicate .travel entry now that it's in the ICANN
gTLD feed, along with cleaning up some trailing whitespace that came
in from ICANN.
=> Correct linter issues

public_suffix_list.dat
freedesktop.org is a site hosting a number of diverse open-source communities.
=> Add freedesktop.org

public_suffix_list.dat
CloudyCluster is used to quickly spin up HPC Clusters and manage them from mobile or desktop devices.   We assign subdomains of cloudycluster.net to clusters that our customers start.  For security reasons, different clusters should not share cookies and other data.  We use cloudycluster.net only for our customers' subdomains.
=> Add cloudycluster.net

public_suffix_list.dat
Similar to `hasura-app.io`, with the introduction of new `app` TLD, Hasura allocates sub-domains on `hasura.app` for the clusters users create on it's platform. A user should not be able to set cookies across these subdomains, apart from their own.
=> Adds hasura.app to the list

public_suffix_list.dat
`s` suggests that `https` was meant and not `http`
=> htts://www.transip.nl => https://www.transip.nl

public_suffix_list.dat
We would like to remove our domain's entry from the PSL.
=> Remove stackspace.space from PSL

public_suffix_list.dat
Adding ponpes.id, new TLD in Indonesia. Ref: https://pandi.id/en/domain/registration-requirements
=> Update public_suffix_list.dat for Indonesia

public_suffix_list.dat
====
Organization Website: https://www.apigee.com
Apigee is a an API management company that provides a suite of tools to allow customers to manage their new and existing API programs.
====
Apigee currently provides cloud hosted developer portals with user generated content, all of which are served by the base domain apigee.io by default. User generated content may contain JavaScript which will allow creation of supercookies. To mitigate cross site cookie vulnerabilities, creation of supercookes must be limited in all major browsers.
Once merged, you can verify by navigating to https://apiportal-publicsuffixtest.apigee.io/. This portal is setup to configure a supercookie called `badcookie` against the base domain `apigee.io`.
DNS …
=> Added apigee.io

public_suffix_list.dat
Automattic (https://automattic.com/) is a company behind WordPress.com, where the users can create websites and blogs for free and enhance those sites with our premium services.
We provide subdomains in wpcomstaging.com and go-vip.co to our users (e.g. site100.wpcomstaging.com, site20.wpcomstaging.com, demo-site1-com.go-vip.co), allowing them to upload custom WordPress plugins or themes so they can test their site before they are migrated to a self-hosted environment.
As any subdomain can be operated by any user, we would like proper handling of the namespace by browsers (to ensure cookie isolation, highlighting the subdomain, SSL management). This will prevent super cookie violation on the main wpcomstaging.com and go-vip.co domain and isolate each subdomain from the others in the same …
=> Add wpcomstaging.com and go-vip.co to the PSL

public_suffix_list.dat
[Siteleaf](https://www.siteleaf.com) is a content management system that allows users to create and host websites with *.siteleaf.net subdomains. 
```
$ dig TXT _psl.siteleaf.net
https://github.com/publicsuffix/list/pull/655
```
=> Add siteleaf.net

public_suffix_list.dat
[Read The Docs](https://readthedocs.org/) is an organization that hosts documentation for free software projects.
$SUBDOMAIN.readthedocs.io is used to host documentation for projects using this service.
This inclusion in the PSL was [discussed and OK'ed with the upstream readthedocs folks](https://github.com/rtfd/readthedocs.org/issues/2233).
This is now done:
~~~~
0 dkg@alice:~$ dig +short -t TXT _psl.readthedocs.io
"https://github.com/publicsuffix/list/pull/722"
0 dkg@alice:~$ 
~~~~
i have run the syntax checker with this patch included.
=> Add readthedocs.io

public_suffix_list.dat
====
I am the former technical contact for .LS, dating back to when the registry was operated by Rhodes University - my previous employer. I left Rhodes in 2016, and technical operations of .LS were passed from Rhodes University to LsNIC, the Lesotho Network Information Centre, in April 2018.
Whilst I was the registry operator, I maintained the referenced Wikipedia page (cf https://en.wikipedia.org/w/index.php?title=.ls&action=history).
Post the transfer to LsNIC, the new registry operator has set up a dedicated web page at http://www.nic.ls/. Whilst there is (unfortunately) not a complete list of second level domains there, it can be derived from a combination of the information on Wikipedia, the policy published on LsNIC's page, and some other bits of LsNIC's …
=> Update subdomains of .ls

public_suffix_list.dat
I represent the registry for the .nl ccTLD (SIDN) and would like to draw your attention to bv.nl.
To the best of our knowledge that private domain has never properly qualified for the public suffix list, even though there might have been good intentions when the initial request was made. We are not the owner of the private domain bv.nl. We did try to contact the current owner and discuss the matter, but we received no response. Since we are not sure what the correct procedures are in this case, I'd like to ask for extra attention (and help) from the maintainers of this list.
=> Proposal to remove bv.nl

public_suffix_list.dat
I am the general manager for a hosting company (https://lifetime.hosting) and we provide subdomains (SLDs) to our customers. For cookie isolation, SSL management, Direct URL translation, and the inevitable developments in security, it would be great to get added to the public suffix list.
[~]# dig +short TXT _psl.co.business
"ht tps://github.com/publicsuffix/list/pull/598"
[~]# dig +short TXT _psl.co.education
"h ttps://github.com/publicsuffix/list/pull/598"
[~]# dig +short TXT _psl.co.technology
"ht tps://github.com/publicsuffix/list/pull/598"
[~]# dig +short TXT _psl.co.events
"ht tps://github.com/publicsuffix/list/pull/598"
[~]# dig +short TXT _psl.co.financial
"ht tps://github.com/publicsuffix/list/pull/598"
[~]# dig +short TXT _psl.co.network
"ht …
=> Add lifetime.hosting domains

public_suffix_list.dat
====
Organization Website: https://stdlib.com
My name is Jacob Lee, and I'm the co-founder of Standard Library and am in charge of platform development and architecture. The CEO of the company, Keith Horwood (@keithwhor), is the original owner of the domain and he will also comment here.
Standard Library is an API development, management, and hosting platform. We support tens of thousands of developers and work closely with Slack and Stripe. Both organizations are active investors in the company and users of the product.
====
Each user on our platform receives a unique hostname with the base domain where we host their deployed APIs. Though many APIs on the platform act as either JSON responses or webhook endpoints, a significant number …
=> Add api.stdlib.com

public_suffix_list.dat
One of the products our company develops allows users to publish websites as subdomains under the `bss.design` domain name. Examples:
```
https://example.bss.design
https://foobar.bss.design
```
This pull request adds `bss.design` to the list.
=> Add bss.design

public_suffix_list.dat
fix outdated link for `.fr` sectorial domains
https://www.afnic.fr/fr/produits-et-services/le-fr/les-domaines-sectoriels-en-fr-11.html
=> Update .FR sectorial domains

public_suffix_list.dat
====
Automattic (https://automattic.com/) is a company behind WordPress.com, where the users can create websites and blogs for free and enhance those sites with our premium services.
This PR is identical to the information contained within https://github.com/publicsuffix/list/pull/719 but is only seeking to add an additional TLD.
====
We provide subdomains in go-vip.net to our users (e.g. demo-site1-com.go-vip.net), allowing them to upload custom WordPress plugins or themes so they can test their site before they are migrated to a self-hosted environment.
As any subdomain can be operated by any user, we would like proper handling of the namespace by browsers (to ensure cookie isolation, highlighting the subdomain, SSL management). This …
=> Add go-vip.net.

public_suffix_list.dat
A GitLab pages hosting instance for the Rochester Institute of Technology community. 
* Proper handling of the namespace by browsers.
* Prevention of cookie based attacks among others. Sites hosted under this namespace will be controlled by any number of students, staff, faculty, etc.
```
dig TXT _psl.git-pages.rit.edu +short
"https://github.com/publicsuffix/list/pull/690"
```
Rochester Institute of Technology is a university in Rochester, New York. More information can be found at [our website](https://www.rit.edu/overview/rit-in-brief).
I am a full time staff member in the Information Technology Services organization, primarily working with Research Computing but assist with other areas as well.
=> Added git-pages.rit.edu

public_suffix_list.dat
====
Organization Website: https://syncloud.it
Syncloud allows to run popular cloud services (mail, files, messaging ...) on personal devices
====
Syncloud DDNS server (syncloud.it) hosts user's DNS records and also has its own site at syncloud.it.
So In practice allthesebelong todifferent people:
user1.syncloud.it
user2.syncloud.it
www.syncloud.it
Also any incorrectly set cookie sharing across all three is not safe as different users can run anything under *.[user].syncloud.it
=======
```
dig +short TXT _psl.syncloud.it
"https://github.com/publicsuffix/list/pull/727"
```
make test
=========
OK
=> Syncloud dynamic dns service

public_suffix_list.dat
====
Organization Website: https://rancher.com
Rancher Labs develops an open-source Kubernetes distribution and management platform called Rancher and similar container product called Rio.
I am [Vincent Fiduccia](https://github.com/vincent99), software architect at Rancher.
====
We are adding a feature to automatically provide each user cluster with a `<service name>.<random user-id>.on-rancher.cloud` (and `on-rio.io`) DNS entry, so each `user-id` is a mutually untrusting third-party that should not be able to set cookies readable by each other.  We also plan to provide Let's Encrypt wildcard certs for each `user-id`.
=======
```
dig +short TXT _psl.on-rancher.cloud …
```
=> Add on-rio.io and on-rancher.cloud

public_suffix_list.dat
====
[GOV.UK Platform as a Service](https://www.cloud.service.gov.uk) is the UK Government's PaaS - these are the domains we use for client applications, ie. `appname.cloudapps.digital` / `appname.london.cloudapps.digital`.
====
We need these domains to be in the public suffix list as each subdomain is specific to one client application: cookie isolation is required.
Additionally, one of our subdomains has been flagged as phishing, which has resulted in the whole *.london.cloudapps.digital being flagged as dangerous. We would like an explicit distinction between independent subdomains.
=======
```
dig +short TXT _psl.cloudapps.digital
"https://github.com/publicsuffix/list/pull/###"
```
```
dig +short TXT …
```
=> Add GOV.UK PaaS client domains

public_suffix_list.dat
====
Organization Website: https://www.nabucasa.com
Nabu Casa offers Home Assistant Cloud, a cloud extension for the open source home automation platform [Home Assistant](https://www.home-assistant.io). With Home Assistant Cloud, local running Home Assistant instances can be accessed via the internet and integrate with cloud-only services like Alexa and Google Assistant.
I am Paulus Schoutsen, the founder of Nabu Casa and Home Assistant.
====
To allow remote connection to Home Assistant instances, we're soon giving users the option to access their local running instance under the domain `https://<domain-id>.ui.nabu.casa`. These domains will be served by their local Home Assistant instances, not under our control. Home Assistant allows …
=> Add Nabu Casa

public_suffix_list.dat
====
Organization Website: http://alboto.ca (in development)
Alboto Inc is a new Canadian corporation that specializes in software, network and marketing solutions for bars and restaurants. It is the official distributor of Barsy software www.barsy.bg for Canada
====
Barsy software solution integrates dynamic DNS solution for each individual client that has the software installed on premises. The main goal is for the client to be able to access his installation easily remotely. Since it deals with sensitive financial and personal clients information security is a major concern and Cookies should be not cross between individual subdomains. The company developed the software has the same solution for its Europe clients and it has proven …
=> Add private dynamic DNS solution for barsy.ca

public_suffix_list.dat
====
Organization Website: https://www.teckids.org
Teckids e.V. is a (probably the) free software youth organisation, that aims at both getting free software in use by young people and in schools, and at getting young people involved in free software contribution. We are a non-profit organisation based in Germany.
====
EduGit.org is a Git hosting service using GitLab and for use in schools, for educational software, etc., with terms of use tailored to the legal needs when working with minors and in classrooms. It provides GitLab pages, where projects can public static web content under a subdomain named after their self-chosen namespace. PSL inclusion is thus important for cookie security and security-related browser UI improvement.
DNS …
=> Add EduGit pages under edugit.org.

public_suffix_list.dat
====
Organization Website: https://repl.it
I'm an engineer at Repl.it.
Repl.it is an online programming environment allowing users to host terminal apps, static sites, and web apps.
====
By default we host all user created websites under `repl.co` and terminal apps under `repl.run` when a user doesn't provide their own domain. We would like to isolate cookies and be able to use Let's Encrypt with user's domains.
=======
```
dig +short TXT _psl.repl.co
"https://github.com/publicsuffix/list/pull/748"
```
and
```
dig +short TXT _psl.repl.run
"https://github.com/publicsuffix/list/pull/748"
```
make test
=========
result of `make test`:
```
PASS: …
```
=> Add repl.co and repl.run

public_suffix_list.dat
====
Organization Website: https://render.com
Render is a cloud provider that hosts websites and apps for developers. We provide subdomains on `app.render.com` and `onrender.com` to allow users to host sites publicly without needing to buy or configure a custom domain. We also issue SSL certificates for individual subdomains to import into CDN providers.
I am the founder and CEO of Render.
====
We'd like `app.render.com` and `onrender.com` on the PSL so we can restrict cookies on user subdomains. Our Let's Encrypt limit has already been raised so this only affects customer website security.
=======
```
dig +short TXT _psl.app.render.com
"https://github.com/publicsuffix/list/pull/761"
```
```
dig +short TXT …
```
=> Add user domains for Render: https://render.com

public_suffix_list.dat
====
Organization Website: https://new.siemens.com/global/en/company/about/businesses/mobility.html
We are part of an innovation department for innovative mobility solutions based on cloud technologies and microservice architectures.
====
mo-siemens.is is used for GitLab pages to allow arbitrary project groups to have subdomains.
=======
```
dig +short TXT _psl.mo-siemens.io
"https://github.com/publicsuffix/list/pull/762"
```
make test
=========
`make test` completed without errors
=> Add mo-siemens.io

public_suffix_list.dat
====
Organization Website: https://protocol.ai
Protocol Labs develops [IPFS](https://ipfs.io/), which allows end-users to resolve content they have published on the IPFS network using content-based addressing. This content can be resolved by web browsers and other clients in the form `http://<hash>.ipfs.dweb.link` or `http://<peerid>.ipns.dweb.link`.
I am an engineer at Protocol Labs and represent the Infrastructure team, responsible for hosting the IPFS Gateways that provide this proxying service. Note that this PR was made as a fork on my personal GitHub account, not the Protocol Labs GitHub organization.
====
Because end-users can publish arbitrary content, we would like to sandbox every subdomain as much as possible (cookies, etc). …
=> Add dweb.link

public_suffix_list.dat
====
Organization Website: https://thingdust.com
We are a small startup that provides a solution for measuring the occupancy of workplace environments (primarily shared desk and meeting rooms). Every customer gets his own instance with his own subdomain provided by us.
====
We currently have prod.cust.thingdust.io (and the same pattern for out testing systems) registered, to provide each customer his own subdomain which must not interfere with the other customers instances.
The inclusion in this list gives each customer his own cookie scope.
We now want to change the prod url gradually from *.prod.cust.thingdust.io to *.thingdustdata.com
=======
```
dig +short TXT _psl.thingdustdata.com …
```
=> added thingdustdata.com

public_suffix_list.dat
====
Organization Website: https://glitch.com
Glitch is the friendly community where everyone can discover and create the best stuff on the web. For more information about Glitch head over to https://glitch.com/about/
====
Everyone can go to https://glitch.com and create an app. We provide every app on Glitch with its own `glitch.me` subdomain.
We'd like to be included in the list to improve our cookie security. 
=======
```
dig +short TXT _psl.glitch.me
"https://github.com/publicsuffix/list/pull/769"
```
make test
=========
I ran the tests and they pass 👍
=> Add glitch.me to the PSL

public_suffix_list.dat
====
Organization Website: https://clovyr.io
I'm co-founder and CTO of a company called Clovyr. We are working on making self-hosted applications easier to use, including without needing to register domains or know what A/CNAME records are.
====
We would like to assign `foo-bar.wnext.app` and `baz-quux.wnext.app` to different people who we (Clovyr) don't particularly trust, and who don't trust each other, and so we would like to:
- Avoid cookies being set on `wnext.app` under any circumstance
- Allow users to provision LE certs, but still be subject to the LE rate limits for their "domain". (A single abusive user maxing out the limits for `wnext.app` would be very bad.)
- Let the many tools that rely on PSL know to treat `wnext.app` as …
=> Add wnext.app

public_suffix_list.dat
====
Clerk provides user authentication as a service to developers. 
Organization Website: https://www.clerk.dev
I am the founder and CEO of Clerk.
====
Our domains should be in the PSL for both cookie security and to mitigate Let's Encrypt issuance limits.
Our service relies on us sharing a domain with our user so we can set cookies on their behalf.  For example, if their app is hosted on `www.example.com`, we will host our service on `accounts.example.com`.  With this structure, `accounts.example.com` can set a cookie with `Domain=example.com;` and `www.example.com` will be able to read it.
To mirror this behavior in development and staging environments, we provide subdomains on `*.lcl.dev` and `*.stg.dev` respectively.  As an …
=> Add Clerk user domains

public_suffix_list.dat
====
Organization Website: https://www.gehirn.co.jp
Gehirn Inc. is a Web hosting provider.
I am a software engineer working for Gehirn Inc.
====
gehirn.ne.jp
------------
Gehirn RS2 Plus <https://www.gehirn.jp/rs2plus/> by Gehirn Inc. allocate one level sub-domain <example.gehirn.ne.jp> and its wildcard <*.example.gehirn.ne.jp> in gehirn.ne.jp for our customers to host any their content on that domain name.  Therefore by adding gehirn.ne.jp to the PSL we want to protect our customers from accidentally sharing their secret Cookie among other users. 
usercontent.jp
---------------
Gehirn Inc. are distributing and will distribute user-uploaded content like photo image and untrusted third-party content from a subdomain in usercontent.jp. We …
=> Add gehirn.ne.jp and usercontent.jp for Gehirn Inc.

public_suffix_list.dat
====
Organization Website: https://www.privacytools.io (https://git.privacytools.io)
@privacytoolsIO is a socially motivated organization providing resources and services to promote privacy online. We are currently operating a [public GitLab instance](https://git.privacytools.io) for our users and our team's use, and will be offering free subdomains with GitLab Pages.
====
We will be implementing GitLab Pages on the `prvcy.page` domain, allowing any user to publish their own static site hosted on our GitLab instance to a subdomain of their choosing. Being added to the PSL is a [recommended task](https://docs.gitlab.com/ee/administration/pages/#add-the-domain-to-the-public-suffix-list) for GitLab Pages administrators to prevent browsers …
=> Add prvcy.page

public_suffix_list.dat
====
Organization Website: https://linode.com
Linode is a public cloud / infrastructure as a service company. 
====
We provide automatic rDNS entries for our Linode and Nodebalancer services using the subdomains *.members.linode.com and *.nodebalancer.com. We are submitting this request so that browsers and tools such as password managers or LetsEncrypt can correctly handle these domains.
=======
```
dig txt +short _psl.members.linode.com
"https://github.com/publicsuffix/list/pull/810"
dig txt +short _psl.nodebalancer.linode.com
"https://github.com/publicsuffix/list/pull/810"
```
make test
=========
```
./pslint_selftest.sh;                     \
./pslint.py …
```
=> Add Linode Suffixes

public_suffix_list.dat
====
Carrd is a free/paid platform for building responsive one-page sites.
Organization Website: https://carrd.co
====
Carrd allows users to publish sites to multiple domain suffixes (including `carrd.co` itself, eg. `mysitename.carrd.co`) so we're requesting inclusion in the PSL primarily to ensure cookie isolation/security for sites hosted on the platform.
=======
```
$ dig +short TXT _psl.carrd.co
"https://github.com/publicsuffix/list/pull/816"
```
```
$ dig +short TXT _psl.crd.co
"https://github.com/publicsuffix/list/pull/816"
```
```
$ dig +short TXT _psl.uwu.ai
"https://github.com/publicsuffix/list/pull/816"
```
make test
=========
Ran and passed!
=> Add Carrd suffixes

public_suffix_list.dat
====
Zitcom A/S is a hosting and cloud provider.
Organization Website: https://www.zitcom.dk/
====
The three domains is used for hostnames and reverse DNS for customer servers.  And for that reason the domains should be added to the list, so that cookies is not shared and to get better/more correct Let's Encrypt limits etc.
=======
```
dig +short TXT _psl.basicserver.io
"https://github.com/publicsuffix/list/pull/817"
```
```
dig +short TXT _psl.enterprisecloud.nu
"https://github.com/publicsuffix/list/pull/817"
```
```
dig +short TXT _psl.virtualserver.io
"https://github.com/publicsuffix/list/pull/817"
```
make test
=========
Ran – no problems.
=> Add Zitcom domains

public_suffix_list.dat
====
Organization Website: https://www.b-data.io
I'm a Data Scientist at b-data using GitLab (https://gitlab.b-data.ch) to serve repositories to my customers.
====
b-data.io is used for GitLab pages to allow arbitrary users to have subdomains.
=> Add b-data.io

public_suffix_list.dat
====
Organization Website: https://urbit.org
I am Mark Staarink, engineer at [Tlon](https://tlon.io), the company working on Urbit. It comprises several separate components, which include Azimuth (decentralized identity) and Arvo (personal server).
====
Azimuth and Arvo will provide identity owners with their own subdomain under `azimuth.network` and `arvo.network` respectively. For example, `palfun-foslup.arvo.network`.
In the case of Azimuth, the identity subdomain will serve as a unique log-on point for that specific identity.  
In the case of Arvo, the identity subdomain will point to the owner's personal server, which can serve arbitrary content.
=======
```
> dig +short TXT _psl.azimuth.network …
```
=> Add azimuth.network and arvo.network

public_suffix_list.dat
====
Organization Website: https://port53.io
I'm the owner of port53, which will run a Anycast DNS Network.
====
Because user.dyn53.io is used for customers, Cookie Security would be crucial.
=======
```
dig +short TXT _psl.dyn53.io
"https://github.com/publicsuffix/list/pull/820"
```
make test
=========
I could not getting make test work. It throws errors (make not list errors)
=> Add dyn53.io

public_suffix_list.dat
====
Balena is a complete set of tools for building, deploying, and managing fleets of connected Linux devices. We provide infrastructure for fleet owners so they can focus on developing their applications and growing their fleets with as little friction as possible.
Organization Website: https://balena.io
====
As part of our service we offer a unique URL per device that each user can use to host custom content like admin interfaces etc. We'd like to protect these domains by including their suffix in the public suffix list.
=======
```
dig +short TXT _psl.balena-devices.com
"https://github.com/publicsuffix/list/pull/814"
```
```
dig +short TXT _psl.balena-staging-devices.com …
```
=> Add Balena domains

public_suffix_list.dat
====
https://www.cloudera.com
I am an engineer at Cloudera, Inc. We sell enterprise software in both shrink-wrapped and cloud service forms.
====
As part of Cloudera's cloud service offering, we are adding a feature
to provide customer's access to their resources under a
<customer>.cloudera.site domain.
As we need to provide strong boundaries between customers, we should
add cloudera.site to the public suffix list to ensure that
* Cookies cannot be set to apply across customers
* Certificate generation activity of one customer doesn't affect others
=======
```
dig +short TXT _psl.cloudera.site
"https://github.com/publicsuffix/list/pull/829"
```
make test
=========
Ran the tests and they passed.
=> Add cloudera.site

public_suffix_list.dat
====
Organization Website: http://www.iodata.com/  (US)    https://www.iodata.jp/ (Japan)
I am a software engineer at I-O DATA DEVICE, INC.
We mainly develop and sell PC peripherals.
iobb.net is a dynamic DNS service available from our products.
====
We would like to improve cookie security for customers using iobb.net.
=======
```
dig +short TXT _psl.iobb.net @8.8.8.8
"https://github.com/publicsuffix/list/pull/828"
```
make test
=========
The result is fine.
```
minagawa@devsrv3:~/GitHub/list$ make test
./pslint_selftest.sh;                     \
./pslint.py ../public_suffix_list.dat;
test_NFKC: OK
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: …
```
=> Add iobb.net

public_suffix_list.dat
Firebase Hosting (owned by Google) recently rolled out support for the web.app domain as a public suffix, this adds it to the list.
====
Organization Website: https://firebase.google.com/docs/hosting
Firebase Hosting is a web hosting provider owned by Google. It offers CDN-backed web hosting for static assets and dynamic content powered by Google Cloud Functions.
====
Cookie security, Let's Encrypt issuance, and our existing shared domain `firebaseapp.com` is already on the PSL.
=======
make test
=========
=> Add web.app for Google

public_suffix_list.dat
====
Organization Website: https://www.cloudflare.com
Cloudflare is a cloud computing company and edge provider. We have a product, [Argo Tunnel](https://www.cloudflare.com/products/argo-tunnel/) that lets users set up a reverse proxy on their origins to safely expose local servers to internet traffic via a hostname they configure with Cloudflare. Recently, we [announced a free tier](https://blog.cloudflare.com/a-free-argo-tunnel-for-your-next-project/) for this project. Users can now expose their local servers to the internet on a subdomain of TryCloudflare.com by running `cloudflared tunnel`. This sets up a randomly-chosen subdomain like `a-big-cool-dog.cloudflare.com` for the user's server. As such, each subdomain should be treated as its own host for cookie …
=> Add trycloudflare.com to Cloudflare's suffixes

public_suffix_list.dat
Organization Website: https://handshake.org/
Handshake is a decentralized, permissionless naming protocol compatible with DNS where every peer is validating and in charge of managing the root zone with the goal of creating an alternative to existing Certificate Authorities. Its purpose is not to replace the DNS protocol, but to replace the root zone file and the root servers with a public commons. The Handshake protocol maintains the root zone file in a decentralized manner, making the root zone uncensorable, permissionless, and free of gatekeepers.
I am a developer for this project.
====
Names registered in Handshake are reflected in to the hs.zone and hs.run zones, allowing clients not running Handshake to look up these names. Because multiple parties can …
=> Add Handshake zones

public_suffix_list.dat
====
Organization Website: https://hostbip.com
'HostBip' is a 'PDNR' (Private Domain Name Registry), allowing 3rd parties to register domain names in a variety of domain name extensions / suffixes.
====
'HostBip' has an existing section in the 'Public Suffix List', and is updating it's section to include additional domain extensions / suffixes in it's portfolio.
This request is seeking to add these to the PSL so the individuals / institutions operating under these suffixes can gain access to services such as Let's Encrypt, Cloudflare and that other third party systems may better be able to identify the level at which the personal/private name has been registered.
=======
```
dig +short TXT _psl.ng.school …
```
=> Update Hostbip Section

public_suffix_list.dat
====
Organization Website: https://www.webhare.com/
We are WebHare bv; we develop a CMS named WebHare which can be self-installed or is offered as a SaaS. We are a commercial organization but working on open-sourcing (parts of) our CMS - which will be done through https://www.webhare.dev/
The reason we're requesting the PSLs for webhare.dev and not webhare.com is that we're trying to separate the open source/product bits and the company bits.
====
We want to use subdomains under `test.webhare.dev` for continuous integration tests (we have a few automated tests that specifically test cross-domain logins, and require separate cookie jars) and for test and acceptance versions of websites for ourselves and our customers (which require …
=> Add *.webhare.dev

public_suffix_list.dat
====
Organization Website: https://lelux.fi/
Organization providing services powered by free software. (related: https://libreho.st/)
I'm the administator of Lelux.fi.
====
Going to be used for a public GitLab Pages instance.
=======
```
dig +short TXT _psl.lelux.site
"https://github.com/publicsuffix/list/pull/849"
```
make test
=========
I ran the test and it passed succesfully.
=> Add lelux.site

public_suffix_list.dat
This updates contact for SymfonyCloud domains.
Symfony SAS became independent in 2018: https://symfony.com/blog/a-business-model-for-symfony
SymfonyCloud, the product using those domains is operated by Symfony SAS: https://symfony.com/blog/meet-the-newest-member-of-the-symfony-family-symfonycloud
DNS update coming after the PR number has been attributed.
=> Update contact for SymfonyCloud

public_suffix_list.dat
====
Organization Website: https://www.zadna.org.za/content/page/domain-information
NZDNA is the administrator of the .ZA top-level domain, the country-code top-level domain for South Africa. I am submitting this change on behalf of Mark Elkins <mje@posix.co.za> who asked for assistance with git-wrangling during the Africa DNS Forum being held this week in Gaborone, Botswana. My name is Joe Abley, and I like to be helpful.
====
.ZA is already included on the PSL. This change is to add the second-level domain NIC.ZA alongside the other, existing second-level domains. NIC.ZA was added on 5 February 2018 but the PSL has not been updated since then to reflect that change. NIC.ZA should be listed in the PSL for the same reason as all the …
=> add nic.za

public_suffix_list.dat
====
Education Services Australia (ESA) is a national not-for-profit company owned by the state, territory and Australian Government education ministers. ESA is the sole organization authorised to deliver registrar services for edu.au and its child zones by .au Domain Administration Ltd (auDA), the policy authority and industry self-regulatory body for the .au domain space as endorsed by the Australian Government.
Organization Websites:
Primary - https://www.esa.edu.au
Registrar services - https://www.domainname.edu.au
====
The PSL currently only includes the national level 2LD and the Australian state and territory level 3LDs for edu.au. The edu.au domain space has expanded in recent years to includes a number other 3LDs and also 4LDs …
=> Update to include all current 3LD/4LD edu.au suffixes

public_suffix_list.dat
As technical contact of the current domain owner, I request removal of his domains from the list.
Subdomains are no longer available/for sale/active, this project has been abandoned by the previous owner long ago.
I will add dns records for authentication ASAP:
```
dig +short TXT _psl.nuernberg.museum
"https://github.com/publicsuffix/list/pull/XXXX"
```
```
dig +short TXT _psl.nuremberg.museum
"https://github.com/publicsuffix/list/pull/XXXX"
```
=> Remove non-public museum domains

public_suffix_list.dat, tools/newgtlds.go, tools/newgtlds_test.go
The tooling added in https://github.com/publicsuffix/list/pull/834 had support for removing gTLDs previously added to the `public_suffix_list.dat` file when the registry contract was terminated: https://github.com/publicsuffix/list/blob/38eb4c45a1e47cb7daa8eee202e3993e4ffcade5/tools/newgtlds.go#L162-L164
In practice I see gTLDs that are removed from the root zones but do not have a terminated contract. E.g. consider `.bnl`, which was marked removed on `2019-07-30` but has `"contractTerminated": false`:
```
$ curl https://www.icann.org/resources/registries/gtlds/v2/gtlds.json 2>/dev/null |  jq '.gTLDs | .[] | select(.gTLD=="bnl")'
{
"applicationId": "1-1257-44806",
"contractTerminated": false,
"dateOfContractSignature": "2014-07-24",
"delegationDate": "2015-06-26",
"gTLD": "bnl", …
```
=> tools: update newgtlds.go to filter removed gTLDs

public_suffix_list.dat
====
Organization Website:  https://www.synology.com 
Synology Inc. is a corporation that specializes in Network-attached storage (NAS) appliances.
====
Hello, I'm engineer from synology.com and we would like to add a new domain for our public dynamic dns service. (refer to #62)
=======
```
dig +short TXT _psl.direct.quickconnect.to
"https://github.com/publicsuffix/list/pull/867"
```
make test
=========
Here are the validated make test
https://paste.yunohost.org/igonijahum.coffeescript
=> Add new domain to Synology dynamic dns service.

public_suffix_list.dat
====
Organization Website: https://www.altervista.org
Altervista is a free web hosting service.
Each registered user gets its own subdomain (e.g. username.altervista.org) on which PHP scripts can be uploaded and executed.
====
We'd like to properly isolate each subdomain to prevent global cookie setting on altervista.org and highlight that each subdomain hosts a different site, unrelated to the others.
=======
```
$ dig +short TXT _psl.altervista.org
"https://github.com/publicsuffix/list/pull/883"
```
make test
=========
https://gist.github.com/CarloCannas/ed43e1ddf23541659c6e296c1cfc5ed3
https://travis-ci.org/publicsuffix/list/builds/586473517
=> Add altervista.org

public_suffix_list.dat
<hr>
<a href="https://www.iana.org/domains/root/db/ss.html">.ss </a>is the designated country code top-level domain (ccTLD) for South Sudan as approved by the ICANN board on 27 January 2019 and added to the DNS root zone on 2 February 2019.
<hr>
To have the .ss ccTLD to be included in the public list for any applications referencing the list.
=> Add the new TLD .ss

public_suffix_list.dat
http://www.nic.it/sites/default/files/docs/Regulation_assignation_v7.1.pdf is no more available.
The new URL of that PDF is https://www.nic.it/sites/default/files/archivio/docs/Regulation_assignation_v7.1.pdf - see [this page](https://www.nic.it/en/doc/2015/assignment-and-management-domain-names-cctdlit-regulations-version-71).
=> Update source of reserved .it geo-names

public_suffix_list.dat
====
Organization Website: https://www.gov.scot
The Scottish Government is the devolved government for Scotland. There is no ccTLD for Scotland, but there is a geographic gTLD: `.scot`. The gov.scot domain is used by the Scottish Government and other public sector organisations in Scotland.
The lack of ccTLD for Scotland means that this proposed entry appears in an unusual place in the list for a government domain. From the commit message:
> This entry for gov.scot appears in the private domains section of the list.  This is in contrast to most `gov.*` domains in the list, which appear in the ICANN section of the list, near or alongside the relevant country code.  This is because the .scot domain is a (geographic) gTLD and the gTLD section of the list is …
=> Add gov.scot to Public Suffix List

public_suffix_list.dat
====
Coordination Center for TLD RU (CC for TLD RU) is administrator of national top level domains .RU and .РФ (national registry).
Organization Website: https://cctld.ru
Reason of this Pull Request
====
1) CC for TLD RU changed the rules and there are no Reserved domain names at Top level domain .RU at this time. 
Domains 
ac.ru
edu.ru
gov.ru
int.ru
mil.ru
test.ru
is the regular domain names now.
2) New URL for Term and Conditions in section xn--p1ai
=> Reserved domains off

public_suffix_list.dat
Hi!
====
Organization Website: https://darklang.com
Our website says:
> Dark is a holistic programming language, structured editor, and infrastructure, for building backend web services. It's for frontend, backend, and mobile engineers.
I'm a co-founder of Dark.
====
Dark allows users to write code that is hosted on subdomains of `builtwithdark.com`. These mutually-untrusted users can currently write code to set cookies for other subdomains; we believe that adding `builtwithdark.com` to the public suffix list is the best way to fix this.
=======
```
$ dig +short TXT _psl.builtwithdark.com
"https://github.com/publicsuffix/list/pull/857"
```
make test
=========
We ran it: …
=> Add builtwithdark.com to the public suffix list

public_suffix_list.dat
====
I am an individual and am representing myself. I would like to list my domain in the PSL for the reasons outlined below.
====
The domain is currently being used (and will be used in future) to host very distinctly different applications, in part already by different owners. As such, I feel that browsers (as well as related DynDNS services and DNS hosts) should treat them as such. Additionally, I intend to open up `<name>.qcx.io` registrations on a per-approval basis in future, and so the prevention of `qcx.io`-wide cookies becomes a more pressing issue.
The wildcard subdomain I am adding, `*.sys.qcx.io`, will be used for other domain-meta information (such as endpoint mappings, datacenter-specific authoritative zones, SDN zones), …
=> Add qcx.io and *.sys.qcx.io

public_suffix_list.dat
We'd like to properly isolate each subdomain to prevent global cookie setting
on 0e.vc and highlight that each subdomain hosts a different site,
unrelated to the others.
====
I'm representing myself, as an individual.
I will host content that would benefit from being isolated at the PSL level.
Organization Website: https://frederik-braun.com/
====
Isolation of Cookies, mostly. (Plus some other minor oddities, that might prefer the PSL instead of a proper Same-Origin Policy Check)
=======
```
$ dig +short -t TXT _psl.0e.vc
"https://github.com/publicsuffix/list/pull/896"
```
make test
=========
=> Add 0e.vc to PSL

public_suffix_list.dat
====
Organization Website: [https://www.gentlent.com](https://www.gentlent.com)
I am a director and engineer at Gentlent, which is a software development and consulting company.
====
We are going to use gentapps.com for user-specific spaces and projects for our upcoming SaaS products. DynDNS may be included later too. As our users may upload custom content to these domains, they should not set cookies on the root domain. Browsers should therefore recognize gentapps.com as a suffix.
=======
```
dig +short TXT _psl.gentapps.com
"https://github.com/publicsuffix/list/pull/916"
```
make test
=========
I ran "make test" with all tests passing. See [https://gist.github.com/tomkln/f291349514901d3a6b3c5384e8e2efd3](https: …
=> Added gentapps.com

public_suffix_list.dat
The organization is Google. We are adding a new URL format for App Engine. Similar to the existing appspot.com (already on PSL), subdomains under *.r.appspot.com (e.g. foo.xyz.r.appspot.com) will each serve different customer apps.
Same as existing appspot.com.
Working on this. Needed to submit PR first to get a number to add to DNS.
Once it's ready, will be available at `dig +short TXT _psl.r.appspot.com`.
Passes.
=> Add *.r.appspot.com to public suffix list

public_suffix_list.dat
====
Organization Website: https://rancher.com
Rancher Labs develops an open-source Kubernetes distribution called K3s
I am [Vincent Fiduccia](https://github.com/vincent99), software architect at Rancher.
====
We are adding a feature to automatically provide each user cluster with a `<random user-id>.on-k3s.io` DNS entry that can be used to reach published Kubernetes services (largely HTTP servers). Each `user-id` is a mutually untrusting third-party that should not be able to set cookies readable by each other.  We also plan to provide Let's Encrypt wildcard certs for each `user-id`.
=======
```
dig +short TXT _psl.on-k3s.io
"https://github.com/publicsuffix/list/pull/922"
```
make test
=========
Passes
=> Add *.on-k3s.io

public_suffix_list.dat
====
Organization Website: https://www.adobe.com
I am an Engineer working at Adobe in the Adobe Experience Manager organisation working on SaaS hosting.
====
Cookie Security between subdomains since the subdomains will be managed and run by different organisations with the ability to set cookies.
=======
Done
$ dig +short TXT _psl.adobeaemcloud.com
"https://github.com/publicsuffix/list/pull/931"
$ dig +short TXT _psl.adobeaemcloud.net
"https://github.com/publicsuffix/list/pull/931"
$ dig +short TXT _psl.dev.adobeaemcloud.com
"https://github.com/publicsuffix/list/pull/931"
make test
=========
make test and other validations have been run.
```
======================================================================== …
```
=> Added adobeaemcloud domains

public_suffix_list.dat
====
Organization Website: https://www.discourse.org/
I am on the Infrastructure team at Civilized Discourse Construction Kit, Inc. and we build an open source community platform for civilized discussion on the web at https://github.com/discourse/discourse/.
We will be hosting a new product on discourse.team in the same manner that we do for discourse.group as previously added in #768 
====
As we will host multiple forums under the discourse.team domain we'd like to add it to the PSL to:
Ensure that each subdomain of discourse.team is treated as a distinct domain.
Adding cookie security.
=======
```
○ → dig +short TXT _psl.discourse.team.
"https://github.com/publicsuffix/list/pull/949"
```
make test
=========
I …
=> Add discourse.team

public_suffix_list.dat
====
Organization Website: getchannels.com
We are a SaaS company. I am the founder and CTO. We provide dynamic dns to users of our product and give them each a unique subdomain.
====
We previously added `channelsdvr.net` to the PSL in #495. Since then, due to limitations by our DNS provider, we have had to migrate new user DDNS entries to a separate `u.channelsdvr.net` domain.
We would like for cookies not to be shared across user subdomains like `xxx.u.channelsdvr.net`.
make test
=========
Tests pass:
```
```
=> Add u.channelsdvr.net to PSL

public_suffix_list.dat
====
Organization Website: https://www.woltlab.com/
I'm an Engineer at WoltLab GmbH. WoltLab GmbH is the developer of WoltLab Suite, a web application suite to build online communities. So far our web application suite was only offered as a downloadable package for customers to host themselves. We plan to provide a fully managed SaaS solution starting in the first quarter of 2020: https://community.woltlab.com/thread/279987-managed-hosting-introducing-the-woltlab-cloud/
====
Within the SaaS solution we will offer a number of domains for customers to choose a subdomain from if they do not want to bring their own domain.
Customers are able to customize the look and feel of their community, including the generated HTML and to a certain …
=> Add WoltLab Cloud domains

public_suffix_list.dat
this is a simple change, just normalizing the text.
=> Remove unnecessary trailing whitespace for name.fj

public_suffix_list.dat
====
Organization Website: https://www.zitcom.dk
Zitcom A/S is a hosting and cloud provider.
Reason for PSL removal
====
site.builder.nu is used for our site builder product. Each customer is assigned a subdomain on *.site.builder.nu -like [randomstring].site.builder.nu.
However as we use a *.site.builder.nu wildcard, the inclusion means that we need to get an exception from the CA, when the cert needs to be renewed, and that is not feasible. And as we has full control over the entire *.site.builder.nu space, we wish site.builder.nu to be **removed** from the PSL.
=======
```
dig +short TXT _psl.site.builder.nu
"https://github.com/publicsuffix/list/pull/866"
```
make test
=========
Ran the test, nothing broke
=> Remove site.builder.nu

public_suffix_list.dat
====
Organization Website: https://urown.net
The domains "dnsupdate.info" and "urown.cloud" are privately owned and made available for free use by the public with the dynamic DNS service https://nsupdate.info/.
====
nsupdate.info strongly advises to add public domains to the public suffix list.
=======
```
dig +short TXT _psl.urown.cloud
"https://github.com/publicsuffix/list/pull/880"
dig +short TXT _psl.dnsupdate.info
"https://github.com/publicsuffix/list/pull/880"
```
make test
=========
https://travis-ci.org/publicsuffix/list/builds/616010823
=> Add "urown.cloud" and "dnsupdate.info"

public_suffix_list.dat
====
Mineduc is the Ministry of Education of the Chilean Government, responsible for promoting development at all levels of education at both public and private institutions.
Organization Website: https://www.mineduc.cl/
I work for NIC Chile (Hugo Salgado <hsalgado@nic.cl>), the .CL registry, submitting this PR on behalf of Mineduc. We're coordinated to validate the change. .CL whois doesn't list contact emails, but I can provide you with any proof at your request.
====
Mineduc will use this private sub-registry to give each public school in Chile a website for e-learning infrastructure. Each site will be fully managed by school administrators, so they need independence for certificate issuing, cookie management, etc.
DNS Verification …
=> Add Mineduc private subregistry for public schools: aprendemas.cl

public_suffix_list.dat
Add a couple of private domains:
* toolforge.org
* wmcloud.org
Both domains belong to the Wikimedia Foundation and are used specifically by
the Wikimedia Cloud Services team to provide services such as Toolforge and
CloudVPS. Information about both can be found on Wikitech:
https://wikitech.wikimedia.org
In both domains, we allow arbitrary subdomains to be created by users of our
services. Any subdomain of a given subdomain is under control of the same user.
Detailed information about the domain names used by Wikimedia Cloud Services
and how do we handle them can be found at Wikitech as well:
https://wikitech.wikimedia.org/wiki/Portal:Cloud_VPS/Admin/DNS
For the record, this update is tracked in Wikimedia's ticketing system:
https://phabricator.wikimedia.org/T168677
While at it, update …
=> Add toolforge.org and wmcloud.org

public_suffix_list.dat
====
Organization Website: https://www.microsoft.com
====
Azure Container Instance resources provide user dns lables, which have a regional suffix. I'm amending the PSL record to have the <regionname>.azureconteiner.io rather than azureconteiner.io
=======
dig +short TXT _psl.azurecontainer.io
"https://github.com/publicsuffix/list/pull/930"
make test
=========
https://travis-ci.org/publicsuffix/list/builds/621228928?utm_source=github_status&utm_medium=notification
=> ACI regional suffix

public_suffix_list.dat
====
Organization Website: https://www.sie.com/en/
Sony Interactive Entertainment LLC (SIE) a US-based company that develops and distributes PlayStation® brand hardware, software, content and network services. Within SIE, Cloud Gaming Engineering & Infrastructure (CGEI) operates a number of cloud-gaming services including [PlayStation™Now](https://www.playstation.com/en-us/explore/playstation-now/).
CGEI operates a global network of datacenters and associated network infrastructure to support these services under the umbrella of [AS33353 (SIE-CGEI-ASN-1)](https://whois.arin.net/rest/asn/AS33353).
Communication regarding this network can be sent to sie-cgei-net-arin-contact@sony.com.
====
This domain will be used to serve a variety of …
=> Add playstation-cloud.com

public_suffix_list.dat
====
Organization Website: https://platter.dev
Platter (Boilerplatter, Inc.) is a product development platform for developers. We create, host, and continuously deploy sites for our users on subdomains of platter-app.com, platter-app.dev, and platterp.us.
====
We want to be able to do the following for our users on these subdomains:
- protect against cross-subdomain cookie/state sharing via the higher level domain suffixes
- use subdomains as Google OAuth Authorized Domains to prevent over-authorizing origins
- experiment with some origin trials on individual sites we run on subdomains
=======
```
$ dig txt _psl.platter-app.com
_psl.platter-app.com.	600	IN	TXT	"https://github.com/publicsuffix/list/pull/935"
``` …
=> Add platter.dev user app domains

public_suffix_list.dat
====
Organization Website: https://fastvps.ru/
FASTVPS EESTI OU is hosting provider. I am the one of engineers working with infrastructure.
====
We provide technical domains for our customers so they can test their sites without the need of assigning their production domain to the server. We now have 4 technical domains:
myfast.space
myfast.host
fastvps.site
fastvps.host
3-rd level domains based on these are not related with each other and should not trust each other.
Every domain is used by different website and typically by different customer.
Also it is good to have ability to issue Let's Encrypt for such domains.
We have created PR before (#743), but did not add DNS records in time, sorry. Now it won't be so.
DNS Verification via …
=> Add domains for FASTVPS EESTI OU

public_suffix_list.dat
====
Organization Website: https://aaronleem.co.za
I am a software developer that allows creating subdomains using self-hosted gitlab pages' systems; I provide this service for students that would like free enterprise features without hassles
====
Cookie security;  since multiple individuals will be using the system it would be good to have separate ability to set cookies
=======
dig +short TXT _psl.graphox.us
"https://github.com/publicsuffix/list/pull/960"
make test
=========
Passes
=> Added graphox.us domain

public_suffix_list.dat
====
Organization Website: https://flynn.io
Reason for PSL Removal
====
This domain is no longer used as a public suffix.
=======
```
$ dig +short TXT _psl.flynnhub.com
"https://github.com/publicsuffix/list/pull/971"
```
make test
=========
The tests pass.
=> Remove flynnhub.com

public_suffix_list.dat
====
Organization Website: www.fearworkshosting.co.uk
FearWorks Media Ltd. provides web hosting and email services. I am the founder and director.
====
The subdomains under the conn.uk, copro.uk, couk.me and ukco.me domains are assigned to different customers of our company. We assign subdomains such as example.conn.uk, companyname.couk.me, etc. Our clients can use the assigned subdomain(s) to access their admin systems, backends and frontends.
We want to protect the user-created subdomains under the conn.uk, copro.uk, couk.me and ukco.me domains from cross-subdomain cookie/state sharing and also allow generation of Let's Encrypt SSL certificates for the custom subdomains.
=======
```
dig +short TXT _psl.conn.uk …
```
=> Add conn.uk, copro.uk, couk.me and ukco.me domains

public_suffix_list.dat
====
Organization Website: https://iserv.eu
IServ GmbH is a German company providing IT solutions for the educational sector. Our main product is also called IServ. IServ, sometimes referred to as IServ Schoolserver, is an all-in-one solution for the pedagogical side of a school's network. It provides basic functionality like e-mail, file sharing, instant messaging, calendars, a collaborative text editor etc., but also software deployment and an Active Directory domain controller as well as more education oriented features such as special examination modes for local computers and an exercise module.
IServ is currently used by over 2.400 schools primarily in German-speaking regions and manages  about 140.000 computers and almost 1.500.000 user accounts.
Reason …
=> Add schulserver.de, update IServ GmbH contact information

public_suffix_list.dat
====
Organization Website: https://www.netlify.com/
I'm Jessica Parsons, staff technical writer at Netlify. Netlify is a platform people use to build, deploy, and serve websites.
====
I submitted https://github.com/publicsuffix/list/pull/469 back in June 2017, which added `netlify.com` and `bitballoon.com` domains to the list. These domains were included because they are used for customer sites. Each subdomain on the domain belongs to a different customer, so inclusion on the list was necessary to prevent multi-site cookies.
As announced in customer emails and the [Netlify community forum](https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918), we're migrating all of our customer subdomains to `netlify.app` on April …
=> Add domain to existing Netlify entry: netlify.app

public_suffix_list.dat
====
Organization Website: https://wisp.gg
I'm a Software Engineer for WISP, a Game Panel SaaS. We host the web interface while allowing you to use your own nodes for deploying game servers. Each client gets their own {id}.panel.gg subdomain, and each client's node gets {id}.daemon.panel.gg subdomain to not require the user to have their own domain.
====
As we have no control over what the user serves on these subdomains, we're looking to get them added to the PSL, improving the cookie security and browser's behavior.
=======
```
dig +short TXT _psl.panel.gg
"https://github.com/publicsuffix/list/pull/978"
```
```
dig +short TXT _psl.daemon.panel.gg
"https://github.com/publicsuffix/list/pull/978"
```
make test …
=> Add panel.gg and daemon.panel.gg

public_suffix_list.dat
====
Organization Website: https://dappnode.io/
I'm a software and systems engineer working at DAppNode.
DAppNode is a solution to allow users to conveniently host P2P and distributed technologies on their own hardware, with focus on blockchain and cryptocurrency projects.
DAppNode software is an open-source platform developed by the non-profit association DAppNode association in Zug, Switzerland. DAppNode Association is driven and funded by the community, at the moment we have three grants from EF, Aragon, and ECF, but the association also has sustainability sources relying on projects that want their package uploaded to DAppNode and featured in the installer section, or the selling of hardware with DAppNode preinstalled which implies a donation to the …
=> Add dyndns.dappnode.io

public_suffix_list.dat
====
Organization Website: https://clic2000.fr
Web dev and hosting company.
====
Domain offer customers free subdomains (Cookie Security)
=======
```
dig +short -t TXT _psl.clic2000.net                                                                                                                                                                                  [7/04/20 10:40]
"https://github.com/publicsuffix/list/pull/1010"
```
make test
=========
it runs
```
~/list$ make test
./pslint_selftest.sh;                     \
./pslint.py ../public_suffix_list.dat;
test_allowedchars: OK
test_dots: OK
test_duplicate: OK
test_exception: OK
test_NFKC: OK
test_punycode: OK …
```
=> Add clic2000.net to Private Section

public_suffix_list.dat
====
Organization Website: https://shopware.store
I am an engineer at shopware working on our SaaS hosting for e-commerce shops which are based on Shopware 6 (https://github.com/shopware/platform).
====
Cookie security between subdomains since the subdomains will be managed and run by different organizations with the ability to set cookies.
=======
```
dig +short TXT _psl.shopware.store
"https://github.com/publicsuffix/list/pull/958"
```
make test
=========
All passed
=> Add shopware.store domain

public_suffix_list.dat
====
Organization Website: https://voxel.sh/dns/
Voxel.sh is an internet infrastructure project run by a small group of individual volunteers. I'm leading this project. We're running our own anycast DNS clusters and are currently working on an authoritative DNS service with focus on free Third Level Domains ("free subdomains") for projects or individuals who don't necessary need an own paid domain.
We're close to release and would like PSL inclusion before launch for the reasons listed below. Right now, during internal testing phase, there are only a few domains active, like my own homepage at https://mia.vxl.sh/.
I closed my previous pull request at https://github.com/publicsuffix/list/pull/953 due to our project name change.
====
- …
=> Add Voxel.sh DNS public suffixes

public_suffix_list.dat
// bitbridge.net : Submitted by Craig Welch, abeliidev@gmail.com
====
Organization Website: https://www.softlatch.net https://gitlab.com/cwsyncdev/SoftLatch/-/wikis/home
SoftLatch provides a way to self-host home automation and productivity apps - a simple way to install domoticz (https://www.domoticz.com/), a motion detecting webcam application, and a note taking application, with more planned.  
I'm the founder of the project and owner of the domain names, Craig Welch.
====
The desire to be added to this list is to enable https://letsencrypt.org/ certificates to be vended for the self-hosted bridge applications for which dynamic dns services are offered on bitbridge.net (e.g. after signup for an account on softlatch.net, during …
=> add bitbridge.net to private section

public_suffix_list.dat
====
Organization Website: https://linode.com
Linode is a public cloud / infrastructure as a service company.
====
We provide automatic PTR records for a number of our services.
- Linode (virtual machine instances) - (e.g. li123-456.members.linode.com)
- NodeBalancer (managed load balancer) - (e.g. nb-192-0-2-1.dallas.nodebalancer.linode.com)
- Object storage static sites - (e.g. my-bucket.website-us-east-1.linodeobjects.com)
We wish to include these domains in the PSL to ensure that browsers provide appropriate cookie security for these domains.
This request updates our NodeBalancer entry to treat all regions as public suffixes (resolves #1018) and adds support for object storage static sites. Our previous PR was #810.
DNS Verification …
=> Update Linode PSL entries

public_suffix_list.dat
// kasserver.com : Submitted by Werner Kaltofen wk@all-inkl.com
====
Web hosting company
Organization Website: all-inkl.com is a web hosting brand of Neue Medien Muennich GmbH
====
The domain offer customers free subdomains (Cookie Security)
=======
dig +short -t txt _psl.kasserver.com
\"https\://github.com/publicsuffix/ list/pull/1016"
make test
=========
no mistakes
=> Add kasserver.com to Private Section

public_suffix_list.dat
====
Organization Website: https://www.plesk.com/
Plesk is the leading WebOps hosting platform to run, automate and grow applications, websites and hosting businesses. Being the only OS agnostic platform, Plesk is running on more than 420,000 servers, automating 11M+ websites and 19M+ mail boxes. Available in more than 32 languages across 140 countries, 50% of the top 100 service providers worldwide are partnering with Plesk today.
====
- We issue LetsEncrypt certificates for server's hostnames for our customers
- We want our customers' sites to be isolated for other customers (cookies, suffix highlighting, etc)
=======
```
$ dig +short TXT _psl.plesk.page
"https://github.com/publicsuffix/list/pull/1022"
$ dig …
```
=> Add plesk.page and pdns.page suffix to private section

public_suffix_list.dat
====
Organization Website: https://whats-th.is
OwO provides free file and source code hosting for its members. It is run independently by @deansheather and @aurieh using donations.
====
Cookie security. `*.owo.codes` hosts individual GitLab pages sites created by users. A wildcard is used as cookies are used on the root.
=======
```
dig +short TXT _psl.owo.codes
"https://github.com/publicsuffix/list/pull/973"
```
=> Add *.owo.codes

public_suffix_list.dat
====
Organization Website: https://www.netlify.com/
I'm Jessica Parsons, staff technical writer at Netlify. Netlify is a platform people use to build, deploy, and serve websites.
Reason for PSL ~Inclusion~ Removal
====
This is a follow-up to #1012, where we added `netlify.app` as the new domain for Netlify customer sites. The migration is now complete; `netlify.com` is now used for Netlify-owned properties only, and `bitballoon.com` is no longer in use (permanently redirects to `netlify.com`/`netlify.app`).
=======
```
$ dig _psl.netlify.com TXT +short
"https://github.com/publicsuffix/list/pull/1020"
$ dig _psl.bitballoon.com TXT  +short
"https://github.com/publicsuffix/list/pull/1020"
```
make test
=========
My laptop doesn't have the …
=> Remove domains from Netlify entry: bitballoon.com and netlify.com

public_suffix_list.dat
====
Organization Website: https://www.gentlent.com
I am CEO/CTO at Gentlent, which is a software development and consulting company.
====
gentlentapis.com will be used to host multiple (incl. third-party) APIs on different subdomains which should not be able to set cookies to other subdomains for security reasons. User content may be allowed. Browsers should, therefore, recognize gentlentapis.com as a suffix.
=======
```
dig +short TXT _psl.gentlentapis.com
"https://github.com/publicsuffix/list/pull/984"
```
make test
=========
"make test" ran successfully: https://gist.github.com/tomkln/e6d5f0a747a3b2433ab2db2b0abe7428
=> Added gentlentapis.com

public_suffix_list.dat
====
Organization Website: https://www.seidat.com
Seidat is a cloud presentation platform for teams. I am responsible for the technology and infrastructure there.
====
We'd like to let our customers run their own Google Tag Manger containers in a sandboxed iframe (hosted on seidat.net) for presentation analytics. Letting them run their GTM setup effectively means allowing them to execute any code in the iframe. Each team loads the iframe from its own subdomain (example: team_id.seidat.net). We'd like to restrict the ability to set cookies on the parent domain to isolate teams from one another.
=======
```
dig +short TXT _psl.seidat.net
"https://github.com/publicsuffix/list/pull/974"
```
make test
========= …
=> Add seidat.net private domain

public_suffix_list.dat
====
Organization Website: https://banzaicloud.com
Hello there, I'm Janos Matyas, CTO of Banzai Cloud. 
Banzai Cloud simplifies the transition to a Cloud Native application stack by providing a range of services around Kubernetes and Istio.
====
We already have an entry in the list for `app.banzaicloud.com` (thank you). 
We now have a new service called Backyards that will provide users DNS entries for publicly exposing their services from a managed cluster through Istio.
We'd like to differentiate DNS entries obtained through Backyards from other Banzai Cloud services.
Similarly to the previous entry we'd like all of these domain names to be compliant, including cookie handling, DNS sorting, and Let's Encrypt cert issuance.
DNS …
=> Add *.backyards.banzaicloud.io and *.banzai.cloud

public_suffix_list.dat
====
Organization Website: https://vercel.com (previously zeit.co)
Vercel is a developer platform that makes deploying performant frontend websites easy. We currently provide users with *.now.sh domains if they don't have their own. We're going to be offering *.vercel.app and *.vercel.dev soon so we need to be included in this list.
====
- We issue LetsEncrypt certificates for our customers
- We want our customers' sites to be isolated for other customers (cookies, suffix highlighting, etc)
=======
```
$ dig +short TXT _psl.vercel.app
"https://github.com/publicsuffix/list/pull/1019"
```
```
$ dig +short TXT _psl.vercel.dev
"https://github.com/publicsuffix/list/pull/1019"
```
```
$ dig +short TXT _psl.now.sh …
```
=> Add vercel.app and vercel.dev and update now.sh listing in private section

public_suffix_list.dat
====
Organization Website: <https://dev.viberplay.io>
Viber Play is a game platform running in the messenger platform Viber <https://chats.viber.com/rakutengames>. It helps game developers to develop and publish HTML5 game content inside Viber.
Viber Play is developed and operated by Rakuten Games, Inc. <http://corp.rakuten-games.com/>
====
Subdomains under g.vbrplsbx.io are assigned to different game developers for hosting their HTML5 game contents.
We want to protect users from being tracked across games via cross-subdomains cookie/state sharing.
=======
```
dig +short TXT _psl.vbrplsbx.io
"https://github.com/publicsuffix/list/pull/994"
```
make test
=========
``` …
```
=> Add g.vbrplsbx.io domain

public_suffix_list.dat
This is adding of pleskns.com domain in addition to pdns.page and plesk.page domains which were added here https://github.com/publicsuffix/list/pull/1022.
====
Organization Website: https://www.plesk.com/
Plesk is the leading WebOps hosting platform to run, automate and grow applications, websites and hosting businesses. Being the only OS agnostic platform, Plesk is running on more than 420,000 servers, automating 11M+ websites and 19M+ mailboxes. Available in more than 32 languages across 140 countries, 50% of the top 100 service providers worldwide are partnering with Plesk today.
====
- We issue LetsEncrypt certificates for server's hostnames for our customers
- We want our customers' sites to be isolated for other customers …
=> Add pleskns.com suffix to private section

public_suffix_list.dat
====
PageXL is a SaaS for building responsive one-page sites.
Organization Website: https://pagexl.com
====
PageXL allows users to publish their sites to the pagexl.com domain suffix (eg. mysitename.pagexl.com) so we're requesting inclusion in the PSL primarily to ensure cookie isolation/security for sites hosted on the platform.
=======
```
dig +short TXT _psl.pagexl.com
"https://github.com/publicsuffix/list/pull/1029"
```
make test
=========
Ran and passed!
=> Add pagexl.com

public_suffix_list.dat
====
Organization Website: https://wiki.funkfeuer.at/wiki/Regionen/Wien/Verein
FunkFeuer is an association with various initiatives throughout Austria. These initiatives all have their own sub-domain within the funkfeuer.at namespace. These sub-domains are fully delegated out to the initiatives and allocate their member domains underneath as they see fit.
This adds the community sub-domain for Vienna.
====
FunkFeuer Wien is an non-profit association from Vienna, Austria. It delegates Domains below `wien.funkfeuer.at` to its members.
=======
```
dig +short TXT _psl.wien.funkfeuer.at
"https://github.com/publicsuffix/list/pull/1041"
```
make test
=========
Test showed no errors.
=> Add wien.funkfeuer.at to private section

public_suffix_list.dat
====
Organization Website: https://fastvps.ru/
FASTVPS EESTI OU is hosting provider. I am the one of engineers working with infrastructure
Reason for PSL Removal
====
That domain was previously used as separate 3-rd level domains provided to our customers, but it is no longer the ussue, and it is not needed in the list. So we request the removal.
Also sorted our other domains to follow guidelines.
=======
```
$ dig +short TXT _psl.fastpanel.direct
"https://github.com/publicsuffix/list/pull/1024"
```
make test
=========
make test finished OK
http://ghostbin.fv.ee/paste/qr7qp/raw
=> Remove fastpanel.direct for FASTVPS EESTI OU

public_suffix_list.dat
A minor fix to update URLs leading to `nic.lk`. No actual domain changes. 
This PR replaces a dead link `http://www.nic.lk/seclevpr.html` that was dead for years with the most relevant page that mentions the public suffixes the NIC maintains.
In addition, there are two `https` upgrades for `http://nic.lk`.
Thank you.
=> Fix broken links in nic.lk

public_suffix_list.dat
====
Organization Website: https://wpengine.com
WP Engine is a commercial company that provides managed WordPress hosting. I work on WP Engine's platform engineering team.
====
Our customers can publish their sites as subdomains of wpenginepowered.com, and we want to prevent cookies from being shared between sites.
=======
```
dig +short TXT _psl.wpenginepowered.com
"https://github.com/publicsuffix/list/pull/1064"
```
make test
=========
All tests pass.
=> Add wpenginepowered.com

public_suffix_list.dat
====
Organization Website: https://mchost.ru
McHost is a hosting provider. We provide free subdomains in `.mcdir.ru` and `.vps.mcdir.ru` domains for our customers.
====
McHost's customers are allowed to publish their own sites in the .mcdir.ru suffix, so we need to restrict cookie sharing between these subdomains.
=======
```
dig +short TXT _psl.mcdir.ru
"https://github.com/publicsuffix/list/pull/1051"
```
```
dig +short TXT _psl.vps.mcdir.ru
"https://github.com/publicsuffix/list/pull/1051"
```
make test
=========
``` …
```
=> Add mcdir.ru and vps.mcdir.ru

public_suffix_list.dat
====
Organization Website: https://thingdust.com
We are a small startup that provides a solution for measuring the occupancy of workplace environments (primarily shared desk and meeting rooms). Every customer gets his own instance with his own subdomain provided by us.
====
firenet.ch is our domain which we use for our internal services (jenkins, monitoring, ...). The services are independent of each other and it causes issues with password-remember and cookies now that we have quite a bunch of these services.
=======
```
dig +short TXT _psl.firenet.ch
"https://github.com/publicsuffix/list/pull/1031"
```
```
dig +short TXT _psl.svc.firenet.ch
"https://github.com/publicsuffix/list/pull/1031"
```
make test …
=> Add *.svc.firenet.ch and *.firenet.ch to existing thingdust.io listing

public_suffix_list.dat
`rdv.to` is a point of rendez-vous for a distributed web of actors.
We use `*.bar0.net`, `*.bar1.net`, `*.bar2.net` as tiers of actors.
`*.rdv.to` is used for isolation of HTTP traffic.
We absolutely want each entity to be perceived as its own in every possible way, and would appreciate an extra layer of security with regards to cookies and in any web handling platform semantics available whatsoever.
```
pcarrier@pcarrier-desk:~$ dig +short TXT _psl.rdv.to
"https://github.com/publicsuffix/list/pull/1039"
pcarrier@pcarrier-desk:~$ dig +short TXT _psl.bar0.net
"https://github.com/publicsuffix/list/pull/1039"
pcarrier@pcarrier-desk:~$ dig +short TXT _psl.bar1.net
"https://github.com/publicsuffix/list/pull/1039"
pcarrier@pcarrier-desk:~$ dig +short TXT _psl.bar2.net …
```
=> Add rdv.to domains for pcarrier.ca Software Inc.

public_suffix_list.dat
====
Organization Website: [https://mythic-beasts.com](https://mythic-beasts.com)
Mythic Beasts is a hosting company offering a mix of web hosting, virtual and dedicated servers, as well as hosted Raspberry Pi servers.
* `vs.mythic-beasts.com` is used by Virtual Servers.
* `x.mythic-beasts.com` is used by Dedicated Servers.
* `hostedpi.com` is used by Hosted Raspberry Pi servers.
* `customer.mythic-beasts.com` is used by a mix of hosting.
* All others used by customer web hosting.
====
A number of customers use the customer sub-domains and server hostnames for testing and various administration interfaces. Adding them to the PSL should negate most cross-domain cookie-related worries.
=======
```bash
dig +short …
```
=> Add Mythic Beasts domains

public_suffix_list.dat
====
Organization Website: https://algorithmia.com
Algorithmia provides the fastest time to value for enterprise machine learning. Rapidly deploy, serve, and manage machine learning models at scale. This PR is submitted by myself, Eli Perelman, representing Algorithmia as lead web engineer.
====
We currently have a cookie set for `algorithmia.com`, but would like to share that with `teams.algorithmia.com` and `test.algorithmia.com` without sharing with our other subdomains that should not have access.
=======
```bash
dig +short TXT _psl.algorithmia.com
"https://github.com/publicsuffix/list/pull/1071"
```
```bash
dig +short TXT _psl.test.algorithmia.com
"https://github.com/publicsuffix/list/pull/1071"
```
```bash …
```
=> Add algorithmia.com

public_suffix_list.dat
====
Organization Website: https://dns.business
DNS Africa Ltd is a back-end registry provider, based in Mauritius. We look after the .Africa infrastructure, with an affiliated organisation (Domain Name Services (PTY) LTD) looking after the ZA infrastructure, dotCapeTown, dotJoburg and dotDurban.
====
Jozi.Biz is an open zone, with registrations available to the public via our https://gateway.africa SRS platform. Each delegation therein is potentially to a different, unaffiliated registrant.
=======
```
dig +short TXT _psl.jozi.biz
"https://github.com/publicsuffix/list/pull/1088"
```
make test
=========
git clone https://github.com/publicsuffix/list.git
cd list
make test
Did the above - had to pull in a couple …
=> Add Jozi.biz

public_suffix_list.dat
====
Organization Website: https://dangerscience.com
We are a software development company that hosts some of our own web applications, including the [Folio Network](https://folio.network) portfolio site creator, and a not-yet-publicly-available PaaS platform called Platform 0.
====
The included domain names can be used as subdomains by customers to create websites/applications, and we would like to make it harder for cookies to be set across multiple of these sites in case of nefarious activity.
`folionetwork.site` and `fnwk.site` are used by [Folio Network](https://folio.network) users for their portfolios, and `platform0.app` will be the default domains on Platform 0-hosted applications.
=======
```
dig …
```
=> Add Danger Science Group domains

public_suffix_list.dat
====
MobileEducation, LLC provides online education services, primarily Forte. We allow schools and teachers to register vanity urls as subdomains of forte.id to make it easy for their students to join with a short link.
Organization Website: https://joinforte.com
====
Our certificate provider allows for easy issuing of certificates on this list, and a wildcard certificate is not currently an option. Also preventing cookie bleed over respects user privacy & security.
dns verification
====
```
dig +short TXT _psl.forte.id
"https://github.com/publicsuffix/list/pull/1081"
```
make test
=========
I have run the tests locally. Pass.
=> Add forte.id

public_suffix_list.dat
====
Organization Website: https://small-tech.org
Small Technology Foundation is a tiny and independent two-person not-for-profit based in Ireland. We advocate for and build small technology to protect personhood and democracy in the digital network age.
====
As part of the [Small Web initiative](https://ar.al/2020/08/07/what-is-the-small-web/), we will be enabling our patrons to host their own web sites and apps at the `small-web.org` public suffix. We want to ensure that this is done securely regarding cookie security/domain scoping.
=======
```
dig +short TXT _psl.small-web.org
"https://github.com/publicsuffix/list/pull/1086"
```
make test
=========
Ran the test and all tests passed.
=> Add small-web.org domain under Small Technology Foundation (private)

public_suffix_list.dat
====
Organization Website: https://www.cloudflare.com/
We're extending our [Workers Sites](https://blog.cloudflare.com/workers-sites/) offering to allow easy deployment of it to <subdomain>.jamsite.app.
I am the product manager for this product at Cloudflare. We already set up an alias to be contacted over, when setting up our workers.dev suffix (publicsuffixlist@cloudflare.com).
====
Cloudflare customers will given a subdomain of jamsite.app for each project, to which they can deploy their serverless websites. Because subdomains are each controlled by different customers, they should be treated as separate domains for cookie purposes.
=======
```
dig +short TXT _psl.pages.dev …
```
=> Add pages.dev

public_suffix_list.dat
====
Organization Website: https://bip.sh
Bip is a static web hosting provider. Customers are provisioned a subdomain of bip.sh to host their website on.
====
Bip customers are provided with a subdomain of bip.sh to host their website on. These subdomains are controlled by different customers, so inclusion in this list will restrict cookie sharing between them.
=======
```
dig +short TXT _psl.bip.sh
"https://github.com/publicsuffix/list/pull/1098"
```
make test
=========
Local tests have passed.
=> Add bip.sh

public_suffix_list.dat
====
Organization Website: https://yahe.sh
**localzone.xyz** is meant as a domain to be used in internal networks to circumvent the problems layed out [by the ICANN](https://www.icann.org/en/system/files/files/name-collision-mitigation-05dec13-en.pdf). To date there is only the **home.arpa** domain as specified in [RFC 8375](https://tools.ietf.org/html/rfc8375) but which is not widely used.
====
The reason for inclusion is Cookie Security.
=======
```
yahe@YaheBookAir:~$ dig +short TXT _psl.localzone.xyz
"https://github.com/publicsuffix/list/pull/915"
```
make test
=========
Executed `make test` successfully:
https://gist.github.com/yahesh/cd9e116b2a7af577cf796fe4f7cc485c
=> add localzone.xyz

.github/pull_request_template.md
Update to ensure the rationale includes an attestation of >2 years registration term and a commitment to maintaining at least >1 year of registration term per #1109
====
====
=======
make test
=========
=> Update pull request template; private names >2y

public_suffix_list.dat
====
Organization Website: https://iopsys.eu
IOPSYS (legally iopsys software solutions AB) is the principal developer of [iopsysWrt](https://iopsys.eu/product/) – platform-independent gateway software based on OpenWRT. The main SDK is open source, and the community is welcome to contribute.
====
The `iopsys.se` domain is attached to our [public Gitlab instance](https://dev.iopsys.eu) for use with Gitlab Pages, so we're primarily looking for cookie security.
=======
```
$ dig +short TXT _psl.iopsys.se
"https://github.com/publicsuffix/list/pull/1104"
```
make test
=========
<details>
<summary>Full check log</summary>
```
$ make test …
```
=> Add iopsys.se

public_suffix_list.dat
====
Organization Website: https://tlon.io
I am Mark Staarink, engineer at Tlon, a company providing Urbit hosting as a service.
====
As part of its hosting service, Tlon will provide Urbit Identity owners with their own subdomain under `tlon.network`. For example, `palfun-foslup.tlon.network`. This will resolve to the web interface of their personal server, which can serve arbitrary content.
=======
```
> dig +short TXT _psl.tlon.network
"https://github.com/publicsuffix/list/pull/1112"
```
make test
=========
`make test` gives me a bunch of failures, but they seem entirely unrelated to my change. Could be a local environment issue. CI passes fine, hope that's sufficient!
=> Add tlon.network

public_suffix_list.dat
====
One.com is a web hosting company specializing in shared hosting. One.com is one of the largest hosting providers in Northern Europe with 1.5 million domain names hosted under the one.com brand and close to a million domain names hosted under other brands.
Organization Website: https://www.one.com/
====
service.one will be used to provide our customers with host names for accessing services on our network when there is not yet any other host name connected with the customer account.
Each customer will find their services under &lt;some name&gt;.&lt;some unique per customer identifier&gt;.service.one.
service.one should be included in PSL primarily for cookie security.
=======
```
$ dig txt +short …
```
=> Add service.one as a public suffix

public_suffix_list.dat
====
Organization Website: https://cloud.google.com/api-gateway
Engineer at Google on the Cloud API Gateway team.
====
Cloud API Gateway hosts fully managed HTTP and gRPC proxies with API policy enforcement features for GCP customers. The proxies receive a default hostname `<gateway ID>.<region code>.gateway.dev`
Our customers are not related to each other and there is no mutual trust between the gateways. By adding an entry to the public suffix list we'd like to prevent our customers from setting cookies on each `<region code>.gateway.dev` subdomain. Our use case is similar to `*.r.appspot.com` already included in the list.
=======
```
dig +short TXT _psl.gateway.dev …
```
=> Adds *.gateway.dev

public_suffix_list.dat
====
Organization Website: https://www.microsoft.com
====
Azure Static Web Apps allows users to host full stack web applications seamlessly. Users are given a generated hostname as a subdomain of the azurestaticapp.net domain, we are adding these domains (regional ones as well) to PSL to ensure one site cannot set a cookie for the whole domain.
=======
Added TXT records for all the domains we are adding. Example:
F:\list>nslookup -type=TXT _psl.westus2.azurestaticapps.net
Server:  cusqui001f5b2d--commoncorp-ip3.network.microsoft.com
Address:  10.50.10.50
Non-authoritative answer:
_psl.westus2.azurestaticapps.net        text =
"https://github.com/publicsuffix/list/pull/1133"
make test
========= …
=> Add azurestaticapps.net dns suffixes

public_suffix_list.dat
Reverts publicsuffix/list#1071
Ended up not being the long-term solution we needed, so reverting to keep the list clean.
=> Revert #1071 "Add algorithmia.com" to remove entries

.github/pull_request_template.md
Added request for submitting party to include historic Issue # or PR # to address issue #1027
====
====
=======
make test
=========
=> Update pull_request_template.md to ask for related issue or PR numbers

public_suffix_list.dat
====
Organization Website: qoto.io
QOTO is a non-profit organization that provides free, open-source, federated, privacy centric services for open-source and community STEM projects. We use gitlab pages and host the user pages at qoto.io, however for reference our main gitlab site is at git.qoto.org. Domain is registered for 2 years and 10 months more right now.
====
Our server issues Let's Encrypt for its user base, cookie security is also a concern. With several hundred projects being listed it is important we get listed on the suffix list.
=======
dig +short TXT _psl.qoto.io
make test
=========
Test ran and passed:
```bash …
```
=> Adding qoto.io

public_suffix_list.dat
====
Organization Website: https://www.hkpc.org/
We are representing Hong Kong Productivity Council - SECaaS Team. SECaaS is a platform providing
secure authentication as a service to developers.
====
Developers can register their own app at `<app>.secaas.hk` to host authentication
service. We'd like to include it in PSL to improve security of the session cookie.
=======
```
; <<>> DiG 9.10.6 <<>> @1.1.1.1 TXT _psl.secaas.hk
; (1 server found)
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49348
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_psl.secaas.hk. …
```
=> Add secaas.hk

public_suffix_list.dat
====
Norid AS runs the registry for Norwegian domain names. All domains directly under .no are registered with us. In addition to processing applications we develop the domain name policy according to the needs of society. We are also responsible for the technical operation and development of associated services. We also handle other national tasks related to our core activities.
In order to develop and adapt the rules for allocating domain names, we co-operate with various stakeholders. We also take social responsibility by working to keep the domain name system reliable and robust, and to ensure that it is governed in an open and democratic way.
The service is regulated by the Domain Name Regulations and is supervised by the Norwegian Communications Authority …
=> Add header for a registry RSS feed URL for .no (Norid AS official)

public_suffix_list.dat
Housekeeping; 
Clearing out expired name
xenapponazure.com #82 Domain Name No Longer Registered
Verified non-existence at registry
no impact expected from non-registered domain names
=> Del xenapponazure.com NXD from Private

public_suffix_list.dat
Housekeeping:
uklugs.org, part of #514  is no longer registered
Deleting this entry
Non-existent domain should have no impact on users or services
Confirmed non-existence at registry
=> Del uklugs.org NXD from Private section

public_suffix_list.dat
Housekeeping
cloudeity.net is **no longer registered**, which empties this section - removing to reverse #534 
NXD (non-existent domain) verified non-registered at registry
no impact anticipated due to non-existence of domain
=> Del cloudeity.net NXD from Private

public_suffix_list.dat
Housekeeping:
ptplus.fit from #300 is **no longer registered**
there is no anticipated impact due to non-existence of domain name
domain non-existence verified at registry
=> Del ptplus.fit NXD from Private

public_suffix_list.dat
Housekeeping
linkitools.space from #636 is no longer registered
NXD so no anticipated impact
NXD validated with registry - domain no longer registered
Only entry in section so also removing comment header for entry
=> Del linkitools.space NXD from Private

public_suffix_list.dat
* [ X] Description of Organization
* [ X] Reason for PSL Inclusion
* [X ] DNS verification via dig
* [X ] Run Syntax Checker (make test)
* [ X] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration.
====
Organization Website: https://Names.of.London/
"Names.of.London" is a business registering second level domains, mostly in new-GTLDs
In some ways similar to the old CentralNIC model (uk.com etc), but in newGTLDs
====
Sub-Domains can be owned & operated by independent legal entities.
Existing domains are already listed, this pull-request updates the list to remove domains no longer relevant and add ones that are going to be kept & operated long term.
======= …
=> Update the existing Names.of.London Public List

public_suffix_list.dat
* [x ] DNS verification via dig
====
I am the Founder of Krellian Ltd., an IoT software company and the new commercial sponsor of the WebThings open source software project. We provide a secure tunnelling service (and dynamic DNS) for IoT devices.
Organization Website: https://krellian.com
====
This is  a follow-up to #605 submitted in 2018.
The [Mozilla WebThings](https://iot.mozilla.org/) project is being [spun out](https://discourse.mozilla.org/t/an-important-update-on-mozilla-webthings/67764) of the Mozilla Corporation as an independent open source project with a new commercial sponsor.
webthings.io
=====
As part of this transition existing users of the [mozilla-iot.org](https://mozilla-iot.org) domain (currently listed in the …
=> Add webthings.io and krellian.net

public_suffix_list.dat
I am a partner of OpenResearch GmbH, a software development company. We are working mostly in the area of IoT solutions and automotive.
Organization website: https:/openresearch.com
We are using *.orsites.com to automatially deploy web projects that have no relation to each other.
* orsites.com is registered for more than two years (until 2023-03-26 11:05:48).
```
dig +short TXT _psl.orsites.com
"https://github.com/publicsuffix/list/pull/1157"
```
Successful output of `make test`: https://pastebin.ubuntu.com/p/dKg9Jgpz9k/
=> Add orsites.com to the list of domains

public_suffix_list.dat
====
Organization Website: www.flap.cloud
I am Louis Chemineau, founder of the FLAP company in France.
FLAP offers managed hosting for popular open source software. To ease the setup for the customer, FLAP can provide a domain name ending by `flap.id`.
====
This change will improve the cookie security.
The `flap.id` domain is in the private section. It is registered for more than 2 years.
=======
```
dig +short TXT _psl.flap.id
"https://github.com/publicsuffix/list/pull/1160"
```
make test
=========
``` …
```
=> Add flap.id domain

public_suffix_list.dat
====
The Lõhmus Family
I am Heiki Lõhmus and I own the domain name `lohmus.me`, which I use to provide DNS services to various members of the Lõhmus family.
====
The delegated zones under `lohmus.me` are operated by various family members of varying technical skill independently of each other. As a consequence, `lohmus.me` ought to be treated as a public suffix for the purposes of cookie security, HSTS preloading, and accessing third-party services such as Cloudflare and Let's Encrypt.
The domain has been registered for the maximum registration period of the `me` TLD (10 years) and I shall ensure that the remaining validity period is longer than two years while the domain remains listed as a public suffix.
```
$ whois lohmus.me
Domain …
```
=> Add lohmus.me to the private section

public_suffix_list.dat
DreamCommerce owns Shoper SaaS e-commerce platform. Each store is running under (`*.shoparena.pl`) domain.
We'd like to block cookies between instances of Shoper application, each one running under different `shoparena.pl` subdomain and owned by diffrent customers.
The domain is registered until 2024 and I shall ensure that the remaining validity period is longer than two years while the domain remains listed as a public suffix.
```
$ whois shoparena.pl
DOMAIN NAME:           shoparena.pl
registrant type:       organization
nameservers:           ns1.dcsaas.net.
ns2.dcsaas.net.
created:               2013.08.09 15:20:52
last modified:         2020.12.04 09:56:24
renewal date:          2024.08.09 15:20:52
```
```
$ dig TXT _psl.shoparena.pl
;; ANSWER SECTION:
_psl.shoparena.pl.  280 IN …
```
=> Add shoparena.pl domain

public_suffix_list.dat
====
Organization Website: https://www.woltlab.com/
I'm an Engineer at WoltLab GmbH. WoltLab GmbH is the developer of WoltLab Suite, a web application suite to build online communities. We are offering WoltLab Suite as a fully managed SaaS solution: https://www.woltlab.com/cloud/
====
This patch adds `woltlab-demo.com` to our existing PSL entry, because we plan to migrate our existing demo system to proper instances within WoltLab Cloud, allowing customers a smooth upgrade into a paid subscription. Our existing demo system was more locked down and did not allow for this upgrade into a subscription, making the security trade-off of not having the domain in PSL acceptable.
Due to this underlying technical change the same reasoning as with …
=> Update WoltLab Cloud Domains

public_suffix_list.dat
====
Organization Website: https://deno.land / https://deno.com
Deno Land Inc will provide hosting services to multiple tenants on subdomains of the https://deno.dev and https://deno-staging.dev domains.
====
- We issue LetsEncrypt certificates for our customers
- We want our customers' sites to be isolated from other customers (cookies, suffix highlighting, etc)
=======
```
dig +short TXT _psl.deno.dev
"https://github.com/publicsuffix/list/pull/1167"
```
```
dig +short TXT _psl.deno-staging.dev
"https://github.com/publicsuffix/list/pull/1167"
```
make test
=========
```
=================================================================== …
```
=> Add deno.dev and deno-staging.dev domains

public_suffix_list.dat
====
Organization Website: https://günstigbestellen.de
GünstigBestellen offers customers an ordering system as customizable software on a subdomain. I am an engineer at GünstigBestellen.
====
* We want to isolate cookies of our customer sites from each other
* We issue Let's Encrypt certificates for our customers
* It would be useful if the focus of the search bar is on the subdomain (customer name) instead of günstigbestellen.de
=======
```
dig +short TXT _psl.günstigbestellen.de
"https://github.com/publicsuffix/list/pull/1170"
```
```
dig +short TXT _psl.günstigliefern.de
"https://github.com/publicsuffix/list/pull/1170"
```
make test
=========
```
================================================================ …
```
=> Add GünstigBestellen domains

public_suffix_list.dat
====
Organization Website: https://incsub.com
Incsub is the parent company of [WPMU DEV](https://premium.wpmudev.org/) which provides web, email, and CDN hosting for our customers. I am the Chief Technical Officer of Incsub submitting this request.
====
The domains to be added are used for our web, email, and CDN hosting. Untrusted customers can create or be assigned subdomains of these parent domains for their use, so we need cookie security to help segment customer websites.
All domains are registered for a period of more than 2 years.
=======
DNS verification records have been created for each domain in this list:
```
dig +short TXT _psl.smushcdn.com
"https://github.com/publicsuffix/list/pull/1169"
```
``` …
```
=> Add needed suffixes for WPMU DEV hosting and CDNs

public_suffix_list.dat
====
Organization Website: https://www.shopify.com
My name is Alex, I'm an Application Security Engineer at Shopify.
Shopify is an e-commerce organization. We provide merchants with tools and services to sell their products online and/or in-person, with the ultimate goal of making commerce better for everyone. 
====
In addition to allowing merchants to purchase and/or connect their domain name to their shops, we provision all new merchants with a `*.myshopify.com` subdomain. Because of this, requests between shops using `*.myshopify.com` domains are considered to be samesite, leaving them open to CSRF.
We're looking to add `myshopify.com` to the Public Suffix List to improve cookie security for all of our merchants who do not yet make …
=> Add myshopify.com

public_suffix_list.dat
====
Organization Website: https://ghost.org
Ghost is a proud non-profit organisation building open source technology for journalism. We've built a sustainable business around a free core application, funded by a premium platform as a service to run it on.
====
Ghost's managed hosting service - Ghost(Pro) - allows users to deploy their own instance of Ghost to a subdomain of `ghost.io`. These instances are independent instances, and as such browsers should treat them as separate sites for Cookies and other security purposes.
=======
```
dig +short TXT _psl.ghost.io
"https://github.com/publicsuffix/list/pull/1180"
```
make test
=========
```
========================================================================= …
```
=> Added ghost.io to PSL

.github/workflows/tld-update.yml
I wanted to describe the situation in detail but it made for a long PR description. Here's the important parts up front:
* Travis & the old gTLD PR automation is effectively broken.
* Let's move the gTLD automation into this repo, using Github actions.
* If you agree, stamp this PR with an approval.
* And we need to coordinate on adding the @tld-update-bot's Github "personal access token" as a secret env var in this repo's config. (_Alternatively: maintainers can make their own account and plug a PAT in._)
Since ~August 2019 the gTLD section of `public_suffix_list.dat` has been kept up to date by a combination of the `tools/newgtlds.go` command [in this repo][newgtlds-cmd] and automation I've been maintaining in [a separate Github repo][cpu-autopull]. To date the bot has opened [67 pull …
=> CI: Add Github Actions workflow for TLD updates PRs.

public_suffix_list.dat
====
Organization Website: https://firewebkit.com
Firewebkit is tools and services available to develop the website.
====
Firewebkit provides free domains for the developers looking to quickly setup something (which is this fireweb.app)
=======
```
dig +short TXT _psl.fireweb.app
"https://github.com/publicsuffix/list/pull/1181"
```
make test
=========
Test ran fine with no failure
=> Added fireweb.app to PSL

public_suffix_list.dat
====
Organization Website: https://mythic-beasts.com
This is an amendment to the entry originally added in [PR #1075](https://github.com/publicsuffix/list/pull/1075).
Mythic Beasts is a hosting company offering a mix of web hosting, virtual and dedicated servers, as well as hosted Raspberry Pi servers.
vs.mythic-beasts.com is used by Virtual Servers.
x.mythic-beasts.com is used by Dedicated Servers.
hostedpi.com is used by Hosted Raspberry Pi servers.
customer.mythic-beasts.com is used by a mix of hosting.
All others used by customer web hosting.
Domains hostedpi.com, mythic-beasts.com and retrosnub.com all have an expiry date greater than 2 years and are in active use so will be maintained with greater than 2 year expiry.
====
A number …
=> Update Mythic Beasts domains

public_suffix_list.dat
====
Organization Website: https://developer.swisscom.com
We at Swisscom would like to remove the two entries scapp.io and applicationcloud.io for our Application Cloud (https://developer.swisscom.com) product.
Reason for PSL Removal
====
We do not want these entries anymore.
=> Remove scapp.io and applicationcloud.io from PSL

public_suffix_list.dat
====
Organization Website: https://freemyip.com
This is a Dynamic DNS service provider.
====
This is dynamic dns service, which means subdomains are registered by independent 3rd parties. It's important to treat them separately for cookie security reasons.
The domain is registered until 2023-12-16 and the registration will be extended annually to keep the required term.
=======
```
dig +short TXT _psl.freemyip.com
"https://github.com/publicsuffix/list/pull/1187"
```
make test
=========
Test completed successfully.
=> Add freemyip.com as Private domain

public_suffix_list.dat
====
Organization Website: https://ovhcloud.com
OVHcloud is an european company that provide Cloud services and hosting services.
====
In our hosting offer and Paas offer, we provide sudomains to allow developers to test their websites. We want to improve the cookie security on theses staging subdomains.
Our Paas offers are delivered as subdomains of [region].webpaas.ovh.net
Our hosting offers are delivered as sudomains of [clusterNumber].hosting.ovh.net
=======
```
dig +short TXT _psl.ovh.net
"https://github.com/publicsuffix/list/pull/1193"
```
make test
=========
``` …
```
=> Add hosting and paas from OVHcloud

public_suffix_list.dat
====
Organization Website: https://clickrising.com/
Hi, I'm Umut, CTO of ClickRising.
ClickRising is the revolutionary sponsorship platform where content creators and apps come together.
====
We provide some clients a custom `*.clickrising.net` subdomain for their dashboards.
We're looking to add `clickrising.net` to the Public Suffix List to improve cookie security for all of our clients.
The domain is registered for 2+ years.
=======
```
dig +short TXT _psl.clickrising.net
"https://github.com/publicsuffix/list/pull/1192"
```
make test
=========
Test passed OK
=> Add clickrising.net

public_suffix_list.dat
====
Organization Website: https://torproject.org/
I'm the senior sysadmin at the Tor Project, Inc. (proof at [the people page as well](https://www.torproject.org/about/people/)) empowered to represent the interests of the company (and the project) insofar as technical resources like DNS are concerned. 
====
The torproject.org domain is the main domain used by the Tor
Project. All machines under that domain are managed by the TPA
team (Tor Project sysAdmins).
The torproject.net domain, however, can be delegated to third parties
and is less trusted.
This is the same policy as the `debian.net` domain.
We will possibly start hosting "GitLab pages" under the
pages.torproject.net domain.
The goal of those changes is to make it more difficult …
=> add torproject.net

public_suffix_list.dat
* added appspacehosted.com
* added appspaceusercontent.com
====
Organization Website: https://www.appspace.com
Appspace is a content management platform for digital communication.
====
The appspacehosted.com domain is used for hosting customer specific content and should not be allowed to share cookies across subdomains/customers. The appspaceusercontent.com hosts customer generated html content and should not be allowed to persist cookies across subdomains/customers.
=======
```
dig +short TXT _psl.appspacehosted.com
"https://github.com/publicsuffix/list/pull/1197"
```
```
dig +short TXT _psl.appspaceusercontent.com
"https://github.com/publicsuffix/list/pull/1197"
```
make test
=========
Test Passed
=> Add Appspace to PSL

public_suffix_list.dat
====
Organization Website: https://northflank.com
Northflank is a fullstack cloud platform offering build and deployment of user services, jobs and databases.
====
Northflank creates subdomains for each hosted user service, job and publicly accessible database on northflank.app and code.run.
To make sure customer subdomains do not share cookies we and our users would like those domains to be added to the PSL.
=======
```
dig TXT _psl.northflank.app +short
"https://github.com/publicsuffix/list/pull/1198"
```
```
dig TXT _psl.code.run +short
"https://github.com/publicsuffix/list/pull/1198"
```
make test
=========
Tests passed
=> Add northflank.app and code.run to PSL

public_suffix_list.dat
====
Organization Website: https://docs.aws.amazon.com/global-accelerator/ , https://aws.amazon.com/
Amazon Web Services (AWS) is a cloud platform, offering a range of fully featured services from data centers globally.
AWS Global Accelerator is an AWS networking service that sends our customers' user’s traffic through Amazon Web Service’s global network infrastructure to customer endpoints (such as AWS Application Load Balancers (ALBs) or AWS EC2 instances). With Global Accelerator, our customers are provided two global static IPs as the entry point for their applications. 
Global Accelerator assigns each accelerator a default Domain Name System (DNS) subdomain, similar to 
`a1234567890abcdef.awsglobalaccelerator.com`
, that points to the static IP addresses …
=> Add awsglobalaccelerator.com

public_suffix_list.dat
====
Organization Website: https://mchost.ru
McHost is a hosting provider. We provide free subdomains in `.mcdir.me`, `.mcdir.ru` and `.vps.mcdir.ru` domains for our customers.
====
McHost's customers are allowed to publish their own sites in the .mcdir.me suffix, so we need to restrict cookie sharing between these subdomains. These domain names and DNS records will be kept renewed.
=======
```
dig +short TXT _psl.mcdir.me
"https://github.com/publicsuffix/list/pull/1206"
```
```
dig +short TXT _psl.mcpre.ru
"https://github.com/publicsuffix/list/pull/1206"
```
make test
=========
```
PASS: …
```
=> Add mcpre.ru, mcdir.me to mchost.ru subsection

public_suffix_list.dat
====
Organization Website: https://eurobyte.ru
Eurobyte is a hosting provider. We provide free subdomains in `.eurodir.ru` domain for our customers.
====
Eurobyte's customers are allowed to publish their own sites in the .eurodir.ru suffix, so we need to restrict cookie sharing between these subdomains. These domain names and DNS records will be kept renewed.
=======
```
dig +short TXT _psl.eurodir.ru
"https://github.com/publicsuffix/list/pull/1207"
```
make test
=========
```
Testsuite summary …
```
=> Add eurodir.ru

public_suffix_list.dat
====
Organization Website: https://northflank.com
Northflank is a fullstack cloud platform offering build and deployment of user services, jobs and databases.
====
A previous PR ([1198](https://github.com/publicsuffix/list/pull/1198)) was created to add northflank.app and code.run to the PSL. 
We now need to extend support for our customers at additional subdomains such as `*.addon.code.run`, `*.[clusterId].code.run`, `*.[userId].code.run` or `*.[region].northflank.app`. `[clusterId]`, `[userId]` and `[region]` represent a set of identifiers which might change in the future. Therefore a wildcard is required on the third level.
=======
```
dig TXT _psl.northflank.app +short …
```
=> Update Northflank domains

public_suffix_list.dat
Hello,
Jonathan Foote from the Fastly security team here, adding another PSL entry for the organization.
Update: This PR is ready for review.
Thanks,
Jon
====
Organization Website: [www.fastly.com](https://www.fastly.com)
Fastly’s global edge cloud platform processes, serves, and secures applications for users. See [www.fastly.com](https://www.fastly.com) for more information.
====
User (third-party) content is served from subdomains of edgecompute.app. Adding this domain to the PSL will stymie cookie stuffing attacks across these subdomains.
The registration term for edgecompute.app is greater than 2 years in the future, and it will be extended automatically in advance of expiration. 
```
% whois edgecompute.app | grep "Registry …
```
=> Add edgecompute.app

.github/workflows/tld-update.yml
The `.github/workflows/tld-update.yml` Github actions workflow used to update the gTLD data in the PSL dat file is presently configured to try and add a `tld-update` label to the PRs it creates.
In practice this requires admin access to the repo and we explicitly do not want the @tld-update-bot Github account used to create PRs to have that access.
The solution is simple: don't try to have the pull request action label the PR it creates. This will resolve the failure present in the action runs that create a PR (e.g. [this run](https://github.com/publicsuffix/list/runs/1938957607?check_suite_focus=true)).
=> CI: remove "labels" config from tld-update.yml workflow.

public_suffix_list.dat
====
Organization Website: https://noticeable.io
Noticeable is an all-in-one solution to update users effectively. You can use the service to engage customers or teammates with regular updates, get powerful feedback, and measure satisfaction.
I am the founder and CEO of Noticeable.
====
User (third-party) content is served from subdomains of _noticeable.news_. Adding this domain to the PSL will stymie cookie stuffing attacks across these subdomains.
The registration term for _noticeable.news_ has just been extended and is greater than 2 years: `2023-09-19T18:26:06.55Z`.
=======
```
$ dig +short TXT _psl.noticeable.news
"https://github.com/publicsuffix/list/pull/1216"
```
make test
=========
`make test` completed …
=> Add noticeable.news

public_suffix_list.dat
====
Organization Website: https://radwebhosting.com
My name is Scott Claeys, I am a network engineer, and I represent Rad Web Hosting.
Rad Web Hosting provides web hosting and servers to users around the globe.
====
User (third-party) content is served from subdomains of cloudsite.builders. Adding this domain to the PSL will stymie cookie stuffing attacks across these subdomains.
The registration term for cloudsite.builders is greater than 2 years in the future, and it will be extended automatically in advance of expiration.
```
% whois cloudsite.builders | grep "Registry Expiry"
Registry Expiry Date: 2023-07-28T09:23:41Z
```
=======
```
dig +short TXT _psl.cloudsite.builders …
```
=> Add cloudsite.builders

public_suffix_list.dat
====
Organization Website: https://sourcehut.org
I am the principal engineer at SourceHut. We are a software development forge, and provide hosting for static websites as one of our services.
====
This domain (srht.site) provides hosting for arbitrary user content. Each subdomain represents an independent entity and information sharing between pages is considered a security issue.
=======
```
dig +short TXT _psl.srht.site
"https://github.com/publicsuffix/list/pull/1218"
```
make test
=========
:heavy_check_mark: works
:vomiting_face: autotools
=> sourcehut: add srht.site

public_suffix_list.dat
====
Clerk provides user authentication as a service to developers.
Organization Website: https://clerk.dev
I am the founder and CEO of Clerk.
====
Our previous domains in the PSL are used in our production environment.  We are adding these domains so our staging environment also benefits from the cookie security protections and Let's Encrypt issuance limit increases afforded by the PSL.  The specific details listed for our production domains in #791 also apply here.
Note: We are awaiting assistance from our registrar to extend the duration.
=======
```
dig +short TXT _psl.lclstage.dev
"https://github.com/publicsuffix/list/pull/1222"
```
```
dig +short TXT _psl.stgstage.dev …
```
=> Add Clerk staging domains, change email to systems@

public_suffix_list.dat
Previously the email address was for an individual, in order to ensure that there is
deliverability for any emails regarding this suffix it would be prudent to
use our team support address for this purpose.
As this is not a change to the domains which were included in https://github.com/publicsuffix/list/pull/765 the previous information on that PR is still valid.
Tests have been run and pass
=> Update Email address for GOV.UK Platform as a Service

.github/workflows/tld-update.yml
Rather than checking for IANA updates every hour at 15 minutes past the hour, run every day, at 15:00 UTC
=> Switch the TLD update workflow to daily

public_suffix_list.dat
====
Boutir (https://www.boutir.com) helps individual merchants to build and host their online webstore. Merchant can use their own custom domain, or use *.boutir.com (e.g. https://ingoodhandsof.boutir.com), therefore we would like to have boutir.com in the public suffix list and have it as eTLD
I'm founder of Boutir, and built Boutir with other engineers in the team. 
Boutir is a SAAS business, merchants can subscribe our monthly / yearly plan to setup, maintain and operate their online webstore using our mobile app. There is also a free plan for merchants and they can setup their store (e.g. xxx.boutir.com) in 10 mins. 
Organization Website: https://www.boutir.com
====
With iOS14.5 launch, in accordance with their …
=> Add boutir.com

public_suffix_list.dat
====
Organization Website: https://www.pythonanywhere.com/
PythonAnywhere is an online software development and web-hosting environment, run by a UK company PythonAnywhere LLP.  We have a US-hosted site at https://www.pythonanywhere.com/, and a separate EU-hosted system at https://eu.pythonanywhere.com.
We allow users of our US-hosted system to create websites at *theirusername*`.pythonanywhere.com`, and users of our EU-hosted system to create websites at *theirusername*`.eu.pythonanywhere.com` so that they don't need to buy their own domain or learn about DNS just in order to get a website online.
====
We would like our two domains to be on the PSL to improve cookie security.  
We do *not* have any concerns regarding Let's Encrypt as …
=> Add subdomains of pythonanywhere.com and of eu.pythonanywhere.com

public_suffix_list.dat
This replaces #1230 and cleans up the merge change to only be the public_suffix_list.dat file, as requested by @dnsguru 
-----
Adding our root domain for our subdomained users for Magnet pages.
====
Service Magnet is a lead generation toolset for the small business service industry. Our customers provide information to us that allows us to generate and maintain landing pages for specific online advertisements so that non-technical users can benefit from online advertising for their businesses.
Each of our customers is assigned a specific subdomain, very much like Squarespace, Heroku, or Carrd does for their customers. We need these subdomains recognized as their own websites.
Organization Website: https://myservicemagnet.com
Note: our website is our marketing …
=> Add service magnet to PSL

public_suffix_list.dat
====
Organization Website: https://www.curvegrid.com/
Curvegrid is a blockchain software company. Our core product MultiBaas allows both independent developers and enterprise companies to rapidly prototype and build blockchain applications.
We are offering MultiBaas as a fully managed SaaS solution in which users/organizations get assigned sub-domains under multibaas.com and/or multibaas.app.
====
We would like multibaas.com and multibaas.app to be on the PSL to improve security as the sub-domains may be assigned/managed to/by different users/organizations.
The domains hold registration term longer than 2 years and we will maintain the registration term above this threshold.
=======
```
dig +short TXT …
```
=> Add multibaas.app and multibaas.com

public_suffix_list.dat
====
Organization Website: https://paywhirl.com
I am CTO of Paywhirl Inc - We are a recurring payment processor with a number of tools available for 3rd parties and custom development. 
====
We provide subdomain `*.paywhirl.com` to our users, allowing them to implement 3rd party tools and manage them. 
The domains hold registration terms longer than 2 years and we will maintain the registration term above this threshold.
=======
```
dig +short TXT _psl.paywhirl.com 
"https://github.com/publicsuffix/list/pull/1237"
```
make test
=========
The test ran successfully.
=> add paywhirl.com for site users

public_suffix_list.dat
We are a web hosting and cloud provider and the atl/njs/ric.jelastic.vps-host.net subdomains are used by our customers for the Jelastic cloud platform. 2 of the subdomains were already included in the list, but we wanted to update and maintain the list on our own. Every Jelastic customer we host will receive hosts from those subdomains and will be able to use them for previewing web apps and development.
We would like to include these subdomain + the main vps-host.net domain for improved cookie security. Be advised that we do not use the subdomains to request Letsencrypt certs because we do provide wildcard SSL certs for all subdomains.
```
[root@rb list]# dig  @8.8.8.8 _psl.vps-host.net TXT +short
"https://github.com/publicsuffix/list/pull/1242"
```
Let me know if TXT records are …
=> Update atl/njs/ric.jelastic.vps host.net

public_suffix_list.dat
Description of Organization We are a PaaS delivering customer identity and access management service
====
Organization Website: forgerock.com
Reason for PSL Inclusion Many web security features (notably cookies) rely on the notion of "registerable domain" (eTLD+1) rather than origin for their security boundary. Under this definition, every tenant could be in the same security context, and can for example overwrite each others' cookies and potentially steal them if misconfigured.
====
=======
make test
=========
=> Added forgeblocks.com to psl

public_suffix_list.dat
====
acces­so Tech­nol­o­gy Group plc, the pre­mier tech­nol­o­gy solu­tions provider to leisure, enter­tain­ment and cul­tur­al mar­kets
Organization Website: accesso.com
====
accesso hosts eCommerce solutions for our clients who are affected by the iOS 14 changes. We are seeking to add to the PSL to test an integration that will effectively counter the effects of the iOS 14 changes. 
=======
```
dig +short TXT devcdnaccesso.com
"https://github.com/publicsuffix/list/pull/1248"
```
make test
=========
This test ran with no syntax errors
=> accesso - Adding devcdnaccesso

public_suffix_list.dat
Responder (https://responder.co.il) provides solutions to business owners to communicate with their customers for about 15 years.
We provide a landing pages builder and serving solution for our customers using the https://ravpage.co.il domain.
I'm working w/ the company R&D team to enable the services to their customers.
Some of our customers are using custom domain w/ their landing pages that created w/ our platform. However, some prefer to use a dedicated subdomain under the ravpage.co.il domain.
$ dig TXT _psl.ravpage.co.il
https://github.com/publicsuffix/list/pull/1250
Here is a summary of the make test:
======================================================================= …
=> Add ravpage.co.il

public_suffix_list.dat
Organization Website: https://repl.it (nowadays called https://replit.com)
I'm an engineer at Repl.it.
Repl.it is an online programming environment allowing users to host terminal apps, static sites, and web apps.
By default we host all user created websites under `repl.co` and terminal apps under `repl.run` when a user doesn't provide their own domain. We would like to isolate cookies and be able to use Let's Encrypt with user's domains. The original PR that added these two suffixes is https://github.com/publicsuffix/list/pull/748 .
Since we allow people to rename their websites / apps, and also to try to avoid hitting hostname length limits when users choose their own names (using either `https://<website>--<username>.repl.co` or `https://<website>.<username>.repl.co`), we have added a …
=> Additional suffix `id.repl.co` for Repl.it

public_suffix_list.dat
====
====
=======
make test
=========
=> Update forgeblocks, add subdomain to psl

public_suffix_list.dat
====
Tradablebits is Digital Marketing platform working with in Sports and Entertainment industry.
Website is https://tradablebits.com
tbits.me - is a domain for client properties and url shorteners in addition to long version on tradablebits.com
I am co-founder of TradableBits and responsible for managing technical infrastructure.
====
Primary reason is new Facebook requirement to Pixel deployment and aggregate event measurement, where our properties must be registered in order to be considered for aggregated events. tbits.me has more than 2 years of expiration and we fully intend to maintain it
=======
```
dig +short TXT _psl.tbits.me
"https://github.com/publicsuffix/list/pull/1240"
```
make test
========= …
=> Adding Tradable Bits

public_suffix_list.dat
====
Organization Website: https://www.wix.com
Wix is a website building platform.
Registered users get their own subdomain (e.g. username.wixsite.com or username.editorx.io) on which their sites are hosted.
====
We'd like to properly isolate each subdomain to prevent global cookie setting on wixsite.com/editorx.io and highlight that each subdomain hosts sites of a different user, unrelated to the others.
=======
```
dig +short TXT _psl.wixsite.com
"https://github.com/publicsuffix/list/pull/927"
```
```
dig +short TXT _psl.editorx.io
"https://github.com/publicsuffix/list/pull/927"
```
make test
=========
https://gist.github.com/shahata/d1c21c6a7fc30c3f0f2cc9e29fe89add
=> Add wixsite.com and editorx.io

public_suffix_list.dat
removed gov.st from list of reserved domains since this zone acting as independent on its own
====
Organization Website: https://www.nic.st
ST Registry AB
.ST domain zone administrator
====
gov.st is operated as public domain and not reserved as subdomain. This zone is used directly by government of Sao Tome. Domain was excluded from list of reserved domains on: https://www.nic.st/terms-of-service 
We don't want to keep it in this list as well as change it to private zone.
=======
DONE
```
dig +short TXT _psl.gov.st
"https://github.com/publicsuffix/list/pull/1257"
```
make test
=========
test done
```
$ make test
./pslint_selftest.sh;                     \
./pslint.py …
```
=> exclude gov.st from publicsuffix since host act as public domain

public_suffix_list.dat
* [ x] Description of Organization
* [x ] Reason for PSL Inclusion
* [ x] DNS verification via dig
* [ x] Run Syntax Checker (make test)
====
Individual.
====
This adds missing entries that are stated on https://registry.nic.ss/ (pointed to via https://www.iana.org/domains/root/db/ss.html)
=======
Requesting DNS Verification be set aside as we are updating the entry for an existing entry to align it with the registry listed information that is verifiably listed at the authoritative registry listed with the IANA.
make test
=========
Ran with no issues.
=> addition of ss sld's sch.ss and me.ss

public_suffix_list.dat
====
Organization Website: https://www.pythonanywhere.com/
PythonAnywhere is an online software development and web-hosting environment, run by a UK company PythonAnywhere LLP. We have a US-hosted site at https://www.pythonanywhere.com/, and a separate EU-hosted system at https://eu.pythonanywhere.com.
We allow users of our US-hosted system to create websites at theirusername.pythonanywhere.com, and users of our EU-hosted system to create websites at theirusername.eu.pythonanywhere.com so that they don't need to buy their own domain or learn about DNS just in order to get a website online.
====
We would like our two domains to be on the PSL to improve cookie security. We believe that using the *. prefix was incorrect and so we are …
=> Update to pythonanywhere entries

public_suffix_list.dat
====
Organization Website: www.fearworkshosting.co.uk
FearWorks Media Ltd. provides web hosting and email services. I am the founder and director.
====
The subdomains under the hosp.uk domain are assigned to different hospitality customers of our company. We assign subdomains such as examplehotel.hosp.uk, etc. Our clients can use the assigned subdomain(s) to access their admin systems, backends and frontends.
We want to protect the user-created subdomains under the hosp.uk domains from cross-subdomain cookie/state sharing and also allow generation of Let's Encrypt SSL certificates for the custom subdomains.
The domain has a validity of at least 2 years and we'll continue to maintain it.
=======
```
dig +short …
```
=> Add hosp.uk to our existing domains

public_suffix_list.dat
====
Organization Website: https://interhop.org/projets/esante
We are a french association (InterHop) and we will host independent subdomains based on our Goupile (AGPL v3) product.
Goupile is a free and open-source electronic data capture application that strives to make form creation and data entry powerful, easy and secure for healthcare research.
====
Each customer will be (or already is) provided with their own subdomain (xxx.goupile.fr).
We want to increase the anti-CSRF security between customer subdomains through SameSite=Lax cookies (and maybe Strict later on).
=======
```
dig +short TXT _psl.goupile.fr
"https://github.com/publicsuffix/list/pull/1307"
```
make test
=========
Tests passed OK …
=> Add goupile.fr to PRIVATE section

public_suffix_list.dat
Delete domain ra-ru.ru and zsew.ru added via https://github.com/publicsuffix/list/pull/1149
```
% dig _psl.ra-ru.ru. +short txt
"https://github.com/publicsuffix/list/pull/1306"
```
```
% dig _psl.zsew.ru. +short txt
"https://github.com/publicsuffix/list/pull/1306"
```
=> REMOVE ra-ru.ru, zsew.ru (#1149)

public_suffix_list.dat
====
Organization Website: https://avstack.io
We provide hosted realtime video infrastructure (videoconferencing, livestreaming, virtual events, education and so on).
====
Customers are able to host realtime A/V infrastructure, including a web frontend, at subdomains of the domain `onavstack.net` proposed for inclusion here. These subdomains should be considered as different origins for security purposes (e.g. w.r.t browser cookies), as these customers are mutually untrusted.
The domain `onavstack.net` is not used for any other purpose.
`onavstack.net` is currently registered up to 2025-01-28 and will always maintain at least two years term.
=======
```
$ dig +short TXT _psl.onavstack.net …
```
=> Added onavstack.net to PRIVATE section of PSL

public_suffix_list.dat
====
Organization Website: https://staclar.com
Staclar provides a variety of services to digital music companies, record labels and independent artists.
====
Under novecore.site, we will be offering web hosting for artist websites. Listing in the PSL is requested for security reasons.
=======
```
dig +short TXT _psl.novecore.site
"https://github.com/publicsuffix/list/pull/1331"
```
make test
=========
Works
=> Add novecore.site

public_suffix_list.dat
====
Organization Website: github.com
I'm a software engineer at GitHub working on the Codespaces product.
====
We no longer want `github.dev` to be included in the PSL. The original intent for the addition was predicting several use cases that are no longer valid for our plans with `github.dev`. We have some initiatives that require removal.
=======
Do I still need to update DNS to this PR even though it is a removal? You can see the current record points to the PR where we added the domain: https://github.com/publicsuffix/list/pull/1290
make test
=========
=> Remove github.dev from PSL

public_suffix_list.dat
This is a follow up to a previous PR that was using our primary domain name. I've created this PR that uses a secondary domain that simply redirects to the primary. There is less risk as the secondary is not linked anywhere. https://github.com/publicsuffix/list/pull/1342
====
Organization Website: https://adimo.co & https://adimo.co.uk (for which this change applies)
We are a global shoppable technology provider for brands across the world. our clients include Nestlé, Unilever, SC Johnson and many other large multi national organisations. These brands use our technology to make their websites shoppable, allowing consumers to add products to their online retailer's shopping cart.
====
Our clients …
=> Adding adimo.co.uk

public_suffix_list.dat
Organization Website: https://www.appudo.com
Appudo UG (haftungsbeschränkt) offers web-based applications and services.
We want the ability to dynamically register a DNS name for the installation and secure usage of our applications with user or third-party-provided machines.
Note that the appudo.net domain is auto-renewed yearly.
```
whois appudo.net | egrep "(^Updated Date|^Creation Date|Expiration Date)"                          
Updated Date: 2021-05-22T10:35:02Z
Creation Date: 2011-05-21T12:02:12Z                               
Registrar Registration Expiration Date: 2022-05-21T12:02:12Z
```
```
dig +short TXT _psl.appudo.net
"https://github.com/publicsuffix/list/pull/1340"
```
```
```
=> Add appudo.net

public_suffix_list.dat
Organization Website: https://sendmsg.co.il
sendmsg provides solutions to business owners to communicate with their customers for about 10 years.
We provide a landing pages platform and serving solution for our customers.
Registered users get their own subdomain (e.g. username.minisite.ms) on which their sites are hosted.
Some of our customers are using custom domain with their landing pages that created with our platform. However, some prefer to use a dedicated subdomain under the minisite.ms domain.
$ dig TXT _psl.minisite.ms
#1344
====================================================================== …
=> Add minisite.ms

tools/newgtlds.go
Only change is to add a URL to the IANA TLD txt file and some comment lines to add context.
Doesn't solve #1325 but helps identify the resource to use.
=> newgtlds.go : update Autopull - Added URL for the IANA PSL for #1325

public_suffix_list.dat
====
Organization Website: https://mediatech.by https://mediatech.dev
We're company developing applications and solutions for TV and OTT
====
We're hosting different clients applications/sites/api under our mediatech.by / mediatech.dev subdomains.
=======
```
$  dig +short TXT _psl.mediatech.by
"https://github.com/publicsuffix/list/pull/1333"
$  dig +short TXT _psl.mediatech.dev
"https://github.com/publicsuffix/list/pull/1333"
```
-->
make test
=========
All the tests passed.
=> add mediatech.by and mediatech.dev domains

public_suffix_list.dat
====
Organization Website: https://brendly.rs
My name is Dusan, I'm a CTO at Brendly.
Brendly is an e-commerce organization. We provide merchants with tools and services to sell their products online and/or in-person, with the ultimate goal of making commerce better for everyone.
====
In addition to allowing merchants to purchase and/or connect their domain name to their shops, we provision all new merchants with a *.shop.brendly.rs subdomain. Because of this, requests between shops using *.shop.brendly.rs domains are considered to be samesite, leaving them open to CSRF.
We're looking to add shop.brendly.rs to the Public Suffix List to improve cookie security for all of our merchants who do not yet make use of a custom domain.
DNS …
=> Add shop.brendly.rs

public_suffix_list.dat
---
(Link: [about propogation/expectations](https://github.com/publicsuffix/list/wiki/Guidelines#appropriate-expectations-on-derivative-propagation-use-or-inclusion))
---
====
Organization Website: https://ddns5.com
ddns5.com is a free service to support HTTP based dynamic DNS
to support and enable rapid-deployment of WebRTC relays and servers.
WebRTC servers require SSL when accessed from browsers in order 
for browsers to enable camera recording. Thus easy dynamic DNS setup
allows users to learn WebRTC in the quickest way possible. 
(When combined with WebRTC relays supporting ddns5.com)
ddns5.com is created and run by an individual, Cameron Elliott,
with more info at http://cameronelliott.com
ddns5.com is run on a .com …
=> Add ddns5.com to private section

public_suffix_list.dat
* [ X ] Description of Organization
* [ X ] Reason for PSL Removal
* [ X ] Run Syntax Checker (make test)
* [ X ] Each domain listed in the PRIVATE section has and shall maintain at least two years remaining on registration, and we shall keep the _PSL txt record in place
* [ X ] We are listing any third party limits that we seek to work around in our rationale such as those between IOS 14.5+ and Facebook (see [Issue #1245](https://github.com/publicsuffix/list/issues/1245) as a well-documented example)
* [ X ] This request was _not_ submitted with the objective of working around other third party limits
* [ X ] The [Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines) were carefully _read_ and _understood_, and this request conforms
* [ X …
=> Removing private subregistry aprendemas.cl due to deprecation.

public_suffix_list.dat
---
====
I purchased the domain uwu.nu on 2021-07-07 with the intention of using it for a website. At the time of purchase I was unaware of it being a part of this list.
The previous owner added it to the list in pull request #1014, and their project seems to be mostly abandoned at this point.
I have no intentions of making subdomains available/for sale and would therefore like uwu.nu removed.
=======
I will edit the dns records once the pull request has been submitted **(Edit: done)**
```
dig +short TXT _psl.uwu.nu
"https://github.com/publicsuffix/list/pull/1377"
```
=> Remove uwu.nu

public_suffix_list.dat
====
Organization Website: https://atlassian.com
I am an engineer at Atlassian, we make a variety of teamwork tools like Jira and Confluence. We host apps from third party developers on `*.cdn.prod.atlassian-dev.net` and display them in our products using iframes.
====
For security reasons given that we use this domain for hosting arbitrary user-generated HTML/JS/CSS content.
=======
```
dig +short TXT _psl.cdn.prod.atlassian-dev.net
"https://github.com/publicsuffix/list/pull/1357"
```
make test
=========
Unable to run full suite due to `libicu` issues. Would be great if someone could double check or provide guidance.
```
make test …
```
=> Add cdn.prod.atlassian-dev.net
